/**
 * @file features/features-page/components/FeaturesFullPage.tsx
 * @description Full features listing page component for LearnVeda
 * Groups all platform features by category with detailed descriptions
 */

"use client";

import React from "react";
import { motion } from "framer-motion";
import {
  BookOpen, Brain, Code2, FlaskConical, Trophy, Users,
  BarChart3, Shield, Smartphone, Globe, Award, Zap,
  Video, Calendar, Download, Bell, Search, Sparkles,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";

/* ─── Feature Categories ─────────────────────────────────────────────────── */
const featureGroups = [
  {
    category: "Learning Content",
    icon: <BookOpen className="h-5 w-5" />,
    color: "text-blue-500",
    bg: "bg-blue-500/10",
    features: [
      { name: "CBSE Class 9–12",       desc: "Complete NCERT-aligned curriculum for all 6 major subjects per class — Math, Science (Physics/Chemistry/Biology), English, Hindi, Social Science, Computer, AI." },
      { name: "Engineering Tracks",    desc: "9 branches × 8 semesters — CSE, ECE, EEE, Mechanical, Civil, Chemical, AI & ML, Data Science, IT — with full subject coverage." },
      { name: "Programming Day Plans", desc: "Structured N-day plans for 14 languages (C, C++, Java, Python, JS, TS, Rust, Go, Kotlin, Swift, SQL, Dart, Ruby) from first principles to project-level." },
      { name: "Core CS Subjects",      desc: "DSA (60d), Web Dev (30d), System Design (25d), DBMS, OS, CN, Git, Competitive Programming (60d), Interview Prep (30d)." },
      { name: "NCERT Solutions",       desc: "Step-by-step NCERT solutions for every chapter with detailed explanations, diagrams, and worked examples." },
      { name: "Previous Year Papers",  desc: "CBSE, JEE, NEET, GATE, and company placement papers with detailed solutions." },
    ],
  },
  {
    category: "AI & Personalization",
    icon: <Brain className="h-5 w-5" />,
    color: "text-purple-500",
    bg: "bg-purple-500/10",
    features: [
      { name: "AI Tutor (24/7)",          desc: "Ask any academic question and get a clear, example-rich explanation instantly — powered by state-of-the-art AI." },
      { name: "Adaptive Learning",        desc: "The platform identifies your weak areas and automatically adjusts which practice questions and content it shows you." },
      { name: "AI-Generated Practice",    desc: "Infinite unique practice questions generated by AI for any topic, at any difficulty level." },
      { name: "Personalized Roadmap",     desc: "Get a custom learning roadmap based on your goal (board exam, JEE, placement, etc.) and available time." },
      { name: "Smart Doubt Solver",       desc: "Upload a photo of a handwritten problem and get a step-by-step AI solution with explanation." },
    ],
  },
  {
    category: "Interactive Simulations",
    icon: <FlaskConical className="h-5 w-5" />,
    color: "text-cyan-500",
    bg: "bg-cyan-500/10",
    features: [
      { name: "Physics Simulations",      desc: "35+ simulations — Newton's Laws, Optics, Electrostatics, Waves, Gravitation, Thermodynamics, with real-time telemetry." },
      { name: "Chemistry Lab",            desc: "20+ simulations — Molecular bonding, Titration, Organic reactions, Periodic trends, Electrochemistry." },
      { name: "DSA Visualizer",           desc: "25+ step-by-step visualizations — Trees, Graphs, Sorting algorithms, Search algorithms, Dynamic Programming." },
      { name: "OS & Network Sims",        desc: "CPU execution cycle, Process scheduling, TCP/IP packet journey, DNS resolution, OSI layer walkthroughs." },
      { name: "Digital Logic & Circuits", desc: "Build and simulate logic gates, flip-flops, circuit diagrams, and Boolean algebra in the browser." },
    ],
  },
  {
    category: "Gamification & Battles",
    icon: <Trophy className="h-5 w-5" />,
    color: "text-yellow-500",
    bg: "bg-yellow-500/10",
    features: [
      { name: "Live 1v1 Battles",         desc: "Real-time coding and quiz battles with Elo matchmaking, <200ms latency, anti-cheat, and live score updates." },
      { name: "XP & Level System",        desc: "100-level quadratic XP system (100 × (level-1)²). Progress from Bronze Learner to Grandmaster." },
      { name: "Streak Tracking",          desc: "Daily learning streaks with fire animations, longest streak records, and 'at-risk' warnings." },
      { name: "Leaderboard",              desc: "Global, class-wise, and subject-wise leaderboards updated in real-time." },
      { name: "Achievement Badges",       desc: "50+ named achievement badges — First Battle, 30-Day Streak, Python Master, DSA Champion, and more." },
    ],
  },
  {
    category: "Practice & Tests",
    icon: <Zap className="h-5 w-5" />,
    color: "text-orange-500",
    bg: "bg-orange-500/10",
    features: [
      { name: "Quiz Engine",              desc: "Randomized quizzes for any chapter with instant feedback, explanations, and detailed score breakdown." },
      { name: "Mock Tests",               desc: "Full-length CBSE, JEE, NEET, GATE, and company assessment mock tests with timer and analysis." },
      { name: "Coding Playground",        desc: "In-browser IDE supporting 14 languages with test case runner, input/output, and execution time tracking." },
      { name: "Assignment Tracker",       desc: "Create, assign, and track custom assignments. Review submissions and provide feedback." },
    ],
  },
  {
    category: "Community & Collaboration",
    icon: <Users className="h-5 w-5" />,
    color: "text-green-500",
    bg: "bg-green-500/10",
    features: [
      { name: "Q&A Forums",               desc: "Categorized by subject, class, and topic. Upvotes, mentor badges, resolved state, and rich text with LaTeX." },
      { name: "Study Groups",             desc: "Create private or public study groups, share resources, schedule group sessions, and track group progress." },
      { name: "Live Study Rooms",         desc: "Real-time collaborative study rooms with shared whiteboard, voice chat, and live code editor." },
      { name: "Events & Competitions",    desc: "Monthly olympiads, code sprints, hackathons, and subject championships with real prizes." },
      { name: "Mentorship",               desc: "Connect with verified expert mentors for personalized guidance on exams, placements, and college prep." },
    ],
  },
  {
    category: "Dashboard & Analytics",
    icon: <BarChart3 className="h-5 w-5" />,
    color: "text-indigo-500",
    bg: "bg-indigo-500/10",
    features: [
      { name: "Progress Dashboard",       desc: "Visualize XP earned, chapters completed, time studied, weak areas, and improvement over time." },
      { name: "52-Week Heatmap",          desc: "GitHub-style activity heatmap showing daily study intensity across the year." },
      { name: "Subject Analytics",        desc: "Per-subject performance trends, accuracy rates, and comparison with top students." },
      { name: "Calendar Integration",     desc: "Study planner with Google Calendar sync, daily goals, reminders, and upcoming test dates." },
      { name: "Parent Dashboard",         desc: "Parents get a dedicated view of their child's progress, time spent, test scores, and activity patterns." },
    ],
  },
  {
    category: "Security & Privacy",
    icon: <Shield className="h-5 w-5" />,
    color: "text-red-500",
    bg: "bg-red-500/10",
    features: [
      { name: "Clerk Authentication",     desc: "Industry-standard auth with email/password, Google, GitHub OAuth, OTP, and 2FA support." },
      { name: "Zero Ads",                 desc: "No advertisements, no tracking pixels, no selling user data. Ever. Education should be distraction-free." },
      { name: "Data Encryption",          desc: "All data encrypted in transit (TLS 1.3) and at rest (AES-256). Passwords hashed with Argon2." },
      { name: "GDPR & Privacy",           desc: "Full GDPR compliance, data export, account deletion, and cookie consent management." },
      { name: "Anti-Cheat System",        desc: "Battle mode includes F12 blocking, tab-switch detection, copy-paste prevention, and violation logging." },
    ],
  },
];

/* ─── Features Full Page Component ───────────────────────────────────────── */
export function FeaturesFullPage() {
  return (
    <div>
      {/* Hero */}
      <section className="py-20 md:py-28 text-center bg-gradient-to-b from-muted/40 to-background">
        <div className="container px-4 md:px-6 max-w-3xl mx-auto">
          <Badge variant="outline" className="mb-4 text-brand-500 border-brand-500/30">
            <Sparkles className="h-3 w-3 mr-1" /> All Features
          </Badge>
          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight mb-4">
            Everything in{" "}
            <span className="text-gradient">LearnVeda</span>
          </h1>
          <p className="text-lg text-muted-foreground">
            A comprehensive overview of every feature — from AI tutoring to live battles, simulations to community.
          </p>
        </div>
      </section>

      {/* Feature groups */}
      <section className="py-12 pb-24">
        <div className="container px-4 md:px-6 space-y-16">
          {featureGroups.map((group, gi) => (
            <motion.div
              key={group.category}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.5, delay: gi * 0.05 }}
            >
              {/* Group header */}
              <div className="flex items-center gap-3 mb-6">
                <div className={`flex h-10 w-10 items-center justify-center rounded-xl ${group.bg} ${group.color}`}>
                  {group.icon}
                </div>
                <h2 className="text-2xl font-bold">{group.category}</h2>
              </div>

              {/* Feature cards grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {group.features.map((feature, fi) => (
                  <div
                    key={feature.name}
                    className="rounded-xl border bg-card p-5 hover:shadow-md hover:-translate-y-0.5 transition-all duration-200"
                  >
                    <h3 className="font-semibold mb-2 text-sm">{feature.name}</h3>
                    <p className="text-xs text-muted-foreground leading-relaxed">{feature.desc}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  );
}
