/**
 * @file lib/content/class11-mathematics.ts
 * @description Single source of truth for real, NCERT-aligned Class 11 Mathematics
 * curriculum content — chapters, theory, formulas, and MCQs.
 *
 * Reusable by:
 *   1. scripts/seed/seed-content.ts      — seeds into MongoDB
 *   2. lib/services/content-service.ts   — demo-mode fallback
 *
 * Every chapter matches NCERT Class 11 Mathematics (2025-26 edition).
 */

import type { ContentChapter } from "./class9-mathematics"; // Re-use shared types

/* ─── Class 11 Mathematics — Full Chapter List (NCERT 2025-26) ──────────── */
export const CLASS_11_MATHEMATICS_CHAPTERS: ContentChapter[] = [
  {
    chapterId: "chapter-01",
    order: 1,
    title: "Sets",
    objective: "Understand sets, types of sets, operations on sets, and Venn diagrams.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Definition of a Set", content: "A set is a well-defined collection of distinct objects, called elements or members. Sets are denoted by capital letters and elements by lowercase letters." },
      { heading: "Types of Sets", content: "Empty Set (∅ or {}), Finite Set, Infinite Set, Singleton Set, Equal Sets, Equivalent Sets, Subsets, Power Set, Universal Set." },
      { heading: "Operations on Sets", content: "Union (A ∪ B), Intersection (A ∩ B), Difference (A – B), Complement (A'), Symmetric Difference (A △ B)." },
      { heading: "Venn Diagrams", content: "Venn diagrams are pictorial representations of sets and their relationships. They are rectangles for universal set with circles for subsets." },
      { heading: "De Morgan's Laws", content: "(A ∪ B)' = A' ∩ B' and (A ∩ B)' = A' ∪ B'." },
    ],
    keyFormulas: [
      { label: "n(A ∪ B)", formula: "n(A) + n(B) – n(A ∩ B)" },
      { label: "n(A ∪ B ∪ C)", formula: "n(A) + n(B) + n(C) – n(A ∩ B) – n(B ∩ C) – n(A ∩ C) + n(A ∩ B ∩ C)" },
      { label: "Power Set cardinality", formula: "|P(A)| = 2^n where n = |A|" },
    ],
    keyPoints: [
      "Every set is a subset of itself; the empty set is a subset of every set.",
      "A set with n elements has 2^n subsets.",
      "The complement of a set A is the set of all elements in U but not in A.",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "If A = {1,2,3} and B = {2,3,4}, then A ∪ B is:", options: ["{2,3}", "{1,2,3,4}", "{1,4}", "{2,3,4}"], answer: 1 },
      { question: "n(A ∩ B) if n(A)=10, n(B)=8, n(A∪B)=15 is:", options: ["3", "2", "5", "18"], answer: 0 },
      { question: "Power set of {a, b} has how many elements?", options: ["2", "4", "8", "3"], answer: 1 },
    ],
    prevChapterId: undefined,
    nextChapterId: "chapter-02",
  },
  {
    chapterId: "chapter-02",
    order: 2,
    title: "Relations and Functions",
    objective: "Understand ordered pairs, Cartesian products, relations, functions, domain, codomain, and range.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Ordered Pairs & Cartesian Product", content: "An ordered pair (a, b) is a pair of elements with a specific order. A × B = {(a, b) : a ∈ A, b ∈ B}." },
      { heading: "Relations", content: "A relation R from set A to B is a subset of A × B. The domain is the set of all first elements; the range is the set of all second elements." },
      { heading: "Functions", content: "A function f: A → B is a relation where every element of A has exactly one image in B. A is the domain, B is the codomain." },
      { heading: "Types of Functions", content: "One-One (injective): different elements in domain have different images. Onto (surjective): every element of codomain has a pre-image. Bijective: both one-one and onto." },
      { heading: "Real Functions", content: "Identity function, constant function, polynomial function, rational function, modulus function, signum function, greatest integer function." },
    ],
    keyFormulas: [
      { label: "Cartesian Product size", formula: "n(A × B) = n(A) × n(B)" },
      { label: "Number of relations from A to B", formula: "2^(n(A) × n(B))" },
      { label: "Number of functions from A to B", formula: "[n(B)]^[n(A)]" },
    ],
    keyPoints: [
      "Every function is a relation but every relation is not a function.",
      "If f(x) = y, then y is called the image of x and x is called the pre-image of y.",
      "The range is always a subset of the codomain.",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "If A = {1,2} and B = {a,b,c}, then n(A × B) = ", options: ["5", "6", "4", "3"], answer: 1 },
      { question: "f(x) = x² is a one-one function on:", options: ["R", "[0, ∞)", "(-∞, 0]", "Both B and C"], answer: 1 },
      { question: "Domain of f(x) = √(x – 3) is:", options: ["x > 3", "x ≥ 3", "x < 3", "x ≤ 3"], answer: 1 },
    ],
    prevChapterId: "chapter-01",
    nextChapterId: "chapter-03",
  },
  {
    chapterId: "chapter-03",
    order: 3,
    title: "Trigonometric Functions",
    objective: "Study angles, radian measure, trigonometric ratios, identities, and graphs of trig functions.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Angles and Measurement", content: "Angles can be measured in degrees or radians. 1 radian = 180°/π ≈ 57.3°. Arc length l = rθ where r is radius and θ is in radians." },
      { heading: "Trigonometric Ratios", content: "sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse, tan θ = sin θ / cos θ, cosec θ = 1/sin θ, sec θ = 1/cos θ, cot θ = 1/tan θ." },
      { heading: "Fundamental Identities", content: "sin²θ + cos²θ = 1; 1 + tan²θ = sec²θ; 1 + cot²θ = cosec²θ." },
      { heading: "Sum and Difference Formulas", content: "sin(A ± B) = sinA cosB ± cosA sinB; cos(A ± B) = cosA cosB ∓ sinA sinB." },
      { heading: "Multiple Angle Formulas", content: "sin 2A = 2 sinA cosA; cos 2A = cos²A – sin²A = 2cos²A – 1 = 1 – 2sin²A; tan 2A = 2tanA/(1 – tan²A)." },
    ],
    keyFormulas: [
      { label: "Radian ↔ Degree", formula: "θ (radians) = π/180 × θ (degrees)" },
      { label: "sin(A+B)", formula: "sinA cosB + cosA sinB" },
      { label: "cos(A+B)", formula: "cosA cosB – sinA sinB" },
      { label: "sin 2A", formula: "2 sinA cosA" },
      { label: "cos 2A", formula: "1 – 2sin²A = 2cos²A – 1" },
    ],
    keyPoints: [
      "All trig ratios can be derived from sin and cos.",
      "The period of sin and cos is 2π; the period of tan and cot is π.",
      "sinC + sinD = 2 sin((C+D)/2) cos((C–D)/2).",
    ],
    hasSimulation: true,
    simulationDescription: "Interactive unit circle showing all trig ratios changing as angle varies.",
    sampleQuestions: [
      { question: "sin 30° + cos 60° = ?", options: ["1", "0.5", "√3/2", "1.5"], answer: 0 },
      { question: "cos 2A in terms of cosA is:", options: ["2cos²A – 1", "1 – 2sin²A", "cos²A – sin²A", "All of the above"], answer: 3 },
      { question: "Value of sin(π) is:", options: ["1", "0", "-1", "Undefined"], answer: 1 },
    ],
    prevChapterId: "chapter-02",
    nextChapterId: "chapter-04",
  },
  {
    chapterId: "chapter-04",
    order: 4,
    title: "Principle of Mathematical Induction",
    objective: "Learn the principle of mathematical induction and apply it to prove mathematical statements.",
    durationLabel: "2 days",
    theoryPoints: [
      { heading: "Statement of PMI", content: "If P(n) is a statement about natural numbers, and (i) P(1) is true, and (ii) P(k) being true implies P(k+1) is true, then P(n) is true for all n ∈ N." },
      { heading: "Steps of Proof", content: "Step 1 (Base case): Verify P(1) is true. Step 2 (Inductive step): Assume P(k) is true, prove P(k+1) is true." },
    ],
    keyFormulas: [
      { label: "Sum of first n natural numbers", formula: "1 + 2 + 3 + … + n = n(n+1)/2" },
      { label: "Sum of squares", formula: "1² + 2² + … + n² = n(n+1)(2n+1)/6" },
      { label: "Sum of cubes", formula: "1³ + 2³ + … + n³ = [n(n+1)/2]²" },
    ],
    keyPoints: [
      "Induction proves a statement for all natural numbers.",
      "The assumption P(k) is called the induction hypothesis.",
      "Both the base step and inductive step are necessary.",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "1 + 2 + 3 + … + 10 = ?", options: ["45", "50", "55", "60"], answer: 2 },
      { question: "Which step is the 'induction hypothesis'?", options: ["Proving P(1)", "Assuming P(k)", "Proving P(k+1)", "Conclusion"], answer: 1 },
      { question: "Sum of first n odd numbers = ?", options: ["n(n+1)/2", "n²", "2n-1", "n(n+2)"], answer: 1 },
    ],
    prevChapterId: "chapter-03",
    nextChapterId: "chapter-05",
  },
  {
    chapterId: "chapter-05",
    order: 5,
    title: "Complex Numbers and Quadratic Equations",
    objective: "Understand complex numbers, their algebra, Argand plane, modulus, argument, and quadratic equations with complex roots.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Complex Numbers", content: "A complex number z = a + bi where a, b ∈ R and i = √(–1). 'a' is the real part, 'b' is the imaginary part." },
      { heading: "Algebra of Complex Numbers", content: "Addition: (a+bi)+(c+di) = (a+c)+(b+d)i. Multiplication: (a+bi)(c+di) = (ac–bd)+(ad+bc)i." },
      { heading: "Modulus and Argument", content: "|z| = √(a²+b²). arg(z) = θ = tan⁻¹(b/a). Polar form: z = |z|(cosθ + i sinθ)." },
      { heading: "Conjugate", content: "Conjugate of z = a+bi is z̄ = a–bi. z × z̄ = |z|². (z + z̄) = 2a (real part doubled)." },
      { heading: "Quadratic Equations", content: "For ax²+bx+c=0, if discriminant D = b²–4ac < 0, roots are complex: x = (–b ± i√|D|) / 2a." },
    ],
    keyFormulas: [
      { label: "i² = –1, i³ = –i, i⁴ = 1", formula: "Powers of i cycle every 4" },
      { label: "Modulus", formula: "|z| = |a+bi| = √(a² + b²)" },
      { label: "Polar form", formula: "z = r(cosθ + i sinθ) = re^(iθ)" },
      { label: "De Moivre's theorem", formula: "(cosθ + i sinθ)ⁿ = cos(nθ) + i sin(nθ)" },
    ],
    keyPoints: [
      "i = √(–1), i² = –1, the imaginary unit.",
      "Complex roots of a polynomial with real coefficients always occur in conjugate pairs.",
      "The Argand plane (complex plane) represents complex numbers geometrically.",
    ],
    hasSimulation: true,
    simulationDescription: "Argand plane plotter — visualize complex numbers, modulus, and argument interactively.",
    sampleQuestions: [
      { question: "i⁴ = ?", options: ["1", "–1", "i", "–i"], answer: 0 },
      { question: "|3 + 4i| = ?", options: ["7", "5", "√7", "25"], answer: 1 },
      { question: "Conjugate of 2 – 3i is:", options: ["–2 + 3i", "2 + 3i", "–2 – 3i", "3 + 2i"], answer: 1 },
    ],
    prevChapterId: "chapter-04",
    nextChapterId: "chapter-06",
  },
  {
    chapterId: "chapter-06",
    order: 6,
    title: "Linear Inequalities",
    objective: "Solve linear inequalities in one and two variables and represent solutions graphically.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Inequalities", content: "An inequality is a mathematical statement that compares two expressions using <, >, ≤, or ≥." },
      { heading: "Rules for Inequalities", content: "Adding or subtracting the same number on both sides preserves inequality. Multiplying/dividing by a positive number preserves; by a negative number, it reverses the inequality sign." },
      { heading: "Linear Inequalities in Two Variables", content: "ax + by < c represents a half-plane. The boundary line ax + by = c divides the plane into two half-planes. Check (0,0) to determine the correct region." },
    ],
    keyFormulas: [
      { label: "Linear inequality solution", formula: "ax + b ≤ 0 → x ≤ –b/a (when a > 0)" },
    ],
    keyPoints: [
      "When multiplying or dividing by a negative number, reverse the inequality sign.",
      "Solid lines are used for ≤ or ≥; dashed lines for strict inequalities.",
      "The solution region must satisfy all inequalities simultaneously (for systems).",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Solve: 2x – 3 > 7. Answer is:", options: ["x > 5", "x < 5", "x > 2", "x < 2"], answer: 0 },
      { question: "If a < b and c < 0, then ac ___ bc.", options: [">", "<", "=", "≥"], answer: 0 },
      { question: "Graph of x + y ≤ 4 includes which point?", options: ["(3,2)", "(2,3)", "(1,2)", "(4,1)"], answer: 2 },
    ],
    prevChapterId: "chapter-05",
    nextChapterId: "chapter-07",
  },
  {
    chapterId: "chapter-07",
    order: 7,
    title: "Permutations and Combinations",
    objective: "Apply the fundamental counting principle, permutations, and combinations to counting problems.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Fundamental Counting Principle", content: "If event A can occur in m ways and event B in n ways, then both can occur together in m × n ways." },
      { heading: "Permutations", content: "A permutation is an arrangement of objects. P(n,r) = n!/(n–r)! = number of ways to arrange r objects from n distinct objects." },
      { heading: "Combinations", content: "A combination is a selection of objects. C(n,r) = n! / [r!(n–r)!] = nCr. Order does not matter." },
      { heading: "Relationship", content: "P(n,r) = C(n,r) × r! — permutations = combinations × arrangements." },
    ],
    keyFormulas: [
      { label: "Permutation", formula: "nPr = n! / (n–r)!" },
      { label: "Combination", formula: "nCr = n! / (r!(n–r)!)" },
      { label: "nC0 = nCn = 1", formula: "Boundary values of combination" },
      { label: "nCr = nC(n–r)", formula: "Symmetry of combinations" },
    ],
    keyPoints: [
      "0! = 1 by definition.",
      "nCr + nC(r–1) = (n+1)Cr (Pascal's identity).",
      "Circular permutations of n objects = (n–1)!.",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "5P3 = ?", options: ["60", "20", "10", "120"], answer: 0 },
      { question: "5C2 = ?", options: ["20", "10", "5", "15"], answer: 1 },
      { question: "In how many ways can 6 people sit in a row?", options: ["720", "120", "360", "24"], answer: 0 },
    ],
    prevChapterId: "chapter-06",
    nextChapterId: "chapter-08",
  },
  {
    chapterId: "chapter-08",
    order: 8,
    title: "Binomial Theorem",
    objective: "Apply the binomial theorem to expand (a+b)^n and find specific terms.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Binomial Theorem", content: "(a + b)^n = Σ(r=0 to n) nCr × a^(n–r) × b^r. There are n+1 terms in the expansion." },
      { heading: "General Term", content: "The (r+1)th term: T(r+1) = nCr × a^(n–r) × b^r." },
      { heading: "Middle Term", content: "For even n: middle term is T(n/2 + 1). For odd n: two middle terms T((n+1)/2) and T((n+3)/2)." },
    ],
    keyFormulas: [
      { label: "Binomial expansion", formula: "(a+b)^n = Σ nCr × a^(n–r) × b^r" },
      { label: "General term T(r+1)", formula: "nCr × a^(n–r) × b^r" },
      { label: "Sum of all coefficients", formula: "Set a=b=1: 2^n" },
    ],
    keyPoints: [
      "The binomial coefficients are symmetric: nCr = nC(n–r).",
      "Pascal's triangle gives binomial coefficients.",
      "Sum of binomial coefficients in (1+x)^n is 2^n.",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Number of terms in (a+b)^7 is:", options: ["7", "8", "9", "6"], answer: 1 },
      { question: "Coefficient of x³ in (1+x)^5 is:", options: ["10", "5", "20", "15"], answer: 0 },
      { question: "T4 in (x+2)^6 =?", options: ["160x³", "240x³", "120x³", "80x³"], answer: 1 },
    ],
    prevChapterId: "chapter-07",
    nextChapterId: "chapter-09",
  },
  {
    chapterId: "chapter-09",
    order: 9,
    title: "Sequences and Series",
    objective: "Study arithmetic progressions, geometric progressions, sum formulas, and the special series.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Arithmetic Progression (AP)", content: "A sequence where each term differs from the previous by a constant d (common difference). a, a+d, a+2d, … . nth term: aₙ = a + (n–1)d." },
      { heading: "Geometric Progression (GP)", content: "A sequence where each term is r times the previous (common ratio r). a, ar, ar², … . nth term: aₙ = a × r^(n–1)." },
      { heading: "Sum of AP", content: "Sₙ = n/2 × [2a + (n–1)d] = n/2 × (first term + last term)." },
      { heading: "Sum of GP", content: "For r ≠ 1: Sₙ = a(1 – rⁿ)/(1 – r). For |r| < 1, infinite sum: S∞ = a/(1–r)." },
    ],
    keyFormulas: [
      { label: "AP nth term", formula: "aₙ = a + (n–1)d" },
      { label: "AP sum", formula: "Sₙ = n/2 [2a + (n–1)d]" },
      { label: "GP nth term", formula: "aₙ = ar^(n–1)" },
      { label: "GP sum", formula: "Sₙ = a(1 – rⁿ)/(1 – r)" },
      { label: "Infinite GP sum", formula: "S∞ = a/(1–r) for |r| < 1" },
    ],
    keyPoints: [
      "Arithmetic Mean between a and b: AM = (a+b)/2.",
      "Geometric Mean: GM = √(ab).",
      "For positive numbers: AM ≥ GM ≥ HM.",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "7th term of AP: 2, 5, 8, … is:", options: ["20", "23", "17", "26"], answer: 0 },
      { question: "Sum of first 10 terms of GP 1, 2, 4, … is:", options: ["1023", "1024", "511", "512"], answer: 0 },
      { question: "Infinite GP with a=3, r=1/2 has sum:", options: ["6", "3", "9", "4"], answer: 0 },
    ],
    prevChapterId: "chapter-08",
    nextChapterId: "chapter-10",
  },
  {
    chapterId: "chapter-10",
    order: 10,
    title: "Straight Lines",
    objective: "Study various forms of the equation of a line and their applications in coordinate geometry.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Slope of a Line", content: "Slope m = (y₂–y₁)/(x₂–x₁) = tan θ where θ is the angle with positive x-axis." },
      { heading: "Forms of Line Equations", content: "Slope-intercept: y = mx + c. Point-slope: y–y₁ = m(x–x₁). Two-point: (y–y₁)/(y₂–y₁) = (x–x₁)/(x₂–x₁). Intercept form: x/a + y/b = 1. Normal form: x cosα + y sinα = p." },
      { heading: "Distance from a Point to a Line", content: "Distance from point (x₁,y₁) to line ax+by+c=0 is |ax₁+by₁+c|/√(a²+b²)." },
    ],
    keyFormulas: [
      { label: "Slope m", formula: "(y₂–y₁)/(x₂–x₁)" },
      { label: "Distance between points", formula: "d = √((x₂–x₁)² + (y₂–y₁)²)" },
      { label: "Point-to-line distance", formula: "|ax₁+by₁+c| / √(a²+b²)" },
    ],
    keyPoints: [
      "Two lines are parallel if m₁ = m₂.",
      "Two lines are perpendicular if m₁ × m₂ = –1.",
      "The angle bisectors of two lines ax+by+c=0 and a'x+b'y+c'=0 can be found using the distance formula.",
    ],
    hasSimulation: true,
    simulationDescription: "Interactive coordinate plane to explore line equations and their properties.",
    sampleQuestions: [
      { question: "Slope of line joining (2,3) and (5,7) is:", options: ["4/3", "3/4", "1", "7/5"], answer: 0 },
      { question: "Equation of x-axis is:", options: ["x=0", "y=0", "x=1", "y=1"], answer: 1 },
      { question: "Distance from (1,2) to line 3x–4y+5=0 is:", options: ["0", "1", "2", "3"], answer: 0 },
    ],
    prevChapterId: "chapter-09",
    nextChapterId: "chapter-11",
  },
  {
    chapterId: "chapter-11",
    order: 11,
    title: "Conic Sections",
    objective: "Study circles, parabolas, ellipses, and hyperbolas — their equations and properties.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Circle", content: "Standard form: (x–h)² + (y–k)² = r² with center (h,k) and radius r. General form: x²+y²+2gx+2fy+c=0 with center (–g,–f) and radius √(g²+f²–c)." },
      { heading: "Parabola", content: "y² = 4ax (open right) with vertex at origin, focus at (a,0), directrix x=–a. Other forms: y²=–4ax, x²=4ay, x²=–4ay." },
      { heading: "Ellipse", content: "x²/a² + y²/b² = 1 (a>b). Foci at (±c,0) where c²=a²–b². Eccentricity e = c/a < 1." },
      { heading: "Hyperbola", content: "x²/a² – y²/b² = 1. Foci at (±c,0) where c²=a²+b². Eccentricity e = c/a > 1. Asymptotes: y = ±(b/a)x." },
    ],
    keyFormulas: [
      { label: "Circle standard", formula: "(x–h)² + (y–k)² = r²" },
      { label: "Parabola y²=4ax", formula: "Focus (a,0), Directrix x=–a, Latus rectum = 4a" },
      { label: "Ellipse eccentricity", formula: "e = c/a where c² = a²–b²" },
      { label: "Hyperbola eccentricity", formula: "e = c/a > 1 where c² = a²+b²" },
    ],
    keyPoints: [
      "Conic sections are obtained by slicing a cone at various angles.",
      "For a parabola, e=1; ellipse, e<1; hyperbola, e>1; circle, e=0.",
      "Length of latus rectum of ellipse = 2b²/a.",
    ],
    hasSimulation: true,
    simulationDescription: "Interactive conic sections visualizer — drag sliders to transform between circle, ellipse, parabola, and hyperbola.",
    sampleQuestions: [
      { question: "Focus of parabola y² = 8x is:", options: ["(2,0)", "(0,2)", "(4,0)", "(–2,0)"], answer: 0 },
      { question: "Eccentricity of a circle is:", options: ["0", "1", ">1", "<1"], answer: 0 },
      { question: "For ellipse x²/25 + y²/16 = 1, the value of c is:", options: ["3", "4", "5", "9"], answer: 0 },
    ],
    prevChapterId: "chapter-10",
    nextChapterId: "chapter-12",
  },
  {
    chapterId: "chapter-12",
    order: 12,
    title: "Introduction to Three Dimensional Geometry",
    objective: "Understand coordinates in 3D space, distance formula, section formula, and coordinates of a point.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "3D Coordinate System", content: "Three mutually perpendicular axes: X, Y, Z. A point P in space is represented as P(x, y, z). The three planes are XY, YZ, XZ planes." },
      { heading: "Distance Formula", content: "Distance between P(x₁,y₁,z₁) and Q(x₂,y₂,z₂) is √((x₂–x₁)²+(y₂–y₁)²+(z₂–z₁)²)." },
      { heading: "Section Formula", content: "Point dividing PQ in ratio m:n internally: ((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n), (mz₂+nz₁)/(m+n))." },
    ],
    keyFormulas: [
      { label: "3D Distance", formula: "d = √((x₂–x₁)² + (y₂–y₁)² + (z₂–z₁)²)" },
      { label: "Midpoint", formula: "M = ((x₁+x₂)/2, (y₁+y₂)/2, (z₁+z₂)/2)" },
      { label: "Section formula (internal)", formula: "((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n), (mz₂+nz₁)/(m+n))" },
    ],
    keyPoints: [
      "The origin O is at (0,0,0).",
      "Octants are the 8 regions formed by the three coordinate planes.",
      "The distance from origin to P(x,y,z) is √(x²+y²+z²).",
    ],
    hasSimulation: true,
    simulationDescription: "3D coordinate system visualizer — plot points and visualize distance in 3D space.",
    sampleQuestions: [
      { question: "Distance between (1,2,3) and (4,6,3) is:", options: ["5", "7", "√13", "√41"], answer: 0 },
      { question: "Midpoint of (2,4,6) and (4,8,10) is:", options: ["(3,6,8)", "(6,12,16)", "(1,2,3)", "(2,4,5)"], answer: 0 },
      { question: "A point on x-axis has coordinates:", options: ["(x,0,0)", "(0,y,0)", "(0,0,z)", "(x,y,0)"], answer: 0 },
    ],
    prevChapterId: "chapter-11",
    nextChapterId: "chapter-13",
  },
  {
    chapterId: "chapter-13",
    order: 13,
    title: "Limits and Derivatives",
    objective: "Understand the concept of limits, continuity, and derivatives with their properties.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Limits", content: "lim(x→a) f(x) = L means as x approaches a, f(x) approaches L. Left-hand limit (LHL) and right-hand limit (RHL) must be equal for the limit to exist." },
      { heading: "Standard Limits", content: "lim(x→0) sinx/x = 1; lim(x→0) (1+x)^(1/x) = e; lim(x→a) (xⁿ–aⁿ)/(x–a) = naⁿ⁻¹." },
      { heading: "Derivatives", content: "The derivative f'(x) = lim(h→0) [f(x+h)–f(x)]/h. Geometrically, it is the slope of the tangent to the curve at point (x, f(x))." },
      { heading: "Rules of Differentiation", content: "Sum: (f+g)' = f'+g'. Product: (fg)' = f'g + fg'. Quotient: (f/g)' = (f'g–fg')/g². Chain rule: d/dx f(g(x)) = f'(g(x))·g'(x)." },
    ],
    keyFormulas: [
      { label: "Derivative definition", formula: "f'(x) = lim(h→0) [f(x+h) – f(x)] / h" },
      { label: "d/dx (xⁿ)", formula: "n·xⁿ⁻¹" },
      { label: "d/dx (sinx)", formula: "cosx" },
      { label: "d/dx (cosx)", formula: "–sinx" },
      { label: "d/dx (eˣ)", formula: "eˣ" },
    ],
    keyPoints: [
      "Limit exists only when LHL = RHL.",
      "Derivative represents instantaneous rate of change.",
      "Differentiability implies continuity, but not vice versa.",
    ],
    hasSimulation: true,
    simulationDescription: "Tangent line visualizer — see the derivative as the slope of the tangent at any point on a curve.",
    sampleQuestions: [
      { question: "lim(x→0) sinx/x = ?", options: ["0", "1", "∞", "Undefined"], answer: 1 },
      { question: "d/dx (x³) = ?", options: ["3x²", "x²", "3x", "x³"], answer: 0 },
      { question: "d/dx (sin x) = ?", options: ["cos x", "–cos x", "sin x", "–sin x"], answer: 0 },
    ],
    prevChapterId: "chapter-12",
    nextChapterId: "chapter-14",
  },
  {
    chapterId: "chapter-14",
    order: 14,
    title: "Mathematical Reasoning",
    objective: "Understand mathematical statements, logical connectives, validity of arguments, and truth tables.",
    durationLabel: "2 days",
    theoryPoints: [
      { heading: "Statements", content: "A statement is a sentence that is either true or false, not both. Compound statements are formed using connectives." },
      { heading: "Logical Connectives", content: "AND (∧): Conjunction — both must be true. OR (∨): Disjunction — at least one must be true. NOT (¬): Negation. IF-THEN (→): Implication. IFF (↔): Biconditional." },
      { heading: "Contrapositive and Converse", content: "Contrapositive of 'If p then q' is 'If ¬q then ¬p'. Converse is 'If q then p'. An implication and its contrapositive are logically equivalent." },
    ],
    keyFormulas: [
      { label: "Truth of p → q", formula: "False only when p is True and q is False" },
      { label: "De Morgan's", formula: "¬(p ∧ q) ≡ ¬p ∨ ¬q; ¬(p ∨ q) ≡ ¬p ∧ ¬q" },
    ],
    keyPoints: [
      "A statement and its negation cannot both be true.",
      "Tautology: always true; Contradiction: always false.",
      "Contrapositive has the same truth value as the original implication.",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Negation of 'Today is Monday' is:", options: ["Today is Sunday", "Today is not Monday", "Yesterday was Monday", "Tomorrow is Tuesday"], answer: 1 },
      { question: "p → q is false when:", options: ["p=T, q=T", "p=F, q=T", "p=T, q=F", "p=F, q=F"], answer: 2 },
      { question: "Contrapositive of 'If it rains, the ground is wet' is:", options: ["If ground is wet, it rains", "If it doesn't rain, the ground is not wet", "If ground is not wet, it does not rain", "If it rains, the ground is not wet"], answer: 2 },
    ],
    prevChapterId: "chapter-13",
    nextChapterId: "chapter-15",
  },
  {
    chapterId: "chapter-15",
    order: 15,
    title: "Statistics",
    objective: "Calculate measures of central tendency and dispersion including mean, median, mode, variance, and standard deviation.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Mean", content: "Arithmetic mean = Σxᵢ/n for ungrouped data. For grouped data: x̄ = Σfᵢxᵢ / Σfᵢ." },
      { heading: "Median", content: "Middle value when data is arranged in order. For even n: Median = mean of (n/2)th and (n/2+1)th terms." },
      { heading: "Mode", content: "The value that appears most frequently in the data set." },
      { heading: "Variance and Standard Deviation", content: "Variance σ² = Σ(xᵢ – x̄)²/n. Standard deviation σ = √variance. For grouped data: σ² = Σfᵢ(xᵢ–x̄)²/Σfᵢ." },
    ],
    keyFormulas: [
      { label: "Mean (ungrouped)", formula: "x̄ = Σxᵢ / n" },
      { label: "Variance", formula: "σ² = Σ(xᵢ – x̄)² / n" },
      { label: "Std Deviation", formula: "σ = √(σ²)" },
      { label: "Coefficient of variation", formula: "CV = (σ/x̄) × 100%" },
    ],
    keyPoints: [
      "Standard deviation is always non-negative.",
      "A low CV indicates low variability relative to the mean.",
      "Mean is affected by extreme values; median is not.",
    ],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Mean of 2, 4, 6, 8, 10 is:", options: ["5", "6", "7", "8"], answer: 1 },
      { question: "Variance of 1, 2, 3, 4, 5 is:", options: ["2", "2.5", "3", "1.5"], answer: 0 },
      { question: "Mode of 3,3,5,7,3,7,7,3 is:", options: ["7", "3", "5", "4"], answer: 1 },
    ],
    prevChapterId: "chapter-14",
    nextChapterId: "chapter-16",
  },
  {
    chapterId: "chapter-16",
    order: 16,
    title: "Probability",
    objective: "Understand random experiments, sample space, events, and calculate probabilities using axiomatic approach.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Random Experiment", content: "An experiment whose outcome cannot be predicted with certainty. Example: tossing a coin, rolling a die." },
      { heading: "Sample Space", content: "The set of all possible outcomes of an experiment. Example: For a die, S = {1,2,3,4,5,6}." },
      { heading: "Events", content: "An event is a subset of the sample space. Simple event: single outcome. Compound event: multiple outcomes. Sure event: S itself. Impossible event: ∅." },
      { heading: "Probability", content: "P(E) = number of favorable outcomes / total outcomes (for equally likely outcomes). 0 ≤ P(E) ≤ 1." },
      { heading: "Axiomatic Approach", content: "P(E) ≥ 0 for all events E. P(S) = 1. P(E₁ ∪ E₂) = P(E₁) + P(E₂) for mutually exclusive E₁, E₂." },
    ],
    keyFormulas: [
      { label: "Classical probability", formula: "P(E) = n(E)/n(S)" },
      { label: "P(A ∪ B)", formula: "P(A) + P(B) – P(A ∩ B)" },
      { label: "P(Aᶜ)", formula: "1 – P(A)" },
      { label: "P(A ∩ B) for independent events", formula: "P(A) × P(B)" },
    ],
    keyPoints: [
      "Mutually exclusive events cannot occur simultaneously.",
      "Exhaustive events cover the entire sample space.",
      "Sum of probabilities of all simple events = 1.",
    ],
    hasSimulation: true,
    simulationDescription: "Coin toss and dice roll probability simulator — run experiments and compare theoretical vs empirical probability.",
    sampleQuestions: [
      { question: "Probability of getting a 6 on a fair die is:", options: ["1/3", "1/2", "1/6", "1/4"], answer: 2 },
      { question: "P(A) = 0.4, P(B) = 0.3, P(A∩B) = 0.1. Then P(A∪B) = ?", options: ["0.6", "0.7", "0.4", "0.5"], answer: 0 },
      { question: "P(Aᶜ) if P(A) = 0.35 is:", options: ["0.65", "0.45", "0.35", "0.55"], answer: 0 },
    ],
    prevChapterId: "chapter-15",
    nextChapterId: undefined,
  },
];
