/**
 * @file lib/content/class11-biology.ts
 * @description NCERT-aligned Class 11 Biology curriculum content
 * Covers all 22 chapters of NCERT Class 11 Biology (2025-26 edition)
 */

import type { ContentChapter } from "./class9-mathematics";

export const CLASS_11_BIOLOGY_CHAPTERS: ContentChapter[] = [
  {
    chapterId: "chapter-01", order: 1,
    title: "The Living World",
    objective: "Understand what defines life, biodiversity, taxonomy, and binomial nomenclature.",
    durationLabel: "2 days",
    theoryPoints: [
      { heading: "Characteristics of Living Things", content: "Growth, reproduction, metabolism, response to stimuli, cellular organization, homeostasis. Growth and reproduction are not exclusive to living organisms (crystals grow; fire reproduces) — consciousness is the definitive property." },
      { heading: "Biodiversity and Taxonomy", content: "~1.7 million species described. Taxonomy: science of classifying organisms. Species, Genus, Family, Order, Class, Phylum, Kingdom (Species to Kingdom — SFOCPK — or mnemonically: Kings Play Chess On Fine Glass Surfaces)." },
      { heading: "Binomial Nomenclature", content: "Carolus Linnaeus proposed binomial nomenclature. Scientific name: Genus + species (e.g., Homo sapiens). Written in italics; genus capitalized, species lowercase." },
    ],
    keyFormulas: [],
    keyPoints: ["Metabolic reactions are the sum of all chemical reactions in the body.", "Taxonomic hierarchy (ascending): Species → Genus → Family → Order → Class → Phylum → Kingdom → Domain.", "ICBN (plants) and ICZN (animals) govern nomenclature."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Correct scientific name for humans:", options: ["homo sapiens", "Homo Sapiens", "Homo sapiens", "HOMO SAPIENS"], answer: 2 },
      { question: "Father of Taxonomy:", options: ["Darwin", "Linnaeus", "Aristotle", "Lamarck"], answer: 1 },
      { question: "Highest taxon in hierarchy:", options: ["Kingdom", "Phylum", "Family", "Domain"], answer: 3 },
    ],
    prevChapterId: undefined, nextChapterId: "chapter-02",
  },
  {
    chapterId: "chapter-02", order: 2,
    title: "Biological Classification",
    objective: "Study the five-kingdom classification system and characteristics of each kingdom.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Five Kingdom Classification (Whittaker, 1969)", content: "Monera (prokaryotes: bacteria, cyanobacteria), Protista (unicellular eukaryotes: Amoeba, Paramecium, algae), Fungi, Plantae, Animalia." },
      { heading: "Kingdom Monera", content: "Bacteria: most abundant organisms. Shapes: coccus (spherical), bacillus (rod), vibrio (comma), spirillum (spiral). Autotrophic or heterotrophic. Archaebacteria (extreme environments), Eubacteria (true bacteria)." },
      { heading: "Kingdom Fungi", content: "Saprophytic (most), parasitic, mutualistic. Cell wall of chitin. Hyphae form mycelium. Asexual: conidia or sporangiospores. Examples: Mucor, Aspergillus, Penicillium, Agaricus (mushroom)." },
      { heading: "Viruses, Viroids, and Lichens", content: "Viruses: non-cellular, protein + nucleic acid (DNA or RNA). Viroids: smallest infectious agents (naked RNA, no protein coat). Lichens: symbiosis of fungi (mycobiont) + algae (phycobiont)." },
    ],
    keyFormulas: [],
    keyPoints: ["Mycorrhiza: symbiotic association of fungi with plant roots — improves water/mineral absorption.", "Lichens are pioneer species — appear first in bare habitats.", "Viruses cause: Tobacco Mosaic Virus (TMV), AIDS (HIV), Influenza, Polio."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Cell wall of fungi is made of:", options: ["Cellulose", "Chitin", "Peptidoglycan", "Lignin"], answer: 1 },
      { question: "Lichens are association of:", options: ["Algae + Bacteria", "Fungi + Algae", "Fungi + Bacteria", "Algae + Algae"], answer: 1 },
      { question: "Which kingdom contains photosynthetic, unicellular eukaryotes?", options: ["Monera", "Protista", "Fungi", "Plantae"], answer: 1 },
    ],
    prevChapterId: "chapter-01", nextChapterId: "chapter-03",
  },
  {
    chapterId: "chapter-03", order: 3,
    title: "Plant Kingdom",
    objective: "Classify plants into major divisions and understand their key characteristics and life cycles.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Algae", content: "Chlorophyta (green algae: Chlamydomonas, Volvox, Ulva), Phaeophyta (brown: Ectocarpus, Fucus), Rhodophyta (red: Polysiphonia). Thallus body, photosynthetic. Reserve food: starch (green), mannitol/laminarin (brown), floridean starch (red)." },
      { heading: "Bryophyta", content: "Amphibians of plant kingdom (need water for reproduction). No vascular tissue. Alternation of generations: gametophyte (dominant, n) → sporophyte (2n, dependent on gametophyte). Examples: Riccia (liverwort), Funaria (moss)." },
      { heading: "Pteridophyta", content: "First vascular plants. Sporophyte dominant. Examples: Ferns (Dryopteris), Horsetails (Equisetum), Clubmosses (Selaginella). Sporangia on sporophyll." },
      { heading: "Gymnosperms and Angiosperms", content: "Gymnosperms: naked seeds, no fruits (Pinus, Cycas). Angiosperms: seeds enclosed in fruit; divided into monocots and dicots. Flowering plants — most diverse and advanced." },
    ],
    keyFormulas: [],
    keyPoints: ["In angiosperms, sporophyte is dominant; gametophyte is reduced to a few cells.", "Dicots: two cotyledons, net-venation, tap root; Monocots: one cotyledon, parallel venation, fibrous root.", "Double fertilization occurs only in angiosperms."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which group has naked seeds?", options: ["Bryophyta", "Pteridophyta", "Gymnosperms", "Angiosperms"], answer: 2 },
      { question: "Alternation of generations: gametophyte is dominant in:", options: ["Pteridophyta", "Bryophyta", "Gymnosperms", "Angiosperms"], answer: 1 },
      { question: "Which algae produces alginic acid?", options: ["Green", "Brown", "Red", "Blue-green"], answer: 1 },
    ],
    prevChapterId: "chapter-02", nextChapterId: "chapter-04",
  },
  {
    chapterId: "chapter-04", order: 4,
    title: "Animal Kingdom",
    objective: "Classify animals from Porifera to Chordata based on key characteristics.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Non-chordates", content: "Porifera: pore-bearing, Canal system, spicules (sponges). Coelenterata: radial symmetry, cnidoblasts (Hydra, Obelia, jellyfish). Platyhelminthes: flat worms, acoelomate (Planaria, Taenia). Nematoda: roundworms (Ascaris). Annelida: segmented worms (Earthworm, Leech). Arthropoda: exoskeleton, jointed legs (Insects, Crabs) — largest phylum. Mollusca: soft body, mantle (Pila, Octopus). Echinodermata: water vascular system, radial symmetry (Starfish, Sea urchin)." },
      { heading: "Chordates", content: "Characteristics: notochord, dorsal hollow nerve cord, pharyngeal gill slits, post-anal tail. Subphyla: Urochordata (Herdmania), Cephalochordata (Amphioxus), Vertebrata (fishes to mammals)." },
      { heading: "Vertebrates", content: "Pisces (fish): cold-blooded, scales, gills. Amphibia: cold-blooded, moist skin, larval aquatic (frog, toad). Reptilia: cold-blooded, dry scales (lizard, crocodile). Aves: warm-blooded, feathers, flight (birds). Mammalia: warm-blooded, hair, mammary glands." },
    ],
    keyFormulas: [],
    keyPoints: ["Arthropoda is the largest animal phylum (~75% of all animal species).", "Homeothermy (warm-blooded): birds and mammals maintain constant body temperature.", "Pisces includes Chondrichthyes (cartilaginous: sharks) and Osteichthyes (bony: Rohu)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Largest animal phylum:", options: ["Chordata", "Mollusca", "Arthropoda", "Annelida"], answer: 2 },
      { question: "Canal system is found in:", options: ["Coelenterata", "Porifera", "Platyhelminthes", "Echinodermata"], answer: 1 },
      { question: "First warm-blooded animal class:", options: ["Reptilia", "Amphibia", "Aves", "Pisces"], answer: 2 },
    ],
    prevChapterId: "chapter-03", nextChapterId: "chapter-05",
  },
  {
    chapterId: "chapter-05", order: 5,
    title: "Morphology of Flowering Plants",
    objective: "Study external structure of roots, stems, leaves, flowers, fruits, and seeds.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Root", content: "Tap root system (dicots) or fibrous root system (monocots). Regions: root cap, meristematic zone, elongation zone, maturation zone (root hairs). Modifications: storage (carrot), support (prop roots in Maize)." },
      { heading: "Stem", content: "Aerial or underground (rhizome, tuber, corm, bulb). Nodes and internodes. Herbaceous or woody. Modifications: tendrils (Cucumber), thorns (Bougainvillea), phylloclade (Opuntia)." },
      { heading: "Leaf", content: "Parts: leaf base, petiole, lamina. Venation: reticulate (dicots) or parallel (monocots). Leaf modifications: tendrils (Lathyrus), spines (cactus), pitcher (Nepenthes). Phyllotaxy: alternate, opposite, whorled." },
      { heading: "Flower", content: "Parts: calyx (sepals), corolla (petals), androecium (stamens), gynoecium (pistil). Complete/incomplete; bisexual/unisexual. Floral formula represents flower structure symbolically." },
    ],
    keyFormulas: [],
    keyPoints: ["Epigeal germination: cotyledons appear above soil (Bean). Hypogeal: remain below (Gram).", "Superior ovary: hypogynous flower (most). Inferior: epigynous.", "Inflorescence: arrangement of flowers on floral axis (raceme, spike, corymb, umbel, head)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which root modification stores food?", options: ["Prop root", "Stilt root", "Tap root of carrot", "Pneumatophore"], answer: 2 },
      { question: "Parallel venation is found in:", options: ["Dicot leaves", "Monocot leaves", "Ferns", "Mosses"], answer: 1 },
      { question: "Which part of flower forms fruit?", options: ["Calyx", "Corolla", "Androecium", "Gynoecium (ovary)"], answer: 3 },
    ],
    prevChapterId: "chapter-04", nextChapterId: "chapter-06",
  },
  {
    chapterId: "chapter-06", order: 6,
    title: "Anatomy of Flowering Plants",
    objective: "Study internal structure of tissues, tissue systems, and stem/root/leaf anatomy.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Meristematic Tissue", content: "Apical meristem: at shoot/root tips, causes elongation. Lateral meristem (cambium): causes secondary growth in dicots. Intercalary: at base of leaves or internodes (monocots)." },
      { heading: "Permanent Tissues", content: "Simple: Parenchyma (storage, photosynthesis), Collenchyma (flexibility), Sclerenchyma (support, dead at maturity). Complex: Xylem (water transport, dead cells: tracheids, vessels), Phloem (food transport, living: sieve tubes, companion cells)." },
      { heading: "Tissue Systems", content: "Epidermal (outermost, protection), Ground (parenchyma/collenchyma/sclerenchyma), Vascular (xylem+phloem+cambium)." },
      { heading: "Dicot vs Monocot Anatomy", content: "Dicot stem: ring of vascular bundles, open (cambium present), pith in centre. Monocot stem: scattered vascular bundles, closed (no cambium). Dicot root: radial vascular bundles, exarch xylem, pith absent. Monocot root: more numerous vascular bundles, pith present." },
    ],
    keyFormulas: [],
    keyPoints: ["Xylem transports water upward (transpiration pull). Phloem transports both upward and downward (bidirectional).", "Wood = secondary xylem formed by vascular cambium.", "Casparian strip in root endodermis: prevents apoplastic entry of water."],
    hasSimulation: true,
    simulationDescription: "Plant tissue cross-section viewer — explore dicot and monocot stem, root, and leaf anatomy.",
    sampleQuestions: [
      { question: "Which tissue provides flexibility to young stems?", options: ["Parenchyma", "Collenchyma", "Sclerenchyma", "Xylem"], answer: 1 },
      { question: "Vascular bundles in monocot stem are:", options: ["In a ring", "Scattered", "In pairs", "Absent"], answer: 1 },
      { question: "Sieve tube elements are found in:", options: ["Xylem", "Phloem", "Parenchyma", "Collenchyma"], answer: 1 },
    ],
    prevChapterId: "chapter-05", nextChapterId: "chapter-07",
  },
  {
    chapterId: "chapter-07", order: 7,
    title: "Structural Organisation in Animals",
    objective: "Study animal tissues, organ systems, and morphology of earthworm, cockroach, and frog.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Animal Tissues", content: "Epithelial: covering surfaces (squamous, cuboidal, columnar, ciliated). Connective: support and binding (loose, dense, specialized: cartilage, bone, blood). Muscular: striated (voluntary), smooth (involuntary), cardiac. Nervous: neurons (sensory, motor, interneurons)." },
      { heading: "Earthworm (Pheretima posthuma)", content: "Body segments (metameres). Closed circulatory system. Hermaphrodite. Excretion by nephridia. Digestion in alimentary canal (gizzard grinds food)." },
      { heading: "Cockroach (Periplaneta americana)", content: "Arthropod, 6 legs, 2 pairs wings, compound eyes. Open circulatory system (haemolymph). Malpighian tubules for excretion. Tracheal system for respiration." },
      { heading: "Frog (Rana tigrina)", content: "Amphibian. Cutaneous and pulmonary respiration. Three-chambered heart (2 atria + 1 ventricle). Ectothermic. External fertilization." },
    ],
    keyFormulas: [],
    keyPoints: ["Blood is a connective tissue (cells in plasma, the intercellular matrix).", "Cartilage: matrix is chondrin (protein+carbohydrate); Bone: matrix is calcified.", "Earthworm has 100-120 segments; typhlosole increases absorption area in intestine."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which tissue is involuntary and spindle-shaped?", options: ["Striated muscle", "Smooth muscle", "Cardiac muscle", "Epithelium"], answer: 1 },
      { question: "Excretory organs of cockroach:", options: ["Nephridia", "Malpighian tubules", "Green glands", "Flame cells"], answer: 1 },
      { question: "Earthworm's circulatory system is:", options: ["Open", "Closed", "Absent", "Mixed"], answer: 1 },
    ],
    prevChapterId: "chapter-06", nextChapterId: "chapter-08",
  },
  {
    chapterId: "chapter-08", order: 8,
    title: "Cell: The Unit of Life",
    objective: "Study cell theory, prokaryotic vs eukaryotic cells, and organelle structure and function.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Cell Theory", content: "Cell is the structural and functional unit of life (Schleiden and Schwann, 1839). Virchow: new cells arise from pre-existing cells. All cells have genetic material." },
      { heading: "Prokaryotic vs Eukaryotic", content: "Prokaryotic: no membrane-bound nucleus, no organelles, 70S ribosomes, circular DNA, cell wall (peptidoglycan in bacteria). Eukaryotic: membrane-bound nucleus, 80S ribosomes (60S+40S), linear DNA, various organelles." },
      { heading: "Cell Organelles", content: "Mitochondria: powerhouse of cell, double membrane, cristae (inner folds), ATP synthesis. Chloroplast: double membrane, thylakoids (grana) for light reactions, stroma for dark reactions. Endoplasmic Reticulum: rough (ribosomes) for protein synthesis; smooth for lipid synthesis. Golgi: packaging and export. Lysosomes: suicide bags (hydrolytic enzymes). Vacuoles: plant cell (large central vacuole, osmosis)." },
    ],
    keyFormulas: [],
    keyPoints: ["Mitochondria and chloroplasts have their own DNA and 70S ribosomes — support endosymbiotic theory.", "Nucleus: nuclear envelope (double membrane with pores), nucleolus (rRNA synthesis), chromatin.", "Centrioles: absent in plant cells and higher fungi; present in animal cells — form spindle during cell division."],
    hasSimulation: true,
    simulationDescription: "Interactive cell organelle explorer — click on any organelle to see structure, function, and location in 3D.",
    sampleQuestions: [
      { question: "Powerhouse of cell:", options: ["Nucleus", "Mitochondria", "Chloroplast", "Ribosome"], answer: 1 },
      { question: "Which organelle is involved in lipid synthesis?", options: ["Rough ER", "Smooth ER", "Golgi", "Ribosome"], answer: 1 },
      { question: "Ribosomes in prokaryotes are:", options: ["80S", "70S", "60S", "40S"], answer: 1 },
    ],
    prevChapterId: "chapter-07", nextChapterId: "chapter-09",
  },
  {
    chapterId: "chapter-09", order: 9,
    title: "Biomolecules",
    objective: "Study chemical composition of cells — carbohydrates, proteins, lipids, nucleic acids, and enzymes.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Carbohydrates", content: "Monosaccharides (glucose, fructose), Disaccharides (sucrose, lactose), Polysaccharides (starch, cellulose, glycogen, chitin). Energy source and structural role." },
      { heading: "Proteins", content: "Polymers of amino acids (20 types). Peptide bond: –CO–NH–. Primary, secondary (α-helix, β-sheet), tertiary, quaternary structures. Functions: enzymes, hormones, antibodies, structural (keratin, collagen)." },
      { heading: "Lipids", content: "Fats (triglycerides: glycerol + 3 fatty acids), Phospholipids (cell membrane), Steroids (cholesterol, hormones), Waxes. Energy storage, membrane structure, hormones." },
      { heading: "Enzymes", content: "Biological catalysts (proteins, except ribozymes which are RNA). Enzyme-Substrate complex (lock-and-key or induced fit). Factors affecting activity: temperature, pH, substrate concentration. Inhibition: competitive, non-competitive." },
    ],
    keyFormulas: [
      { label: "Michaelis-Menten equation", formula: "v = Vmax[S]/(Km + [S])" },
    ],
    keyPoints: ["Km is the substrate concentration at half-maximal velocity — measures enzyme affinity.", "Prosthetic group (tightly bound cofactor) + apoenzyme = holoenzyme.", "Isoenzymes: different molecular forms of same enzyme (e.g., LDH has 5 isoenzymes)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Peptide bond is formed by:", options: ["Dehydration synthesis", "Hydrolysis", "Phosphorylation", "Methylation"], answer: 0 },
      { question: "Which polysaccharide is found in exoskeleton of insects?", options: ["Starch", "Cellulose", "Glycogen", "Chitin"], answer: 3 },
      { question: "Enzyme that is made of RNA is called:", options: ["Cofactor", "Coenzyme", "Ribozyme", "Apoenzyme"], answer: 2 },
    ],
    prevChapterId: "chapter-08", nextChapterId: "chapter-10",
  },
  {
    chapterId: "chapter-10", order: 10,
    title: "Cell Cycle and Cell Division",
    objective: "Study mitosis, meiosis, cell cycle phases, and significance of cell division.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Cell Cycle", content: "Interphase: G1 (growth, protein synthesis), S (DNA replication), G2 (preparation for division). M phase: mitosis. G0: quiescent phase (non-dividing cells)." },
      { heading: "Mitosis", content: "Equational division — produces 2 genetically identical daughter cells. Phases: Prophase (chromatin condenses), Metaphase (chromosomes at equatorial plate), Anaphase (chromatids separate), Telophase (nuclear envelope reforms) + Cytokinesis." },
      { heading: "Meiosis", content: "Reductional division — produces 4 genetically different cells (gametes). Two divisions: Meiosis I (homologous chromosomes separate) and Meiosis II (sister chromatids separate). Results in haploid cells (n)." },
      { heading: "Significance", content: "Mitosis: growth, repair, asexual reproduction. Meiosis: sexual reproduction, genetic variation (crossing over in prophase I)." },
    ],
    keyFormulas: [],
    keyPoints: ["Crossing over (recombination) occurs at chiasmata during pachytene of prophase I.", "Mitosis takes ~1 hour; S phase takes ~8 hours in typical human cells.", "Karyokinesis: nuclear division; Cytokinesis: cytoplasmic division."],
    hasSimulation: true,
    simulationDescription: "Mitosis and meiosis cell division animator — watch chromosome movements through all phases in real time.",
    sampleQuestions: [
      { question: "During which phase does DNA replication occur?", options: ["G1", "S phase", "G2", "M phase"], answer: 1 },
      { question: "Meiosis produces how many cells from one parent cell?", options: ["2", "4", "1", "8"], answer: 1 },
      { question: "Crossing over occurs during:", options: ["G2 phase", "Prophase I", "Metaphase I", "Anaphase II"], answer: 1 },
    ],
    prevChapterId: "chapter-09", nextChapterId: "chapter-11",
  },
  {
    chapterId: "chapter-11", order: 11,
    title: "Transport in Plants",
    objective: "Study osmosis, water potential, absorption, transpiration, and transport of minerals and food.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Water Potential and Osmosis", content: "Water potential (ψ) = solute potential (ψs) + pressure potential (ψp). Water moves from high to low water potential. Osmosis: water diffusion through semipermeable membrane." },
      { heading: "Absorption and Ascent of Sap", content: "Water enters by osmosis through root hairs. Apoplast pathway (through cell walls) and symplast pathway (through cytoplasm/plasmodesmata). Ascent of sap: transpiration pull (cohesion-tension theory), root pressure." },
      { heading: "Transpiration", content: "Stomatal transpiration (90-95%). Stomata open in light (K⁺ enters guard cells → ψ decreases → water enters → turgid → open). Factors: light, temperature, humidity, wind, CO₂ concentration." },
      { heading: "Phloem Transport", content: "Translocation of sugars from source (leaves) to sink (roots, fruits). Pressure flow hypothesis (Munch). Active loading of sucrose into phloem sieve tubes." },
    ],
    keyFormulas: [
      { label: "Water potential equation", formula: "ψ = ψs + ψp (ψs is always negative; ψp can be positive or zero)" },
      { label: "Osmotic potential", formula: "ψs = –iCRT" },
    ],
    keyPoints: ["A turgid plant cell has a positive pressure potential (ψp). A fully turgid cell: ψ = 0.", "Plasmolysis: water leaves cell, protoplast shrinks away from cell wall (in concentrated solution).", "Bulk flow in phloem is from source (high P) to sink (low P)."],
    hasSimulation: true,
    simulationDescription: "Osmosis simulation — watch water movement across semipermeable membrane based on concentration gradients.",
    sampleQuestions: [
      { question: "Transpiration pull is explained by:", options: ["Root pressure theory", "Cohesion-tension theory", "Atmospheric pressure theory", "Capillarity"], answer: 1 },
      { question: "Source in phloem transport is:", options: ["Roots", "Fruits", "Seeds", "Leaves"], answer: 3 },
      { question: "Guard cells in stomata open due to:", options: ["K⁺ loss", "K⁺ gain and water entry", "Decreased turgor", "CO₂ increase"], answer: 1 },
    ],
    prevChapterId: "chapter-10", nextChapterId: "chapter-12",
  },
  {
    chapterId: "chapter-12", order: 12,
    title: "Mineral Nutrition",
    objective: "Study essential elements, macronutrients, micronutrients, deficiency symptoms, and nitrogen fixation.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Essential Elements", content: "17 essential elements: C, H, O, N, P, K, Ca, Mg, S (macronutrients — >10 mmol/kg dry weight) + Fe, Mn, Cu, Zn, Mo, B, Cl, Ni (micronutrients — <10 mmol/kg)." },
      { heading: "Deficiency Symptoms", content: "N: chlorosis (yellowing), stunted growth. P: dark green/purple color (anthocyanin accumulation). K: premature death of leaf tips. Mg: chlorosis between veins. Fe: interveinal chlorosis (young leaves affected first)." },
      { heading: "Nitrogen Fixation", content: "Symbiotic: Rhizobium (legumes), Frankia (Alnus), Anabaena (Azolla). Free-living: Azotobacter, Clostridium. Nitrogenase enzyme: N₂ + 8H⁺ + 8e⁻ → 2NH₃ + H₂ (requires ATP and is O₂-sensitive)." },
    ],
    keyFormulas: [],
    keyPoints: ["Leghemoglobin in root nodules protects nitrogenase from O₂.", "Nitrogen cycle: N₂ → NH₃ (fixation) → NO₂⁻/NO₃⁻ (nitrification) → organic N → NH₃ (ammonification) → N₂ (denitrification).", "Hydroponics: growing plants in mineral solutions without soil."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which micronutrient is component of nitrogenase?", options: ["Fe and S", "Mo and Fe", "Cu and Zn", "Mn and B"], answer: 1 },
      { question: "Rhizobium fixes nitrogen in:", options: ["Free living state", "Root nodules of legumes", "Leaf cells", "Water"], answer: 1 },
      { question: "Yellowing of leaves (chlorosis) is due to deficiency of:", options: ["Phosphorus", "Nitrogen", "Potassium", "Calcium"], answer: 1 },
    ],
    prevChapterId: "chapter-11", nextChapterId: "chapter-13",
  },
  {
    chapterId: "chapter-13", order: 13,
    title: "Photosynthesis in Higher Plants",
    objective: "Study light reactions, Calvin cycle, photorespiration, and C4 and CAM pathways.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Light Reactions (Thylakoid Membrane)", content: "PS-II (P680): water splitting (O₂ released), plastoquinone carries e⁻. Cytochrome b₆f complex. PS-I (P700): NADP⁺ + 2e⁻ + H⁺ → NADPH. Photophosphorylation: ATP synthesis by CF₀-CF₁ ATPase. Z-scheme: cyclic and non-cyclic photophosphorylation." },
      { heading: "Calvin Cycle (Dark Reactions, Stroma)", content: "CO₂ + RuBP (5C) → 2 PGA (3C) [RuBisCo enzyme]. PGA → G3P (using ATP and NADPH). Some G3P → glucose; some → RuBP regeneration. 3CO₂ → 1 G3P needs 9ATP + 6NADPH." },
      { heading: "C4 Pathway (Hatch-Slack)", content: "CO₂ first fixed by PEP (phosphoenolpyruvate) in mesophyll cells → OAA (4C) → transported to bundle sheath → CO₂ released → Calvin cycle. Plants: Maize, Sugarcane. Advantage: no photorespiration." },
      { heading: "Photorespiration", content: "RuBisCo acts as oxygenase (in C3 plants at high O₂/CO₂ ratio) → glycolate formed → oxidized → CO₂ released. Wastes energy; absent in C4 plants (special anatomy)." },
    ],
    keyFormulas: [
      { label: "Overall photosynthesis equation", formula: "6CO₂ + 12H₂O → C₆H₁₂O₆ + 6O₂ + 6H₂O" },
      { label: "ATP yield per glucose", formula: "~38 ATP (theoretical)" },
    ],
    keyPoints: ["Emerson Effect: enhanced photosynthesis when two wavelengths used together (red + far-red).", "Oxygenation by RuBisCo and subsequent glycolate metabolism = photorespiration.", "CAM plants (Crassulacean Acid Metabolism): stomata open at night, fix CO₂ as malic acid — succulent desert plants."],
    hasSimulation: true,
    simulationDescription: "Photosynthesis light and dark reaction simulator — see electron flow, ATP synthesis, and Calvin cycle in real time.",
    sampleQuestions: [
      { question: "O₂ released in photosynthesis comes from:", options: ["CO₂", "H₂O", "Glucose", "RuBP"], answer: 1 },
      { question: "First stable product of C3 pathway:", options: ["RuBP", "PGA", "OAA", "G3P"], answer: 1 },
      { question: "Photorespiration is absent in:", options: ["C3 plants", "C4 plants", "CAM plants", "Both B and C"], answer: 3 },
    ],
    prevChapterId: "chapter-12", nextChapterId: "chapter-14",
  },
  {
    chapterId: "chapter-14", order: 14,
    title: "Respiration in Plants",
    objective: "Study glycolysis, Krebs cycle, electron transport chain, fermentation, and energy yield.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Glycolysis (Cytoplasm)", content: "Glucose (6C) → 2 Pyruvate (3C). Net gain: 2 ATP (substrate-level) + 2 NADH. Does not require oxygen — aerobic and anaerobic." },
      { heading: "Krebs Cycle (Mitochondrial Matrix)", content: "Pyruvate → Acetyl-CoA (by PDC) → combines with OAA (4C) → Citrate (6C). Per Acetyl-CoA: 3 NADH + 1 FADH₂ + 1 GTP. Per glucose: 6 NADH + 2 FADH₂ + 2 GTP." },
      { heading: "Electron Transport Chain (Inner Mitochondrial Membrane)", content: "NADH and FADH₂ donate electrons to ETC → O₂ is final electron acceptor → H₂O formed. Proton gradient drives ATP synthase (chemiosmosis). Per NADH: ~2.5 ATP; per FADH₂: ~1.5 ATP." },
      { heading: "Fermentation", content: "Anaerobic breakdown of glucose. Yeast: Pyruvate → Ethanol + CO₂ (by pyruvate decarboxylase). Muscle: Pyruvate → Lactate (by lactate dehydrogenase). Net: 2 ATP only." },
    ],
    keyFormulas: [
      { label: "Overall aerobic respiration", formula: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ~36-38 ATP" },
      { label: "RQ for carbohydrate", formula: "RQ = CO₂ evolved/O₂ consumed = 1.0" },
    ],
    keyPoints: ["RQ > 1 for fat (needs more O₂); RQ < 1 for proteins.", "Respiratory quotient (RQ) helps identify respiratory substrate.", "Glycolysis occurs in cytoplasm; Krebs cycle and ETC in mitochondria."],
    hasSimulation: true,
    simulationDescription: "Cellular respiration energy flow — track ATP production through glycolysis, Krebs cycle, and ETC.",
    sampleQuestions: [
      { question: "Net ATP from glycolysis per glucose:", options: ["4 ATP", "2 ATP", "36 ATP", "38 ATP"], answer: 1 },
      { question: "Final electron acceptor in aerobic respiration:", options: ["NAD⁺", "FAD", "O₂", "CO₂"], answer: 2 },
      { question: "Fermentation in yeast produces:", options: ["Lactic acid + CO₂", "Ethanol + CO₂", "Acetyl-CoA + H₂O", "Pyruvate + ATP"], answer: 1 },
    ],
    prevChapterId: "chapter-13", nextChapterId: "chapter-15",
  },
  {
    chapterId: "chapter-15", order: 15,
    title: "Plant Growth and Development",
    objective: "Study plant growth regulators (phytohormones) — auxins, gibberellins, cytokinins, ABA, and ethylene.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Plant Growth", content: "Meristematic phase (rapid cell division), elongation phase, maturation phase. Sigmoid growth curve: lag, log, stationary phases. Arithmetic growth vs geometric (exponential) growth." },
      { heading: "Phytohormones", content: "Auxins (IAA): promote cell elongation, apical dominance, root initiation, tropisms. Gibberellins: stem elongation, seed germination, bolting. Cytokinins: cell division, delay senescence. ABA (Abscisic acid): stress hormone — wilting, stomatal closure, seed dormancy. Ethylene: gaseous, ripening, senescence, epinasty." },
      { heading: "Photoperiodism and Vernalization", content: "Photoperiodism: plant's response to light duration. Short-day plants (SDPs): flower when night > critical period. Long-day plants (LDPs): flower when night < critical period. Vernalization: cold treatment needed for flowering in some plants." },
    ],
    keyFormulas: [],
    keyPoints: ["Florigen (flowering hormone) is produced in leaves and transported to shoot apex.", "Phytochrome (Pr/Pfr system): light receptor that controls photoperiodism.", "Ethylene (ripening agent): used commercially to ripen fruits; also produced in response to stress."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which hormone promotes stomatal closure under water stress?", options: ["Auxin", "Gibberellin", "Cytokinin", "Abscisic acid (ABA)"], answer: 3 },
      { question: "Auxin promotes growth at:", options: ["Shoot apex only", "Root apex only", "Both apices equally", "Shoot apex more than root"], answer: 3 },
      { question: "Ethylene is a:", options: ["Solid hormone", "Liquid hormone", "Gaseous hormone", "Protein hormone"], answer: 2 },
    ],
    prevChapterId: "chapter-14", nextChapterId: "chapter-16",
  },
  {
    chapterId: "chapter-16", order: 16,
    title: "Digestion and Absorption",
    objective: "Study the human digestive system, enzymatic digestion, and absorption of nutrients.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Alimentary Canal", content: "Mouth → Pharynx → Oesophagus → Stomach → Small intestine (duodenum, jejunum, ileum) → Large intestine → Rectum → Anus. Accessory glands: salivary glands, liver (bile), pancreas." },
      { heading: "Digestion", content: "Mouth: salivary amylase (starch → maltose). Stomach: pepsin (protein → peptones), HCl (pH 2, kills bacteria). Small intestine: pancreatic enzymes (trypsin, lipase, amylase), brush border enzymes (maltase, sucrase, lactase). Bile (liver): emulsification of fats." },
      { heading: "Absorption", content: "Small intestine: villi and microvilli (brush border) increase surface area. Glucose and amino acids: active transport. Fatty acids and glycerol: form chylomicrons → lymph (lacteals)." },
    ],
    keyFormulas: [],
    keyPoints: ["Vitamin B₁₂ and folic acid: absorbed in ileum with intrinsic factor.", "Liver: largest gland, produces bile, stores glycogen, detoxifies.", "Ruminants: cellulose digestion by bacteria in rumen."],
    hasSimulation: true,
    simulationDescription: "Digestive system simulator — trace food through the human gut with enzyme activity at each stage.",
    sampleQuestions: [
      { question: "Enzyme that digests starch in the mouth:", options: ["Pepsin", "Trypsin", "Salivary amylase", "Lipase"], answer: 2 },
      { question: "Bile is produced by:", options: ["Pancreas", "Gall bladder", "Liver", "Stomach"], answer: 2 },
      { question: "Absorption of fatty acids and glycerol occurs into:", options: ["Blood capillaries directly", "Lacteals (lymph)", "Portal vein", "Hepatic artery"], answer: 1 },
    ],
    prevChapterId: "chapter-15", nextChapterId: "chapter-17",
  },
  {
    chapterId: "chapter-17", order: 17,
    title: "Breathing and Exchange of Gases",
    objective: "Study respiratory organs, mechanism of breathing, gas exchange, and transport of gases.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Human Respiratory System", content: "Nose → Pharynx → Larynx → Trachea → Bronchi → Bronchioles → Alveoli. Alveoli: site of gas exchange. Total lung capacity: ~6L; tidal volume: ~0.5L." },
      { heading: "Mechanism of Breathing", content: "Inspiration: diaphragm + intercostals contract → volume increases → pressure decreases → air in. Expiration: muscles relax → volume decreases → pressure increases → air out." },
      { heading: "Transport of Gases", content: "O₂: 97% as oxyhaemoglobin (HbO₂); 3% dissolved in plasma. CO₂: 70% as bicarbonate (HCO₃⁻), 23% as carbamino-haemoglobin, 7% dissolved. Chloride shift maintains ionic balance." },
      { heading: "Disorders", content: "Asthma: inflammation/narrowing of bronchi. Emphysema: alveolar wall damage, reduced surface area. Occupational respiratory diseases: silicosis, asbestosis, anthracosis (coal miners)." },
    ],
    keyFormulas: [
      { label: "pO₂ in alveoli", formula: "~104 mmHg; in tissues ~40 mmHg → O₂ diffuses to tissues" },
      { label: "pCO₂ in tissues", formula: "~45 mmHg; in alveoli ~40 mmHg → CO₂ diffuses to alveoli" },
    ],
    keyPoints: ["Bohr effect: decreased pH (more CO₂) decreases Hb affinity for O₂ — releases O₂ to active tissues.", "Total lung capacity = Tidal volume + ERV + IRV + RV = ~6L.", "Respiratory centre: medulla oblongata (rhythm); pneumotaxic centre: pons."],
    hasSimulation: true,
    simulationDescription: "Lung breathing mechanism — see diaphragm movement, volume/pressure changes during inspiration and expiration.",
    sampleQuestions: [
      { question: "Site of gas exchange in lungs:", options: ["Bronchi", "Trachea", "Alveoli", "Bronchioles"], answer: 2 },
      { question: "Maximum CO₂ is transported as:", options: ["CO₂ dissolved", "Carbamino-Hb", "HCO₃⁻ (bicarbonate)", "HbCO₂"], answer: 2 },
      { question: "During inspiration, diaphragm:", options: ["Relaxes and rises", "Contracts and flattens", "Does not move", "Pushes upward"], answer: 1 },
    ],
    prevChapterId: "chapter-16", nextChapterId: "chapter-18",
  },
  {
    chapterId: "chapter-18", order: 18,
    title: "Body Fluids and Circulation",
    objective: "Study blood composition, cardiac cycle, ECG, blood pressure, and lymph circulation.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Blood Composition", content: "Plasma (55%): water, proteins (albumin, globulin, fibrinogen), nutrients, hormones. Formed elements: RBC (7μm, biconcave, no nucleus, ~5 million/mm³), WBC (nucleated, 7000/mm³, immune defense), Platelets (2-3μm, 1.5-3.5 lakh/mm³, clotting)." },
      { heading: "Cardiac Cycle", content: "Systole: ventricles contract (120 mmHg). Diastole: ventricles relax (80 mmHg). Normal BP: 120/80 mmHg. Cardiac output: ~5 L/min (70 mL × 72 beats/min). Intrinsic rhythm: SA node (72 bpm) → AV node → Bundle of His → Purkinje fibres." },
      { heading: "Blood Groups", content: "ABO system: A (antigen A, antibody b), B (antigen B, antibody a), AB (both antigens, no antibodies — universal recipient), O (no antigens, both antibodies — universal donor). Rh factor: Rh+ve or Rh–ve." },
      { heading: "Disorders", content: "Hypertension (>120/80), Coronary Artery Disease (atherosclerosis), Angina pectoris, Heart failure." },
    ],
    keyFormulas: [
      { label: "Cardiac output", formula: "CO = Stroke volume × Heart rate = ~70mL × 72 = ~5L/min" },
    ],
    keyPoints: ["Erythropoiesis occurs in bone marrow. Lifespan of RBC: ~120 days.", "Leucocytes: granulocytes (neutrophils, eosinophils, basophils) and agranulocytes (lymphocytes, monocytes).", "Double circulation: pulmonary (heart-lungs-heart) and systemic (heart-body-heart)."],
    hasSimulation: true,
    simulationDescription: "Heart beating simulator — see cardiac cycle, valve movements, and blood flow through the four chambers.",
    sampleQuestions: [
      { question: "Universal blood donor is:", options: ["A", "B", "AB", "O"], answer: 3 },
      { question: "Pacemaker of heart:", options: ["AV node", "SA node", "Bundle of His", "Purkinje fibres"], answer: 1 },
      { question: "Normal BP in humans:", options: ["80/120 mmHg", "120/80 mmHg", "70/110 mmHg", "130/90 mmHg"], answer: 1 },
    ],
    prevChapterId: "chapter-17", nextChapterId: "chapter-19",
  },
  {
    chapterId: "chapter-19", order: 19,
    title: "Excretory Products and their Elimination",
    objective: "Study kidney structure, urine formation, osmoregulation, and disorders.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Kidney Structure", content: "Outer cortex, inner medulla (pyramids), pelvis → ureter → bladder → urethra. Nephron: filtering unit (~1 million per kidney). Parts: Bowman's capsule (glomerulus inside), PCT, Loop of Henle, DCT, Collecting duct." },
      { heading: "Urine Formation", content: "Glomerular filtration (GFR): ~125 mL/min, ~180 L/day filtered. Tubular reabsorption (99%): PCT (Na⁺, glucose, amino acids, water), Loop of Henle (water in descending, ions in ascending), DCT (selective reabsorption, hormone-regulated). Tubular secretion: H⁺, NH₄⁺, K⁺, drugs." },
      { heading: "Regulation", content: "ADH (antidiuretic hormone): increases water reabsorption in DCT/collecting duct (concentrated urine). Aldosterone: increases Na⁺/K⁺ exchange in DCT. Renin-angiotensin system regulates blood pressure." },
    ],
    keyFormulas: [
      { label: "GFR", formula: "~125 mL/min = 180 L/day" },
      { label: "Final urine output", formula: "~1-1.5 L/day (99% reabsorbed)" },
    ],
    keyPoints: ["Counter-current mechanism in loop of Henle creates osmotic gradient in medulla for urine concentration.", "Urine: water, urea, uric acid, creatinine, ions. Normal pH = 6.0.", "Dialysis (artificial kidney): removes waste by diffusion across selectively permeable membrane."],
    hasSimulation: true,
    simulationDescription: "Nephron function simulator — trace filtration, reabsorption, and secretion along the nephron with hormone controls.",
    sampleQuestions: [
      { question: "GFR per day approximately:", options: ["18 L", "180 L", "1.8 L", "1800 L"], answer: 1 },
      { question: "ADH increases urine volume.", options: ["True", "False — it decreases urine volume", "ADH has no effect", "Only in diabetics"], answer: 1 },
      { question: "Which part of nephron is in medulla?", options: ["PCT", "Bowman's capsule", "Loop of Henle", "DCT"], answer: 2 },
    ],
    prevChapterId: "chapter-18", nextChapterId: "chapter-20",
  },
  {
    chapterId: "chapter-20", order: 20,
    title: "Locomotion and Movement",
    objective: "Study skeletal muscle structure, mechanism of contraction, skeleton, and joints.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Types of Movement", content: "Amoeboid (pseudopodia), Ciliary (cilia), Muscular (skeletal, smooth, cardiac)." },
      { heading: "Skeletal Muscle Structure", content: "Muscle bundle → muscle fibre → myofibrils → sarcomere (basic functional unit). Sarcomere: A-band (myosin), I-band (actin), H-zone, Z-disc, M-line. Thin filaments: actin + troponin + tropomyosin. Thick: myosin." },
      { heading: "Sliding Filament Theory", content: "ATP hydrolysis → myosin head forms cross-bridge with actin → power stroke → thin filaments slide inward → sarcomere shortens. Ca²⁺ released from SR triggers contraction (binds troponin, exposes actin binding site)." },
      { heading: "Skeleton and Joints", content: "206 bones in adult human. Axial (80) + appendicular (126) skeleton. Joints: fibrous (immovable: skull sutures), cartilaginous (slightly movable: vertebrae), synovial (freely movable: hinge=knee, ball-and-socket=hip)." },
    ],
    keyFormulas: [],
    keyPoints: ["Red muscle fibres: many mitochondria, slow, fatigue-resistant. White fibres: fast, fewer mitochondria, fatigue quickly.", "Rigor mortis: post-death muscle stiffening due to no ATP for cross-bridge detachment.", "Actin: G-actin (globular) polymerizes to F-actin (filamentous); binds myosin S1 region."],
    hasSimulation: true,
    simulationDescription: "Sarcomere contraction simulator — visualize sliding filament theory with actin, myosin, and ATP in action.",
    sampleQuestions: [
      { question: "Basic functional unit of skeletal muscle:", options: ["Myofibril", "Sarcomere", "Muscle fibre", "Motor unit"], answer: 1 },
      { question: "Which band shortens during muscle contraction?", options: ["A-band", "I-band and H-zone", "Z-disc", "M-line"], answer: 1 },
      { question: "Hip joint is a type of:", options: ["Hinge joint", "Pivot joint", "Ball and socket joint", "Gliding joint"], answer: 2 },
    ],
    prevChapterId: "chapter-19", nextChapterId: "chapter-21",
  },
  {
    chapterId: "chapter-21", order: 21,
    title: "Neural Control and Coordination",
    objective: "Study the nervous system, neuron structure, synapse, reflex action, and the brain.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Neuron Structure", content: "Cell body (soma) + dendrites (receive) + axon (transmit) + axon terminals (synaptic knobs). Myelinated (saltatory conduction, faster) vs non-myelinated. Nodes of Ranvier in myelinated fibres." },
      { heading: "Resting and Action Potential", content: "Resting: –70mV (K⁺ inside, Na⁺ outside). Depolarization: Na⁺ channels open → inside becomes positive. Repolarization: Na⁺ channels close, K⁺ channels open → inside becomes negative. Hyperpolarization → resting state." },
      { heading: "Synapse", content: "Chemical synapse: neurotransmitter released from pre-synaptic terminal → diffuses across synaptic cleft → binds receptor on post-synaptic membrane. Acetylcholine (ACh), Dopamine, Serotonin, GABA are common neurotransmitters." },
      { heading: "Human Brain", content: "Forebrain: cerebrum (voluntary actions, intelligence, memory), thalamus (relay), hypothalamus (thermoregulation, hunger, sleep). Midbrain: visual/auditory reflexes. Hindbrain: cerebellum (balance, coordination), medulla (breathing, heart rate, BP), pons." },
    ],
    keyFormulas: [],
    keyPoints: ["All-or-none law: neuron fires completely or not at all.", "Reflex arc: receptor → afferent nerve → spinal cord → efferent nerve → effector.", "Blood-brain barrier: tight junctions in brain capillaries protect brain from toxins."],
    hasSimulation: true,
    simulationDescription: "Action potential simulator — watch Na⁺/K⁺ channel dynamics during nerve impulse propagation.",
    sampleQuestions: [
      { question: "Resting membrane potential of neuron:", options: ["+70 mV", "–70 mV", "0 mV", "–90 mV"], answer: 1 },
      { question: "Cerebellum controls:", options: ["Intelligence", "Memory", "Balance and coordination", "Hunger"], answer: 2 },
      { question: "First event in action potential:", options: ["K⁺ efflux", "Na⁺ influx", "Cl⁻ efflux", "Ca²⁺ influx"], answer: 1 },
    ],
    prevChapterId: "chapter-20", nextChapterId: "chapter-22",
  },
  {
    chapterId: "chapter-22", order: 22,
    title: "Chemical Coordination and Integration",
    objective: "Study the endocrine system — glands, hormones, mechanism of hormone action, and disorders.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Endocrine Glands and Hormones", content: "Pituitary (master gland): GH, TSH, ACTH, FSH, LH, prolactin, ADH, oxytocin. Thyroid: T₃, T₄ (metabolism), calcitonin (Ca²⁺ regulation). Parathyroid: PTH (increases Ca²⁺). Adrenal: cortex (cortisol, aldosterone), medulla (adrenaline, noradrenaline). Pancreas: insulin (decreases blood glucose), glucagon (increases). Gonads: testosterone (testes), estrogen/progesterone (ovaries)." },
      { heading: "Mechanism of Hormone Action", content: "Protein hormones (hydrophilic): bind membrane receptors → second messenger (cAMP, Ca²⁺) → cellular response. Steroid hormones (lipophilic): enter cell → bind nuclear receptor → gene expression change." },
      { heading: "Feedback Regulation", content: "Hypothalamus-pituitary-target organ axis. Negative feedback: hormone suppresses its own production. Example: high T₄ → inhibits TRH and TSH → reduces T₄ production." },
    ],
    keyFormulas: [],
    keyPoints: ["Hypothalamus is the master regulator — controls pituitary via releasing/inhibiting hormones.", "Diabetes mellitus: type 1 (no insulin), type 2 (insulin resistance). Diabetes insipidus: no ADH.", "Goiter: iodine deficiency → low T₄ → high TSH → enlarged thyroid."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Master gland of the body:", options: ["Thyroid", "Adrenal", "Pituitary", "Hypothalamus"], answer: 2 },
      { question: "Hormone that lowers blood glucose:", options: ["Glucagon", "Cortisol", "Insulin", "Adrenaline"], answer: 2 },
      { question: "Steroid hormones act by:", options: ["Binding cell surface receptor", "Second messenger system", "Entering cell and binding nuclear receptor", "Changing membrane permeability"], answer: 2 },
    ],
    prevChapterId: "chapter-21", nextChapterId: undefined,
  },
];
