/**
 * @file lib/content/class12-physics.ts
 * @description NCERT-aligned Class 12 Physics curriculum content
 * Every chapter matches NCERT Class 12 Physics (2025-26 edition)
 */

import type { ContentChapter } from "./class9-mathematics";

export const CLASS_12_PHYSICS_CHAPTERS: ContentChapter[] = [
  {
    chapterId: "chapter-01", order: 1,
    title: "Electric Charges and Fields",
    objective: "Understand Coulomb's law, electric field, Gauss's law, and field lines.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Electric Charge", content: "Charge is quantized: q = ne where e = 1.6×10⁻¹⁹ C, n ∈ Z. Charge is conserved. Like charges repel; unlike attract." },
      { heading: "Coulomb's Law", content: "F = kq₁q₂/r² = q₁q₂/4πε₀r². k = 9×10⁹ N·m²/C². ε₀ = 8.85×10⁻¹² C²/N·m²." },
      { heading: "Electric Field", content: "E = F/q₀ (field at a point = force per unit positive test charge). E due to point charge q: E = kq/r². Superposition: E_net = ΣEᵢ." },
      { heading: "Gauss's Law", content: "Net electric flux through any closed surface = Q_enclosed/ε₀. φ = ∮E·dA = Q/ε₀. Used to find E for symmetric charge distributions." },
    ],
    keyFormulas: [
      { label: "Coulomb's law", formula: "F = kq₁q₂/r² = q₁q₂/(4πε₀r²)" },
      { label: "Electric field (point charge)", formula: "E = kq/r²" },
      { label: "Gauss's law", formula: "∮E·dA = Q_enc/ε₀" },
      { label: "E for infinite line charge", formula: "E = λ/(2πε₀r)" },
    ],
    keyPoints: ["Electric field lines start from + charges and end at – charges.", "Field lines never cross each other.", "Gauss's law: easiest for spherical, cylindrical, and planar symmetry."],
    hasSimulation: true,
    simulationDescription: "Electric field visualizer — see field lines around point charges and charge distributions.",
    sampleQuestions: [
      { question: "Force between 1C and 1C charges 1m apart in vacuum (k=9×10⁹):", options: ["9×10⁹ N", "9 N", "1 N", "9×10⁻⁹ N"], answer: 0 },
      { question: "Electric flux through a surface with Q=2ε₀ enclosed:", options: ["2 V·m", "ε₀ V·m", "2/ε₀ V·m", "ε₀/2 V·m"], answer: 0 },
      { question: "Electric field inside a hollow conductor:", options: ["Maximum", "Non-zero", "Zero", "Depends on shape"], answer: 2 },
    ],
    prevChapterId: undefined, nextChapterId: "chapter-02",
  },
  {
    chapterId: "chapter-02", order: 2,
    title: "Electrostatic Potential and Capacitance",
    objective: "Study electric potential, potential energy, capacitors, dielectrics, and energy stored in capacitors.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Electric Potential", content: "V = W/q₀ (work done per unit positive charge). V due to point charge: V = kq/r. Potential is a scalar. Equipotential surfaces: E is perpendicular to them." },
      { heading: "Capacitance", content: "Capacitor stores charge. C = Q/V. For parallel plate: C = ε₀A/d. With dielectric: C = Kε₀A/d where K is dielectric constant." },
      { heading: "Capacitors in Series and Parallel", content: "Series: 1/C_eff = Σ1/Cᵢ (same charge). Parallel: C_eff = ΣCᵢ (same voltage)." },
      { heading: "Energy Stored", content: "U = ½CV² = Q²/2C = QV/2. Energy density = ½ε₀E²." },
    ],
    keyFormulas: [
      { label: "Parallel plate capacitance", formula: "C = ε₀A/d (air); C = Kε₀A/d (dielectric)" },
      { label: "Energy stored", formula: "U = ½CV² = Q²/(2C)" },
      { label: "Series capacitors", formula: "1/C = 1/C₁ + 1/C₂ + ..." },
      { label: "Parallel capacitors", formula: "C = C₁ + C₂ + ..." },
    ],
    keyPoints: ["Potential inside a conductor is constant (equals surface potential).", "Dielectric increases capacitance by factor K.", "When capacitors are connected in series, the total capacitance decreases."],
    hasSimulation: true,
    simulationDescription: "Capacitor charging/discharging simulator — see Q, V, U vs time with adjustable C and V.",
    sampleQuestions: [
      { question: "Capacitance of parallel plate capacitor doubles when plate area:", options: ["Halves", "Doubles", "Stays same", "Quadruples"], answer: 1 },
      { question: "Energy stored in 4μF capacitor at 10V:", options: ["200 μJ", "40 μJ", "400 μJ", "0.2 μJ"], answer: 0 },
      { question: "Three 3μF capacitors in series give:", options: ["9 μF", "1 μF", "3 μF", "6 μF"], answer: 1 },
    ],
    prevChapterId: "chapter-01", nextChapterId: "chapter-03",
  },
  {
    chapterId: "chapter-03", order: 3,
    title: "Current Electricity",
    objective: "Study Ohm's law, resistance, cells, Kirchhoff's laws, Wheatstone bridge, and potentiometer.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Ohm's Law and Resistance", content: "V = IR. Resistance R = ρL/A where ρ is resistivity, L is length, A is cross-sectional area. Conductance G = 1/R. Conductivity σ = 1/ρ." },
      { heading: "Cells and EMF", content: "EMF (ε): work done per unit charge by cell. Terminal voltage V = ε – Ir where r is internal resistance. For n cells in series: ε_eff = nε, r_eff = nr." },
      { heading: "Kirchhoff's Laws", content: "KCL: Σ currents at a junction = 0 (charge conservation). KVL: Σ EMFs and Σ voltage drops in a closed loop = 0 (energy conservation)." },
      { heading: "Wheatstone Bridge", content: "P/Q = R/S at balance condition (galvanometer reads zero). Used for precise resistance measurement." },
    ],
    keyFormulas: [
      { label: "Ohm's law", formula: "V = IR; R = ρL/A" },
      { label: "Power dissipated", formula: "P = IV = I²R = V²/R" },
      { label: "Terminal voltage", formula: "V = ε – Ir" },
      { label: "Wheatstone bridge balance", formula: "P/Q = R/S" },
    ],
    keyPoints: ["Resistors in series: R_eff = ΣRᵢ. In parallel: 1/R_eff = Σ1/Rᵢ.", "Power dissipated in resistor = I²R (heat loss).", "Potentiometer measures EMF without drawing current — more accurate than voltmeter."],
    hasSimulation: true,
    simulationDescription: "Circuit simulator — build circuits with batteries, resistors; measure V and I with virtual meters.",
    sampleQuestions: [
      { question: "Three 6Ω resistors in parallel. Equivalent resistance:", options: ["18 Ω", "2 Ω", "3 Ω", "6 Ω"], answer: 1 },
      { question: "Power dissipated by 10Ω resistor carrying 2A:", options: ["20 W", "40 W", "5 W", "100 W"], answer: 1 },
      { question: "EMF = 6V, r = 1Ω, R = 5Ω. Terminal voltage:", options: ["5V", "6V", "5.5V", "1V"], answer: 0 },
    ],
    prevChapterId: "chapter-02", nextChapterId: "chapter-04",
  },
  {
    chapterId: "chapter-04", order: 4,
    title: "Moving Charges and Magnetism",
    objective: "Study magnetic force on moving charges and current-carrying conductors, Biot-Savart law, Ampere's law.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Magnetic Force on Charge", content: "F = q(v×B). Magnitude: F = qvB sinθ. For circular motion: qvB = mv²/r → r = mv/qB." },
      { heading: "Force on Current Conductor", content: "F = IL×B. Magnitude: F = BIL sinθ. Force between parallel wires: F/L = μ₀I₁I₂/(2πd). Parallel currents attract; antiparallel repel." },
      { heading: "Biot-Savart Law", content: "dB = μ₀I(dL×r̂)/(4πr²). For infinite straight wire: B = μ₀I/(2πr). At centre of circular loop: B = μ₀I/(2R)." },
      { heading: "Ampere's Circuital Law", content: "∮B·dL = μ₀I_enclosed. For solenoid: B = μ₀nI inside (n = turns/length), 0 outside. For toroid: B = μ₀nI inside, 0 outside." },
    ],
    keyFormulas: [
      { label: "Magnetic force on charge", formula: "F = qvB sinθ" },
      { label: "Radius of circular orbit", formula: "r = mv/(qB)" },
      { label: "B due to infinite wire", formula: "B = μ₀I/(2πr)" },
      { label: "B at centre of circular loop", formula: "B = μ₀I/(2R)" },
      { label: "Solenoid B inside", formula: "B = μ₀nI" },
    ],
    keyPoints: ["μ₀ = 4π×10⁻⁷ T·m/A (permeability of free space).", "A charged particle in a magnetic field moves in a circle (no work done by B).", "Galvanometer can be converted to ammeter (shunt in parallel) or voltmeter (high R in series)."],
    hasSimulation: true,
    simulationDescription: "Charged particle in magnetic field simulator — visualize circular and helical motion with adjustable v and B.",
    sampleQuestions: [
      { question: "Radius of proton orbit in B=1T at v=10⁶ m/s (m=1.67×10⁻²⁷kg, q=1.6×10⁻¹⁹C):", options: ["~0.01 m", "~0.1 m", "~1 m", "~10 m"], answer: 0 },
      { question: "B at 1m from long wire carrying 1A (μ₀=4π×10⁻⁷):", options: ["2×10⁻⁷ T", "4π×10⁻⁷ T", "2×10⁻⁷ π T", "10⁻⁷ T"], answer: 0 },
      { question: "Solenoid has 1000 turns/m, carries 2A. B inside (μ₀=4π×10⁻⁷):", options: ["4π×10⁻⁴ T", "4π×10⁻³ T", "2π×10⁻⁴ T", "8π×10⁻⁴ T"], answer: 1 },
    ],
    prevChapterId: "chapter-03", nextChapterId: "chapter-05",
  },
  {
    chapterId: "chapter-05", order: 5,
    title: "Magnetism and Matter",
    objective: "Study magnetic properties of materials, magnetization, earth's magnetism, and permanent magnets.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Bar Magnet as Dipole", content: "Magnetic dipole moment M = m × 2l (pole strength × magnetic length). B on axial point: μ₀·2M/(4π·d³). B on equatorial point: –μ₀M/(4π·d³)." },
      { heading: "Magnetic Materials", content: "Diamagnetic: repelled by magnet, χ < 0 (Bi, Cu, water). Paramagnetic: attracted weakly, χ > 0 (Al, Mn). Ferromagnetic: strongly attracted, permanent magnets (Fe, Co, Ni)." },
      { heading: "Earth's Magnetism", content: "Earth's magnetic south pole is near geographic north pole. Declination: angle between magnetic and geographic north. Dip/inclination: angle of B with horizontal. Horizontal component H = B cosδ." },
    ],
    keyFormulas: [
      { label: "Axial field of bar magnet", formula: "B = μ₀·2M/(4πd³)" },
      { label: "Equatorial field", formula: "B = μ₀M/(4πd³)" },
      { label: "Horizontal component of Earth's field", formula: "H = B cosδ (δ = angle of dip)" },
    ],
    keyPoints: ["Diamagnetic: negative susceptibility, expelled from strong fields.", "Ferromagnetic: domains align under field, shows hysteresis.", "Curie temperature: above this, ferromagnet becomes paramagnetic."],
    hasSimulation: true,
    simulationDescription: "Earth's magnetic field and bar magnet interaction visualizer with field lines.",
    sampleQuestions: [
      { question: "Which material is strongly attracted to a magnet?", options: ["Copper", "Bismuth", "Iron", "Aluminum"], answer: 2 },
      { question: "At magnetic equator, angle of dip is:", options: ["90°", "45°", "0°", "Varies"], answer: 2 },
      { question: "Which property distinguishes ferromagnetic from paramagnetic?", options: ["Positive χ", "Domain structure", "Attracted to magnet", "Contains iron"], answer: 1 },
    ],
    prevChapterId: "chapter-04", nextChapterId: "chapter-06",
  },
  {
    chapterId: "chapter-06", order: 6,
    title: "Electromagnetic Induction",
    objective: "Understand Faraday's laws, Lenz's law, motional EMF, self-induction, and mutual induction.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Faraday's Laws", content: "EMF induced = –dΦ/dt (Faraday's first law). Magnitude of induced EMF = rate of change of magnetic flux. Φ = NBA cosθ." },
      { heading: "Lenz's Law", content: "Induced current opposes the change that causes it (conserves energy). This gives the negative sign in Faraday's law." },
      { heading: "Self-Induction", content: "Self-inductance L: Φ = LI. Induced EMF = –L(dI/dt). L for solenoid = μ₀n²V = μ₀n²Al. Unit: Henry (H)." },
      { heading: "Mutual Induction", content: "M: flux in coil 2 due to current in coil 1. ε₂ = –M(dI₁/dt). Transformer works on mutual induction." },
    ],
    keyFormulas: [
      { label: "Induced EMF", formula: "ε = –dΦ/dt = –N·d(BA)/dt" },
      { label: "Motional EMF", formula: "ε = BLv" },
      { label: "Self-inductance of solenoid", formula: "L = μ₀n²Al" },
      { label: "Energy stored in inductor", formula: "U = ½LI²" },
    ],
    keyPoints: ["Eddy currents: induced currents in bulk conductors — cause heating, used in induction cookers.", "AC generator: ε = NBAω sin(ωt) = ε₀ sinωt.", "Back-EMF in motors opposes applied voltage, limiting current."],
    hasSimulation: true,
    simulationDescription: "Electromagnetic induction simulator — move magnet through coil and observe induced current.",
    sampleQuestions: [
      { question: "A coil of 100 turns has flux changing at 0.05 Wb/s. Induced EMF:", options: ["5 V", "0.5 V", "50 V", "500 V"], answer: 0 },
      { question: "Lenz's law is a consequence of:", options: ["Gauss's law", "Conservation of energy", "Newton's 3rd law", "Ampere's law"], answer: 1 },
      { question: "Energy stored in 2H inductor with 5A:", options: ["25 J", "50 J", "10 J", "5 J"], answer: 0 },
    ],
    prevChapterId: "chapter-05", nextChapterId: "chapter-07",
  },
  {
    chapterId: "chapter-07", order: 7,
    title: "Alternating Current",
    objective: "Study AC circuits — resistance, inductance, capacitance, LC oscillations, transformers, and resonance.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "AC Basics", content: "v = V₀ sinωt; i = I₀ sin(ωt + φ). RMS values: V_rms = V₀/√2; I_rms = I₀/√2. Power P = V_rms·I_rms·cosφ (cosφ is power factor)." },
      { heading: "AC Components", content: "Resistor: V and I in phase. Inductor: V leads I by 90°, X_L = ωL. Capacitor: I leads V by 90°, X_C = 1/(ωC)." },
      { heading: "Series LCR Circuit", content: "Impedance Z = √(R² + (X_L – X_C)²). Resonance at ω₀ = 1/√(LC): Z = R (minimum), I = maximum." },
      { heading: "Transformer", content: "V_s/V_p = N_s/N_p = I_p/I_s (for ideal transformer). Step-up: N_s > N_p; Step-down: N_s < N_p. Power input ≈ Power output (ideal)." },
    ],
    keyFormulas: [
      { label: "Rms values", formula: "V_rms = V₀/√2; I_rms = I₀/√2" },
      { label: "Impedance", formula: "Z = √(R² + (X_L – X_C)²)" },
      { label: "Resonant frequency", formula: "ω₀ = 1/√(LC); f₀ = 1/(2π√(LC))" },
      { label: "Transformer ratio", formula: "V_s/V_p = N_s/N_p" },
      { label: "Power factor", formula: "cos φ = R/Z" },
    ],
    keyPoints: ["At resonance: X_L = X_C, phase angle = 0, power factor = 1.", "Quality factor Q = ω₀L/R = (resonant frequency)/(bandwidth).", "Wattless current is the component that does no work (imaginary part)."],
    hasSimulation: true,
    simulationDescription: "AC circuit phasor diagram — visualize voltage and current phasors for R, L, C and series LCR circuits.",
    sampleQuestions: [
      { question: "Rms of AC with peak value 311V is approximately:", options: ["220 V", "311 V", "155 V", "440 V"], answer: 0 },
      { question: "In an LC circuit, resonance frequency f₀ = 1/(2π√LC). If L=1mH, C=1μF, f₀=?", options: ["~5033 Hz", "~1000 Hz", "~10000 Hz", "~159 Hz"], answer: 0 },
      { question: "Step-up transformer with N_p=100, N_s=1000, V_p=220V. V_s = ?", options: ["22 V", "2200 V", "220 V", "22000 V"], answer: 1 },
    ],
    prevChapterId: "chapter-06", nextChapterId: "chapter-08",
  },
  {
    chapterId: "chapter-08", order: 8,
    title: "Electromagnetic Waves",
    objective: "Understand Maxwell's equations, EM wave properties, spectrum, and applications.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Maxwell's Equations", content: "Maxwell added displacement current (ε₀dΦ_E/dt) to Ampere's law, predicting EM waves. The four equations unify electricity and magnetism." },
      { heading: "EM Waves", content: "E and B oscillate perpendicular to each other and to direction of propagation. Speed in vacuum: c = 1/√(μ₀ε₀) = 3×10⁸ m/s." },
      { heading: "EM Spectrum", content: "Radio waves (longest λ) → Microwaves → IR → Visible → UV → X-rays → Gamma rays (shortest λ, highest energy). All travel at c in vacuum." },
    ],
    keyFormulas: [
      { label: "Speed of EM waves", formula: "c = 1/√(μ₀ε₀) = 3×10⁸ m/s" },
      { label: "Energy of photon", formula: "E = hf = hc/λ" },
      { label: "Relation c, λ, f", formula: "c = fλ" },
    ],
    keyPoints: ["EM waves carry energy and momentum but no mass.", "Visible light: 400-700 nm (violet to red).", "Microwaves used in cooking (resonance with water molecules); X-rays for medical imaging."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Speed of EM waves in vacuum:", options: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10¹⁰ m/s", "3×10⁴ m/s"], answer: 0 },
      { question: "Which EM wave has highest frequency?", options: ["Radio waves", "Visible light", "X-rays", "Gamma rays"], answer: 3 },
      { question: "Maxwell's contribution to Ampere's law:", options: ["Added magnetic force term", "Added displacement current", "Added gravitational term", "Removed the integral"], answer: 1 },
    ],
    prevChapterId: "chapter-07", nextChapterId: "chapter-09",
  },
  {
    chapterId: "chapter-09", order: 9,
    title: "Ray Optics and Optical Instruments",
    objective: "Study reflection, refraction, TIR, lenses, mirrors, and optical instruments like microscope and telescope.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Reflection at Curved Mirrors", content: "Mirror formula: 1/v + 1/u = 1/f = 2/R. Magnification m = –v/u. Sign convention: distances measured from pole; incident ray direction is positive." },
      { heading: "Refraction and Snell's Law", content: "n₁ sinθ₁ = n₂ sinθ₂. TIR occurs when θ > θc where sinθc = n₂/n₁ (n₁ > n₂). Used in optical fibre." },
      { heading: "Refraction at Lenses", content: "Lens formula: 1/v – 1/u = 1/f. Lensmaker's equation: 1/f = (n–1)(1/R₁ – 1/R₂). Power P = 1/f (in metres), unit: Diopter (D)." },
      { heading: "Optical Instruments", content: "Microscope: m = –L/f₀ × D/f_e. Telescope: m = –f₀/f_e. Resolving power of microscope = 2n sinθ/λ." },
    ],
    keyFormulas: [
      { label: "Mirror formula", formula: "1/v + 1/u = 1/f" },
      { label: "Lens formula", formula: "1/v – 1/u = 1/f" },
      { label: "Snell's law", formula: "n₁sinθ₁ = n₂sinθ₂" },
      { label: "Lens power", formula: "P = 1/f (metres), unit: D" },
      { label: "Critical angle", formula: "sinθc = n₂/n₁" },
    ],
    keyPoints: ["Concave mirror: f < 0 (sign convention). Convex lens: f > 0.", "Power of combination of lenses: P = P₁ + P₂.", "Human eye: near point = 25 cm; far point = ∞ (normal vision)."],
    hasSimulation: true,
    simulationDescription: "Ray optics simulator — trace rays through lenses and mirrors, see image formation interactively.",
    sampleQuestions: [
      { question: "Object at 30 cm from concave mirror (f=–15cm). Image at:", options: ["15 cm", "–30 cm", "30 cm", "–15 cm"], answer: 1 },
      { question: "Critical angle for glass (n=1.5) to air:", options: ["42°", "48°", "60°", "30°"], answer: 0 },
      { question: "Two lenses, P=+3D and P=–1D combined. Total P:", options: ["–4 D", "+2 D", "+4 D", "+3 D"], answer: 1 },
    ],
    prevChapterId: "chapter-08", nextChapterId: "chapter-10",
  },
  {
    chapterId: "chapter-10", order: 10,
    title: "Wave Optics",
    objective: "Study wave nature of light — interference (Young's experiment), diffraction, and polarization.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Huygens' Principle", content: "Every point on a wavefront is a source of secondary wavelets. The tangent to these wavelets gives the new wavefront. Explains reflection and refraction of light." },
      { heading: "Young's Double Slit Experiment", content: "Constructive (bright fringe): path difference = nλ. Destructive (dark): path difference = (2n+1)λ/2. Fringe width β = λD/d." },
      { heading: "Diffraction", content: "Single slit: minima at a sinθ = nλ (n ≠ 0). Central maximum is twice as wide. Resolving power limited by diffraction." },
      { heading: "Polarization", content: "Light is transverse — can be polarized. Malus's law: I = I₀ cos²θ. Brewster's angle: tan i_B = n (reflected light is completely polarized)." },
    ],
    keyFormulas: [
      { label: "Fringe width (YDSE)", formula: "β = λD/d" },
      { label: "Path difference for bright fringe", formula: "Δx = nλ" },
      { label: "Malus's law", formula: "I = I₀ cos²θ" },
      { label: "Brewster's angle", formula: "tan i_B = n₂/n₁" },
    ],
    keyPoints: ["Interference requires coherent sources (constant phase difference).", "Diffraction is prominent when λ ≈ size of obstacle.", "Unpolarized light through polaroid becomes polarized; intensity halved."],
    hasSimulation: true,
    simulationDescription: "Young's double slit interference pattern simulator — vary λ, d, D to see fringe pattern changes.",
    sampleQuestions: [
      { question: "YDSE: λ=600nm, D=1m, d=1mm. Fringe width β:", options: ["0.6 mm", "0.06 mm", "6 mm", "0.006 mm"], answer: 0 },
      { question: "Polarized light of intensity I₀ passes through analyzer at 60°. Output:", options: ["I₀/4", "I₀/2", "3I₀/4", "I₀"], answer: 0 },
      { question: "Diffraction is significant when wavelength is:", options: ["Much larger than obstacle", "Comparable to obstacle size", "Much smaller than obstacle", "Any size"], answer: 1 },
    ],
    prevChapterId: "chapter-09", nextChapterId: "chapter-11",
  },
  {
    chapterId: "chapter-11", order: 11,
    title: "Dual Nature of Radiation and Matter",
    objective: "Understand photoelectric effect, de Broglie hypothesis, and wave-particle duality.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Photoelectric Effect", content: "When light above threshold frequency hits metal, electrons are emitted. Einstein's equation: KE_max = hf – φ (φ = work function). No effect below threshold frequency." },
      { heading: "Einstein's Photoelectric Equation", content: "KE_max = hf – φ = eV₀ (V₀ = stopping potential). Threshold frequency: f₀ = φ/h. Increasing intensity increases number of photoelectrons, not their energy." },
      { heading: "de Broglie Hypothesis", content: "Every particle has an associated wavelength: λ = h/mv = h/p. For electron accelerated through V volts: λ = h/√(2meV) = 1.22/√V nm." },
    ],
    keyFormulas: [
      { label: "Photoelectric equation", formula: "KE_max = hf – φ = eV₀" },
      { label: "de Broglie wavelength", formula: "λ = h/p = h/mv" },
      { label: "For electron at voltage V", formula: "λ = 1.22/√V nm (approx.)" },
    ],
    keyPoints: ["h = 6.626×10⁻³⁴ J·s (Planck's constant).", "Stopping potential V₀ is independent of intensity.", "Wave-particle duality: all particles exhibit wave properties; most observable at atomic scale."],
    hasSimulation: true,
    simulationDescription: "Photoelectric effect simulator — vary frequency and intensity of light, observe stopping potential and photocurrent.",
    sampleQuestions: [
      { question: "Work function of metal = 2eV. Threshold frequency (h=6.6×10⁻³⁴, e=1.6×10⁻¹⁹):", options: ["~4.8×10¹⁴ Hz", "~5×10¹⁴ Hz", "~3×10¹⁴ Hz", "~1×10¹⁴ Hz"], answer: 0 },
      { question: "In photoelectric effect, stopping potential depends on:", options: ["Intensity", "Frequency of light", "Number of photons", "Area of surface"], answer: 1 },
      { question: "de Broglie wavelength of a particle depends on its:", options: ["Size", "Charge", "Momentum", "Temperature"], answer: 2 },
    ],
    prevChapterId: "chapter-10", nextChapterId: "chapter-12",
  },
  {
    chapterId: "chapter-12", order: 12,
    title: "Atoms",
    objective: "Study Rutherford model, Bohr model, atomic spectra, and energy levels of hydrogen atom.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Rutherford's Nuclear Model", content: "Alpha particle scattering showed: atom has a tiny dense positive nucleus; electrons orbit around it. Size of nucleus ~10⁻¹⁵ m; atom ~10⁻¹⁰ m." },
      { heading: "Bohr's Model", content: "Electrons move in discrete orbits (quantized angular momentum: mvr = nh/2π). Energy: Eₙ = –13.6/n² eV. Radius: rₙ = 0.529n² Å. Transitions: ΔE = hf (photon emitted/absorbed)." },
      { heading: "Spectral Series of Hydrogen", content: "Lyman (UV, n₂→1), Balmer (visible, n₂→2), Paschen (IR, n₂→3), Brackett (IR, n₂→4), Pfund (IR, n₂→5). Rydberg formula: 1/λ = R(1/n₁² – 1/n₂²)." },
    ],
    keyFormulas: [
      { label: "Bohr energy levels", formula: "Eₙ = –13.6/n² eV" },
      { label: "Bohr radius", formula: "rₙ = 0.529 n² Å" },
      { label: "Rydberg formula", formula: "1/λ = R(1/n₁² – 1/n₂²); R = 1.097×10⁷ m⁻¹" },
    ],
    keyPoints: ["Ground state of H: E₁ = –13.6 eV; ionization energy = 13.6 eV.", "Balmer series is in visible region: n₂ = 3,4,5,6 → n₁ = 2.", "Bohr model works only for hydrogen-like (one-electron) atoms."],
    hasSimulation: true,
    simulationDescription: "Hydrogen atom energy level diagram — click transitions to see photon wavelength and corresponding spectral series.",
    sampleQuestions: [
      { question: "Energy of electron in n=2 orbit of hydrogen:", options: ["–13.6 eV", "–3.4 eV", "–1.51 eV", "–0.85 eV"], answer: 1 },
      { question: "Balmer series of hydrogen is in which region?", options: ["UV", "IR", "Visible", "X-ray"], answer: 2 },
      { question: "First Bohr orbit radius of hydrogen:", options: ["0.529 Å", "0.529 nm", "0.529 m", "0.529 cm"], answer: 0 },
    ],
    prevChapterId: "chapter-11", nextChapterId: "chapter-13",
  },
  {
    chapterId: "chapter-13", order: 13,
    title: "Nuclei",
    objective: "Study nuclear structure, binding energy, radioactive decay laws, fission, and fusion.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Nuclear Structure", content: "Nucleus: protons (Z) + neutrons (N). Mass number A = Z + N. Nuclear density ~10¹⁷ kg/m³ (same for all nuclei). Nuclear radius: R = R₀A^(1/3), R₀ = 1.2 fm." },
      { heading: "Mass Defect and Binding Energy", content: "Mass defect Δm = Zm_p + Nm_n – M_nucleus. Binding energy BE = Δm × c². BE per nucleon peaks at Fe-56 (~8.8 MeV) — most stable nucleus." },
      { heading: "Radioactive Decay", content: "Alpha decay: ₂₄He emission; Beta decay: electron or positron emission; Gamma: electromagnetic radiation. Activity A = λN = A₀e^(–λt). Half-life t½ = 0.693/λ." },
      { heading: "Fission and Fusion", content: "Fission: heavy nucleus splits (²³⁵U + n → two mid-weight nuclei + 2-3n + 200 MeV). Fusion: light nuclei combine (²H + ³H → ⁴He + n + 17.6 MeV). Fusion powers stars." },
    ],
    keyFormulas: [
      { label: "Nuclear radius", formula: "R = R₀A^(1/3)" },
      { label: "Binding energy", formula: "BE = [Zm_p + Nm_n – M]c²" },
      { label: "Radioactive decay law", formula: "N = N₀e^(–λt)" },
      { label: "Half-life", formula: "t½ = ln2/λ = 0.693/λ" },
    ],
    keyPoints: ["1 u = 931.5 MeV (mass-energy equivalence).", "Alpha particles are stopped by paper; beta by aluminum; gamma by lead/concrete.", "Chain reaction: neutrons from fission trigger more fissions — critical mass needed."],
    hasSimulation: true,
    simulationDescription: "Radioactive decay simulator — see exponential decay, half-life visualization, and decay series.",
    sampleQuestions: [
      { question: "Half-life of element is 10 days. After 30 days, fraction remaining:", options: ["1/8", "1/4", "1/2", "1/16"], answer: 0 },
      { question: "Most stable nucleus has highest:", options: ["Mass number", "Binding energy per nucleon", "Proton number", "Neutron number"], answer: 1 },
      { question: "In alpha decay, mass number decreases by:", options: ["1", "2", "4", "0"], answer: 2 },
    ],
    prevChapterId: "chapter-12", nextChapterId: "chapter-14",
  },
  {
    chapterId: "chapter-14", order: 14,
    title: "Semiconductor Electronics",
    objective: "Study semiconductors, p-n junction, diodes, transistors, logic gates, and digital circuits.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Semiconductors", content: "Conductivity between conductors and insulators. Intrinsic: pure Si or Ge. Extrinsic: N-type (donor impurities, extra e⁻), P-type (acceptor impurities, holes)." },
      { heading: "p-n Junction Diode", content: "Depletion region forms at junction. Forward bias: thin depletion layer, current flows. Reverse bias: wide depletion layer, very small reverse current. Breakdown voltage: Zener breakdown." },
      { heading: "Transistors", content: "BJT: NPN or PNP, three terminals (Emitter, Base, Collector). Common Emitter configuration: current gain β = I_C/I_B (typically 20-200). Used as amplifier and switch." },
      { heading: "Logic Gates", content: "AND: output 1 only if both inputs 1. OR: output 1 if any input 1. NOT: inverts. NAND and NOR are universal gates (can implement any logic). XOR: output 1 if inputs differ." },
    ],
    keyFormulas: [
      { label: "Diode equation", formula: "I = I₀(e^(V/ηVT) – 1)" },
      { label: "Current gain (CE)", formula: "β = IC/IB; α = IC/IE; β = α/(1–α)" },
      { label: "Efficiency of half-wave rectifier", formula: "η = 40.6%" },
    ],
    keyPoints: ["Zener diode is used for voltage regulation in reverse bias.", "NAND and NOR gates are universal — can build any circuit from just NAND (or just NOR).", "For transistor as switch: saturation = ON; cutoff = OFF."],
    hasSimulation: true,
    simulationDescription: "Logic gate simulator — build digital circuits with AND, OR, NOT gates and see truth table outputs.",
    sampleQuestions: [
      { question: "N-type semiconductor is formed by adding:", options: ["Acceptor impurity", "Donor impurity", "Intrinsic atoms", "Both types"], answer: 1 },
      { question: "In common emitter, if β=100 and IB=10μA, IC=?", options: ["100 μA", "1 mA", "10 mA", "0.1 mA"], answer: 1 },
      { question: "Output of NAND gate for inputs 1,1:", options: ["0", "1", "Undefined", "Depends on V"], answer: 0 },
    ],
    prevChapterId: "chapter-13", nextChapterId: undefined,
  },
];
