/**
 * @file lib/content/class12-chemistry.ts
 * @description NCERT-aligned Class 12 Chemistry curriculum content
 * Every chapter matches NCERT Class 12 Chemistry (2025-26 edition)
 */

import type { ContentChapter } from "./class9-mathematics";

export const CLASS_12_CHEMISTRY_CHAPTERS: ContentChapter[] = [
  {
    chapterId: "chapter-01", order: 1,
    title: "The Solid State",
    objective: "Study classification of solids, crystal structures, Bravais lattices, packing efficiency, and defects.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Types of Solids", content: "Crystalline (definite geometric shape, sharp melting point): ionic, covalent, metallic, molecular. Amorphous (no regular structure, gradual softening): glass, rubber, plastics." },
      { heading: "Crystal Lattice and Unit Cells", content: "Bravais lattices: 7 crystal systems, 14 Bravais lattices. Unit cells: Simple cubic (SC), Body-centered cubic (BCC), Face-centered cubic (FCC/CCP)." },
      { heading: "Packing Efficiency", content: "SC: 52.4%. BCC: 68%. FCC/CCP: 74% (most efficient). Coordination number: SC=6, BCC=8, FCC=12." },
      { heading: "Defects", content: "Point defects: Schottky (anion-cation pair missing), Frenkel (cation moves to interstitial site). Impurity defects. F-centres (anion vacancy with trapped electron — colour in crystals)." },
    ],
    keyFormulas: [
      { label: "Number of atoms in unit cell", formula: "SC: 1; BCC: 2; FCC: 4" },
      { label: "Density of crystal", formula: "ρ = Z×M/(Nₐ×a³)" },
      { label: "Radius ratio for coordination number 6", formula: "r/R = 0.414 to 0.732" },
    ],
    keyPoints: ["In FCC, octahedral voids = n, tetrahedral voids = 2n (n = number of atoms).", "Schottky defect decreases density; Frenkel defect doesn't.", "Semiconductors can be intrinsic or extrinsic (n-type or p-type)."],
    hasSimulation: true,
    simulationDescription: "Crystal unit cell visualizer — explore SC, BCC, and FCC structures with atom packing and voids.",
    sampleQuestions: [
      { question: "Packing efficiency of FCC structure:", options: ["52.4%", "68%", "74%", "90%"], answer: 2 },
      { question: "Coordination number in BCC:", options: ["6", "8", "12", "4"], answer: 1 },
      { question: "Which defect causes decrease in density?", options: ["Frenkel", "Schottky", "F-centre", "Interstitial"], answer: 1 },
    ],
    prevChapterId: undefined, nextChapterId: "chapter-02",
  },
  {
    chapterId: "chapter-02", order: 2,
    title: "Solutions",
    objective: "Study types of solutions, concentration terms, colligative properties, and abnormal molar masses.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Concentration Terms", content: "Molarity (M) = mol/L. Molality (m) = mol/kg solvent. Mole fraction (X) = n_A/(n_A+n_B). Mass percent (%) = (mass solute/mass solution)×100." },
      { heading: "Raoult's Law", content: "P_solution = X_A·P°_A + X_B·P°_B. Ideal solution: follows Raoult's law, ΔH_mix=0, ΔV_mix=0. Positive deviation: A-B interactions weaker than A-A and B-B (e.g., ethanol+water)." },
      { heading: "Colligative Properties", content: "Depend on number of solute particles, not nature. 1) ΔP = X_B·P°_A (vapour pressure lowering). 2) ΔTb = Kb·m (boiling point elevation). 3) ΔTf = Kf·m (freezing point depression). 4) π = MRT (osmotic pressure)." },
      { heading: "Abnormal Molar Mass", content: "Van't Hoff factor i = observed colligative property / expected colligative property. Electrolytes: i > 1 (dissociation). Association: i < 1 (e.g., acetic acid in benzene, i=0.5)." },
    ],
    keyFormulas: [
      { label: "Boiling point elevation", formula: "ΔTb = Kb × m (Kb = ebullioscopic constant)" },
      { label: "Freezing point depression", formula: "ΔTf = Kf × m (Kf = cryoscopic constant)" },
      { label: "Osmotic pressure", formula: "π = MRT = (n/V)RT" },
      { label: "Van't Hoff factor", formula: "i = actual/expected colligative property" },
      { label: "Molality from ΔTf", formula: "m = ΔTf/Kf → molar mass = w×1000/(m×W)" },
    ],
    keyPoints: ["Water Kf = 1.86 K·kg/mol; Kb = 0.52 K·kg/mol.", "Osmosis: solvent moves from dilute to concentrated solution through semipermeable membrane.", "Reverse osmosis used in water purification."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Osmotic pressure of 0.1 M glucose at 300 K (R=0.083 L·bar/mol·K):", options: ["2.49 bar", "0.249 bar", "24.9 bar", "0.83 bar"], answer: 0 },
      { question: "Kf for water = 1.86. ΔTf for 0.5 molal solution:", options: ["0.93°C", "3.72°C", "1.86°C", "0.465°C"], answer: 0 },
      { question: "Van't Hoff factor for NaCl in dilute solution:", options: ["1", "0.5", "2", "3"], answer: 2 },
    ],
    prevChapterId: "chapter-01", nextChapterId: "chapter-03",
  },
  {
    chapterId: "chapter-03", order: 3,
    title: "Electrochemistry",
    objective: "Study electrochemical cells, Nernst equation, conductance, electrolysis, and corrosion.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Galvanic Cells", content: "Spontaneous redox reaction generates electrical energy. Cell notation: Anode || Cathode (oxidation at anode, reduction at cathode). Cell potential E_cell = E_cathode – E_anode." },
      { heading: "Standard Electrode Potential", content: "Measured vs. SHE (E° = 0). Species with higher (more positive) E° gets reduced. E°_cell = E°_cathode – E°_anode. ΔG° = –nFE°_cell." },
      { heading: "Nernst Equation", content: "E_cell = E°_cell – (RT/nF)ln Q = E°_cell – (0.0592/n)log Q at 25°C." },
      { heading: "Conductance", content: "Conductance G = 1/R. Conductivity κ = G × l/A. Molar conductivity Λm = κ/C. Kohlrausch's law: Λ°m = Σλ° (individual ion contributions)." },
      { heading: "Electrolysis", content: "Faraday's 1st law: m = Z×Q = (E/F)×Q. Z = E/F (electrochemical equivalent). F = 96485 C/mol. 2nd law: masses proportional to equivalent weights." },
    ],
    keyFormulas: [
      { label: "Nernst equation", formula: "E = E° – (0.0592/n) log Q (at 25°C)" },
      { label: "Gibbs energy from E_cell", formula: "ΔG° = –nFE°_cell" },
      { label: "Faraday's law", formula: "m = (M/nF) × Q = (M/nF) × It" },
      { label: "Relation K and E°", formula: "log K = nE°/0.0592" },
    ],
    keyPoints: ["At equilibrium: E_cell = 0, Q = K.", "Cathode in electrolytic cell: where reduction occurs (connected to –ve terminal of battery).", "Corrosion is an electrochemical process: Fe oxidized at anode, O₂ reduced at cathode."],
    hasSimulation: true,
    simulationDescription: "Electrochemical cell simulator — build galvanic/electrolytic cells, measure E_cell, see redox reactions.",
    sampleQuestions: [
      { question: "E°(Zn/Zn²⁺) = –0.76V, E°(Cu²⁺/Cu) = +0.34V. E°_cell = ?", options: ["1.10 V", "0.42 V", "–0.42 V", "–1.10 V"], answer: 0 },
      { question: "F = 96485 C/mol. Time to deposit 1 mol Cu²⁺ with 10A current:", options: ["19297 s", "9648.5 s", "48242.5 s", "96485 s"], answer: 0 },
      { question: "Kohlrausch's law is about:", options: ["Osmotic pressure", "Limiting molar conductivity", "Electrode potential", "Boiling point"], answer: 1 },
    ],
    prevChapterId: "chapter-02", nextChapterId: "chapter-04",
  },
  {
    chapterId: "chapter-04", order: 4,
    title: "Chemical Kinetics",
    objective: "Study rate of reaction, rate law, integrated rate equations, half-life, Arrhenius equation, and mechanisms.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Rate of Reaction", content: "Rate = –(1/a)d[A]/dt = (1/b)d[B]/dt. Average rate and instantaneous rate. Rate depends on concentration, temperature, surface area, catalyst." },
      { heading: "Rate Law and Order", content: "Rate = k[A]^m[B]^n. Order of reaction = m+n (experimentally determined, not from stoichiometry). Zero order: rate = k. First order: rate = k[A]. Second order: rate = k[A]²." },
      { heading: "Integrated Rate Equations", content: "Zero order: [A] = [A]₀ – kt; t½ = [A]₀/2k. First order: ln[A] = ln[A]₀ – kt; t½ = 0.693/k (constant!). Second order: 1/[A] = 1/[A]₀ + kt." },
      { heading: "Arrhenius Equation", content: "k = Ae^(–Ea/RT). ln k = ln A – Ea/RT. Ea: activation energy. ln(k₂/k₁) = (Ea/R)(1/T₁ – 1/T₂). ~10°C rise doubles rate (approximate rule)." },
    ],
    keyFormulas: [
      { label: "First order rate", formula: "k = (2.303/t) log([A]₀/[A])" },
      { label: "First order half-life", formula: "t½ = 0.693/k" },
      { label: "Arrhenius", formula: "k = A·e^(–Ea/RT)" },
      { label: "Temperature-rate relation", formula: "ln(k₂/k₁) = (Ea/R)(1/T₁ – 1/T₂)" },
    ],
    keyPoints: ["Half-life of first order reaction is independent of initial concentration.", "Molecularity = number of molecules in elementary step (always integer, max 3).", "Order of reaction can be zero, integer, or fraction — determined experimentally."],
    hasSimulation: true,
    simulationDescription: "Reaction kinetics simulator — plot concentration vs time for 0th, 1st, and 2nd order reactions.",
    sampleQuestions: [
      { question: "For first order reaction, t½ = 14 days. k = ?", options: ["0.0495 day⁻¹", "0.693 day⁻¹", "14 day⁻¹", "0.1 day⁻¹"], answer: 0 },
      { question: "Which factor does NOT affect rate constant k?", options: ["Temperature", "Catalyst", "Concentration", "Activation energy"], answer: 2 },
      { question: "Unit of rate constant for zero order reaction:", options: ["mol L⁻¹ s⁻¹", "L mol⁻¹ s⁻¹", "s⁻¹", "L² mol⁻² s⁻¹"], answer: 0 },
    ],
    prevChapterId: "chapter-03", nextChapterId: "chapter-05",
  },
  {
    chapterId: "chapter-05", order: 5,
    title: "Surface Chemistry",
    objective: "Study adsorption, catalysis, colloids, emulsions, and gels.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Adsorption", content: "Accumulation of substance on surface. Adsorbate: substance adsorbed. Adsorbent: surface. Physisorption (van der Waals, reversible, low heat) vs chemisorption (covalent, irreversible, high heat, monolayer)." },
      { heading: "Catalysis", content: "Catalyst increases rate without being consumed (increases rate in forward and backward direction equally). Homogeneous: same phase. Heterogeneous: different phase. Enzyme: biological catalyst." },
      { heading: "Colloids", content: "Colloidal particle size: 1-1000 nm. Tyndall effect: scattering of light by colloids. Brownian motion: random motion of colloidal particles. Zeta potential: charge on colloidal particle." },
      { heading: "Emulsions and Gels", content: "Emulsion: liquid dispersed in liquid (milk = fat in water = O/W emulsion). Gel: liquid dispersed in solid (jelly, cheese). Coagulation: electrolyte causes colloid to settle." },
    ],
    keyFormulas: [
      { label: "Freundlich adsorption", formula: "x/m = k·P^(1/n) (1/n < 1)" },
    ],
    keyPoints: ["Hardy-Schulze rule: higher valence of coagulating ion, more effective.", "Peptization: converting precipitate to colloid by adding electrolyte.", "Lyophilic colloids: gel in liquid (self-stabilizing); lyophobic: need stabilizer."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Tyndall effect is shown by:", options: ["True solution", "Colloid", "Suspension", "Both A and C"], answer: 1 },
      { question: "Catalyst increases rate by:", options: ["Increasing activation energy", "Decreasing activation energy", "Increasing T", "Decreasing T"], answer: 1 },
      { question: "Size of colloidal particles:", options: ["< 1 nm", "1-1000 nm", "> 1000 nm", "Exactly 500 nm"], answer: 1 },
    ],
    prevChapterId: "chapter-04", nextChapterId: "chapter-06",
  },
  {
    chapterId: "chapter-06", order: 6,
    title: "General Principles of Isolation of Elements",
    objective: "Study metallurgy — concentration, reduction, refining of metals, and thermodynamic principles.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Concentration of Ore", content: "Hydraulic washing (density difference), Froth flotation (sulphide ores — pine oil used), Magnetic separation (magnetic ores), Leaching (chemical treatment)." },
      { heading: "Thermodynamic Principles", content: "Ellingham diagram: plots ΔG° vs T for metal oxide formation. Metal with more negative ΔG° can reduce oxide of metal with less negative ΔG°." },
      { heading: "Reduction Methods", content: "Carbon reduction: C or CO as reducing agent (Fe, Sn, Pb, Zn). Self-reduction: Cu₂S+Cu₂O→Cu+SO₂. Hydrometallurgy: leaching+electrolysis (Cu, Ag, Au). Electrolytic reduction: Al, Na, Mg." },
      { heading: "Refining", content: "Distillation (volatile metals: Zn, Hg), Liquation (Sn), Electrolytic refining (Cu, Ag, Au, Al), Zone refining (ultra-pure Si, Ge for semiconductors), Vapour phase refining (Ni — Mond process; Ti — Van Arkel)." },
    ],
    keyFormulas: [],
    keyPoints: ["Al extracted by Hall-Héroult process (electrolysis of Al₂O₃ in molten cryolite).", "Thermite reduction: Al reduces Cr₂O₃ (used in welding rail joints).", "Blister copper: 98% pure Cu, contains blisters of SO₂."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Froth flotation is used for concentration of:", options: ["Oxide ores", "Sulphide ores", "Carbonate ores", "Native metal ores"], answer: 1 },
      { question: "Zone refining is used to obtain:", options: ["Ultra-pure metals/semiconductors", "Steel", "Crude metal", "Ore"], answer: 0 },
      { question: "Al is extracted by:", options: ["Carbon reduction", "Electrolysis of molten Al₂O₃", "Thermite process", "Self-reduction"], answer: 1 },
    ],
    prevChapterId: "chapter-05", nextChapterId: "chapter-07",
  },
  {
    chapterId: "chapter-07", order: 7,
    title: "The p-Block Elements (Part 2)",
    objective: "Study Groups 15–18 in detail — nitrogen family, oxygen family, halogens, and noble gases, their compounds and reactions.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Group 15: Nitrogen and Phosphorus Compounds", content: "HNO₃: prepared by Ostwald process (N₂→NO→NO₂→HNO₃). PCl₃ and PCl₅ are important halides. P₄O₁₀: powerful dehydrating agent." },
      { heading: "Group 16: Sulphur Compounds", content: "H₂SO₄ made by Contact process (S→SO₂→SO₃+H₂SO₄). SO₃ is absorbed in H₂SO₄ to give oleum. H₂SO₄ is viscous, high boiling, highly exothermic on dilution." },
      { heading: "Group 17: Interhalogen Compounds", content: "XX' type: ClF, BrF, BrCl etc. General formula: XX'ₙ (n=1,3,5,7). More reactive than halogens. F₂ forms maximum interhalogens (most reactive)." },
      { heading: "Group 18: Noble Gases", content: "He: lightest, used in balloons, cryogenic applications. Ne: neon lights. Ar: largest use (inert gas for welding). Kr, Xe: form compounds (XeF₂, XeF₄, XeF₆, XeO₃)." },
    ],
    keyFormulas: [],
    keyPoints: ["Ostwald process: 4NH₃ + 5O₂ → 4NO + 6H₂O (Pt catalyst, 800°C).", "Contact process: 2SO₂ + O₂ ⇌ 2SO₃ (V₂O₅ catalyst).", "XeF₂ structure: linear (3 lone pairs on Xe); XeF₄: square planar; XeF₆: distorted octahedral."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "HNO₃ is manufactured by:", options: ["Haber process", "Contact process", "Ostwald process", "Solvay process"], answer: 2 },
      { question: "Shape of XeF₄:", options: ["Tetrahedral", "Square planar", "Octahedral", "Linear"], answer: 1 },
      { question: "Most electronegative halogen:", options: ["Cl", "Br", "F", "I"], answer: 2 },
    ],
    prevChapterId: "chapter-06", nextChapterId: "chapter-08",
  },
  {
    chapterId: "chapter-08", order: 8,
    title: "The d and f Block Elements",
    objective: "Study transition metals (d-block) and inner transition metals (f-block) — properties, oxidation states, and compounds.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Transition Elements", content: "Elements with partly filled d-orbitals in ground state or common oxidation state. Properties: variable oxidation states (due to close energy of 3d and 4s), colored ions, paramagnetic, form complexes, catalytic activity." },
      { heading: "Important Compounds", content: "KMnO₄: purple, oxidizing agent (Mn changes from +7 to +2). K₂Cr₂O₇: orange, oxidizing agent (Cr changes from +6 to +3). Both used in titrimetry." },
      { heading: "Lanthanoids and Actinoids", content: "Lanthanoids (La to Lu): 4f filling. Actinoids (Ac to Lr): 5f filling. Lanthanoid contraction: steady decrease in size due to poor shielding by 4f electrons." },
    ],
    keyFormulas: [
      { label: "Spin-only magnetic moment", formula: "μ = √n(n+2) BM (n = unpaired electrons)" },
      { label: "KMnO₄ in acidic medium", formula: "MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O" },
    ],
    keyPoints: ["Fe has maximum number of unpaired electrons (4 in Fe²⁺, 5 in Fe³⁺) — highest magnetic moment.", "Zn, Cd, Hg are NOT transition metals (fully filled d orbitals in both element and ion).", "Lanthanoid contraction causes Zr and Hf to have very similar sizes — hard to separate."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Oxidation state of Cr in K₂Cr₂O₇:", options: ["+3", "+6", "+4", "+7"], answer: 1 },
      { question: "Magnetic moment of Fe³⁺ (5 unpaired electrons):", options: ["√24 BM", "√35 BM", "√48 BM", "√15 BM"], answer: 1 },
      { question: "Which transition metal is NOT a transition metal strictly?", options: ["Fe", "Zn", "Cu", "Mn"], answer: 1 },
    ],
    prevChapterId: "chapter-07", nextChapterId: "chapter-09",
  },
  {
    chapterId: "chapter-09", order: 9,
    title: "Coordination Compounds",
    objective: "Study coordination complexes, IUPAC nomenclature, isomerism, bonding theories (VBT, CFT).",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Terminology", content: "Central metal atom/ion + ligands (Lewis bases). Coordination number: number of sigma bonds from ligands to metal. Primary valence = oxidation state; secondary = coordination number." },
      { heading: "IUPAC Nomenclature", content: "Name ligands first (alphabetically), then metal with oxidation state. Anionic ligands: -ido/-ite/-ate suffix. Examples: [Co(NH₃)₆]³⁺ = hexaamminecobalt(III) cation." },
      { heading: "Isomerism", content: "Geometric: cis-trans in square planar and octahedral. Optical: mirror images (non-superimposable). Ionization, Linkage, Coordination, Solvate isomerism." },
      { heading: "Bonding Theories", content: "VBT: hybridization determines geometry. sp³ (tetrahedral), sp³d² (octahedral inner sphere), d²sp³ (octahedral outer sphere). CFT: d-orbital splitting by ligand field — Δ_oct (CFSE)." },
    ],
    keyFormulas: [
      { label: "EAN rule", formula: "EAN = Z – oxidation state + 2×(coordination number)" },
      { label: "Crystal field splitting", formula: "Δ_oct = 10Dq (magnitude depends on metal and ligands)" },
    ],
    keyPoints: ["Spectrochemical series (weak to strong field): I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < en < CN⁻ < CO.", "Strong field ligands (CO, CN⁻) cause large Δ — low spin complexes.", "Werner's theory: complex ions have primary (ionizable) and secondary (non-ionizable) valences."],
    hasSimulation: true,
    simulationDescription: "Crystal field theory visualizer — see d-orbital energy splitting for octahedral and tetrahedral complexes.",
    sampleQuestions: [
      { question: "IUPAC name of [Cu(NH₃)₄]²⁺:", options: ["Tetraamminecopper(II)", "Tetraaminecupric", "Cuprammonium", "Tetraamine copper"], answer: 0 },
      { question: "Coordination number of Pt in [PtCl₂(NH₃)₂]:", options: ["2", "4", "6", "3"], answer: 1 },
      { question: "Which complex shows optical isomerism?", options: ["[CoCl₂(en)]⁺", "[Co(en)₃]³⁺", "[CoCl₄]²⁻", "[CoF₆]³⁻"], answer: 1 },
    ],
    prevChapterId: "chapter-08", nextChapterId: "chapter-10",
  },
  {
    chapterId: "chapter-10", order: 10,
    title: "Haloalkanes and Haloarenes",
    objective: "Study nomenclature, physical and chemical properties, SN1/SN2 reactions of haloalkanes and haloarenes.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Types and Nomenclature", content: "Alkyl halide: R-X. Primary (1°), secondary (2°), tertiary (3°). IUPAC: halo-prefix + parent alkane. Aryl halides: X directly attached to benzene ring." },
      { heading: "Nucleophilic Substitution (SN)", content: "SN2: bimolecular, one step, inversion of configuration (Walden inversion), favored by 1° alkyl halides, strong nucleophile. SN1: unimolecular, two steps (forms carbocation), favored by 3° alkyl halides, retention/racemization." },
      { heading: "Elimination vs Substitution", content: "E2: bimolecular elimination (Zaitsev — major product = more substituted alkene). E1: via carbocation. Tertiary halides prefer elimination at high temp; substitution at low." },
      { heading: "Haloarenes", content: "C-X bond shorter and stronger in aryl halide (resonance). Aryl halides are less reactive than alkyl halides in nucleophilic substitution. Electron-withdrawing groups ortho/para to X activate haloarene." },
    ],
    keyFormulas: [],
    keyPoints: ["SN2 proceeds with Walden inversion (nucleophile attacks from back).", "SN1 forms racemic mixture (carbocation is planar).", "Good leaving groups: I⁻ > Br⁻ > Cl⁻ > F⁻ (in SN reactions)."],
    hasSimulation: true,
    simulationDescription: "SN1 vs SN2 reaction mechanism animator — step-by-step 3D visualization of nucleophilic substitution.",
    sampleQuestions: [
      { question: "Which undergoes SN2 fastest?", options: ["(CH₃)₃CCl", "(CH₃)₂CHCl", "CH₃CH₂Cl", "CH₃Cl"], answer: 3 },
      { question: "SN1 reaction gives:", options: ["Inverted product only", "Retention only", "Racemic mixture", "No reaction"], answer: 2 },
      { question: "Which is better leaving group in SN reactions?", options: ["F⁻", "Cl⁻", "Br⁻", "I⁻"], answer: 3 },
    ],
    prevChapterId: "chapter-09", nextChapterId: "chapter-11",
  },
  {
    chapterId: "chapter-11", order: 11,
    title: "Alcohols, Phenols and Ethers",
    objective: "Study preparation, properties, and reactions of alcohols, phenols, and ethers.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Alcohols", content: "R-OH. Primary, secondary, tertiary based on OH-bearing carbon. Preparation: hydration of alkenes, reduction of carbonyl compounds, Grignard reagent + carbonyl. Reactions: esterification, dehydration, oxidation, Lucas test." },
      { heading: "Phenols", content: "Ar-OH. More acidic than alcohols (pKa ~10) due to resonance stabilization of phenoxide. Reactions: electrophilic aromatic substitution (OH is ortho/para director), coupling, Kolbe reaction, Reimer-Tiemann." },
      { heading: "Ethers", content: "R-O-R'. Prepared by Williamson synthesis (RO⁻ + R'X → ROR'). Less reactive than alcohols. Cleavage by HI or HBr at high temperature." },
    ],
    keyFormulas: [],
    keyPoints: ["Lucas test: ZnCl₂+conc HCl. 3°→immediate turbidity; 2°→5 min; 1°→no reaction.", "Phenol is more acidic than water but less acidic than carboxylic acids.", "Williamson synthesis: best route to unsymmetrical ethers."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which is most acidic?", options: ["Ethanol", "Phenol", "Water", "Cyclohexanol"], answer: 1 },
      { question: "Alcohols react with Na to give:", options: ["H₂ gas", "O₂ gas", "NaOH", "CO₂"], answer: 0 },
      { question: "Williamson synthesis makes:", options: ["Alcohols", "Ethers", "Aldehydes", "Alkenes"], answer: 1 },
    ],
    prevChapterId: "chapter-10", nextChapterId: "chapter-12",
  },
  {
    chapterId: "chapter-12", order: 12,
    title: "Aldehydes, Ketones and Carboxylic Acids",
    objective: "Study nucleophilic addition to carbonyl, oxidation, Aldol condensation, and carboxylic acid reactions.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Aldehydes and Ketones", content: "Aldehydes (RCHO): more reactive than ketones. Nucleophilic addition to C=O: HCN, Grignard, NaBH₄. Aldol condensation: α-H present + NaOH → β-hydroxy carbonyl → α,β-unsaturated." },
      { heading: "Distinction Tests", content: "Tollen's test (silver mirror): aldehydes only. Fehling's test (blue → brick red ppt): aliphatic aldehydes only. Iodoform test (CHI₃ yellow ppt): methyl ketones + CH₃CHO + ethanol." },
      { heading: "Carboxylic Acids", content: "R-COOH. Most acidic common organic compound. Reactions: esterification (R-OH + HOOCR' ⇌ RCOOR' + H₂O, conc H₂SO₄), acyl chloride formation (SOCl₂), anhydride, amide, reduction (LiAlH₄)." },
    ],
    keyFormulas: [
      { label: "Esterification (Fischer)", formula: "RCOOH + R'OH ⇌ RCOOR' + H₂O (acid catalyst)" },
    ],
    keyPoints: ["Carboxylic acids are more acidic than phenols due to resonance stabilization of carboxylate ion.", "Benzaldehyde doesn't give Fehling's but gives Tollen's test.", "Claisen condensation: ester + ester → β-ketoester (for esters with α-H)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Tollen's test is positive for:", options: ["Ketone only", "Aldehyde only", "Both ketone and aldehyde", "Carboxylic acid"], answer: 1 },
      { question: "Iodoform test is NOT given by:", options: ["Acetone", "Ethanol", "Acetaldehyde", "Diethyl ketone"], answer: 3 },
      { question: "Reaction of carboxylic acid with alcohol gives:", options: ["Ester", "Aldehyde", "Ketone", "Ether"], answer: 0 },
    ],
    prevChapterId: "chapter-11", nextChapterId: "chapter-13",
  },
  {
    chapterId: "chapter-13", order: 13,
    title: "Amines",
    objective: "Study classification, nomenclature, basicity, preparation, and reactions of amines.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Classification", content: "Primary (1°): R-NH₂. Secondary (2°): R₂NH. Tertiary (3°): R₃N. Quaternary salt: R₄N⁺X⁻. Aryl amines (aniline C₆H₅NH₂) are less basic than alkyl amines." },
      { heading: "Basicity", content: "Basicity order: alkyl amines > NH₃ > aryl amines (lone pair delocalized in ring reduces basicity). In aqueous solution: secondary > primary > tertiary (due to solvation)." },
      { heading: "Reactions", content: "With acids: form ammonium salts. Acylation (with RCOCl/Ac₂O): NHCOR. Carbylamine reaction: primary amine + CHCl₃ + KOH → isocyanide (foul smell — test for primary amine). Diazonium salt formation (primary aromatic amine + NaNO₂ + HCl at 0-5°C)." },
    ],
    keyFormulas: [],
    keyPoints: ["Basicity: CH₃NH₂ (pKb 3.4) > C₂H₅NH₂ > NH₃ (pKb 4.7) > C₆H₅NH₂ (pKb 9.4).", "Diazonium salts undergo coupling reactions with phenol/aniline to form azo dyes.", "Gabriel phthalimide synthesis: specific for primary amines."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which amine is most basic in water?", options: ["Primary alkyl amine", "Secondary alkyl amine", "Tertiary alkyl amine", "Aryl amine"], answer: 1 },
      { question: "Carbylamine reaction is a test for:", options: ["Secondary amine", "Tertiary amine", "Primary amine", "All amines"], answer: 2 },
      { question: "Aniline is less basic than methylamine because:", options: ["Lone pair is delocalized into ring", "N-H bond is weaker", "N has more electronegativity", "Steric effect"], answer: 0 },
    ],
    prevChapterId: "chapter-12", nextChapterId: "chapter-14",
  },
  {
    chapterId: "chapter-14", order: 14,
    title: "Biomolecules",
    objective: "Study carbohydrates, proteins, nucleic acids, vitamins, hormones, and enzymes.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Carbohydrates", content: "Monosaccharides (glucose, fructose), disaccharides (sucrose, lactose, maltose), polysaccharides (starch, cellulose, glycogen). Glucose: C₆H₁₂O₆, open chain (Fischer) or cyclic (Haworth). Anomers: α and β forms." },
      { heading: "Proteins", content: "Polymers of amino acids linked by peptide bonds (–CO–NH–). Primary structure: amino acid sequence. Secondary: α-helix or β-sheet (H-bonds). Tertiary: 3D folding. Quaternary: multiple subunits." },
      { heading: "Nucleic Acids", content: "DNA: double helix, deoxyribose sugar, A-T and G-C base pairs. RNA: single strand, ribose, A-U and G-C. Nucleotide = base + sugar + phosphate." },
      { heading: "Vitamins, Enzymes, Hormones", content: "Vitamins: fat-soluble (A,D,E,K) and water-soluble (B,C). Enzymes: biological catalysts (protein). Hormones: chemical messengers (e.g., insulin, adrenaline)." },
    ],
    keyFormulas: [],
    keyPoints: ["Sucrose (non-reducing): glucose + fructose; Lactose (reducing): glucose + galactose.", "Iodine turns starch blue-black (test for starch).", "Denaturation: loss of 3D structure of protein (by heat, acid, etc.) — reversible (renaturation) or irreversible."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which is a non-reducing sugar?", options: ["Glucose", "Fructose", "Sucrose", "Maltose"], answer: 2 },
      { question: "DNA has which bases?", options: ["A,U,G,C", "A,T,G,C", "A,T,G,U", "A,B,G,C"], answer: 1 },
      { question: "Peptide bond is formed between:", options: ["Two –COOH groups", "–COOH and –NH₂ groups", "Two –NH₂ groups", "–OH and –NH₂ groups"], answer: 1 },
    ],
    prevChapterId: "chapter-13", nextChapterId: "chapter-15",
  },
  {
    chapterId: "chapter-15", order: 15,
    title: "Polymers",
    objective: "Study types of polymerization, classification of polymers, and commercially important polymers.",
    durationLabel: "2 days",
    theoryPoints: [
      { heading: "Types of Polymerization", content: "Addition polymerization: monomers with double bonds add without byproduct (polyethylene, polystyrene, PVC, Teflon). Condensation polymerization: monomers with two functional groups, byproduct (nylon, polyester, Bakelite)." },
      { heading: "Classification", content: "By origin: natural (cellulose, rubber), semi-synthetic, synthetic. By structure: linear, branched, cross-linked. By properties: thermoplastic (reshape on heating) vs thermoset (do not soften). By use: elastomers, fibers, plastics." },
      { heading: "Important Polymers", content: "Nylon-6,6: hexamethylenediamine + adipic acid. Polyester (Terylene/Dacron): ethylene glycol + terephthalic acid. Bakelite: phenol + formaldehyde. Natural rubber: polyisoprene (cis); Neoprene: polychloroprene." },
    ],
    keyFormulas: [],
    keyPoints: ["Vulcanization of rubber: addition of sulphur — improves strength and elasticity.", "PVC (polyvinyl chloride): used in pipes, floor tiles; plasticizer added to make it flexible.", "Biodegradable polymers: PHBV (polyhydroxybutyrate-co-hydroxyvalerate)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Nylon is formed by:", options: ["Addition polymerization", "Condensation polymerization", "Free radical polymerization", "Cationic polymerization"], answer: 1 },
      { question: "Natural rubber is polymer of:", options: ["Isoprene", "Styrene", "Ethylene", "Propylene"], answer: 0 },
      { question: "Thermoplastic can be reshaped because:", options: ["Cross-linked structure", "No cross-linking", "High melting point", "Crystalline structure"], answer: 1 },
    ],
    prevChapterId: "chapter-14", nextChapterId: "chapter-16",
  },
  {
    chapterId: "chapter-16", order: 16,
    title: "Chemistry in Everyday Life",
    objective: "Study drugs, food additives, detergents, antacids, antiseptics, and chemicals in agriculture.",
    durationLabel: "2 days",
    theoryPoints: [
      { heading: "Drugs and Their Classification", content: "Analgesics (pain relief): aspirin, paracetamol, morphine. Antibiotics: broad-spectrum (ampicillin), narrow (penicillin G). Antiseptics: on wounds (dettol, savlon). Disinfectants: non-living surfaces (phenol)." },
      { heading: "Drug-Receptor Interaction", content: "Drugs bind to active site of enzymes or receptors (competitive inhibition). Agonists: mimic natural messenger. Antagonists: block receptor." },
      { heading: "Food Additives and Detergents", content: "Preservatives: sodium benzoate, SO₂. Artificial sweeteners: saccharin, aspartame (phenylketonuria patients should avoid). Detergents: sulfonate salts — work in hard water (unlike soaps)." },
    ],
    keyFormulas: [],
    keyPoints: ["Aspirin: analgesic, antipyretic, anti-inflammatory; inhibits prostaglandin synthesis.", "Soaps do not work in hard water (Ca²⁺, Mg²⁺ form scum). Detergents do.", "Broad-spectrum antibiotics kill many bacteria; narrow-spectrum target specific bacteria."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Aspirin belongs to which class of drugs?", options: ["Antibiotic", "Antiseptic", "Analgesic", "Antacid"], answer: 2 },
      { question: "Detergents work in hard water because:", options: ["They form foam", "They are ionic", "Ca/Mg salts of sulfonates are soluble", "They are cheaper"], answer: 2 },
      { question: "Which artificial sweetener is avoided by phenylketonurics?", options: ["Saccharin", "Aspartame", "Sucralose", "Stevia"], answer: 1 },
    ],
    prevChapterId: "chapter-15", nextChapterId: undefined,
  },
];
