/**
 * @file lib/content/class11-physics.ts
 * @description NCERT-aligned Class 11 Physics curriculum content
 * Every chapter matches NCERT Class 11 Physics (2025-26 edition)
 */

import type { ContentChapter } from "./class9-mathematics";

export const CLASS_11_PHYSICS_CHAPTERS: ContentChapter[] = [
  {
    chapterId: "chapter-01", order: 1,
    title: "Physical World",
    objective: "Understand the scope of physics, fundamental forces, and the nature of physical laws.",
    durationLabel: "1 day",
    theoryPoints: [
      { heading: "Scope of Physics", content: "Physics is the most fundamental science, dealing with matter, energy, space, and time. It underpins all other natural sciences." },
      { heading: "Four Fundamental Forces", content: "Gravitational force, Electromagnetic force, Strong nuclear force, Weak nuclear force. Gravitational is the weakest; strong nuclear is the strongest." },
      { heading: "Physical Laws", content: "Laws are concise, universal, and mathematically expressible. Examples: Newton's laws, Laws of thermodynamics, Maxwell's equations." },
    ],
    keyFormulas: [],
    keyPoints: ["Physics seeks to understand the universe from elementary particles to cosmological structures.", "Unification of forces is a major goal of modern physics."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which is the strongest fundamental force?", options: ["Gravitational", "Electromagnetic", "Strong nuclear", "Weak nuclear"], answer: 2 },
      { question: "Which branch of physics deals with very small particles?", options: ["Astrophysics", "Quantum mechanics", "Thermodynamics", "Optics"], answer: 1 },
      { question: "Range of strong nuclear force is:", options: ["Infinite", "~10⁻¹⁵ m", "~10⁻¹⁰ m", "~10⁻² m"], answer: 1 },
    ],
    prevChapterId: undefined, nextChapterId: "chapter-02",
  },
  {
    chapterId: "chapter-02", order: 2,
    title: "Units and Measurements",
    objective: "Understand SI units, dimensions, significant figures, and errors in measurement.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "SI Units", content: "The International System of Units has 7 base units: metre (m), kilogram (kg), second (s), ampere (A), kelvin (K), mole (mol), candela (cd)." },
      { heading: "Dimensional Analysis", content: "Every physical quantity has dimensions in terms of M (mass), L (length), T (time), A (current), θ (temperature), N (amount), J (luminosity)." },
      { heading: "Significant Figures", content: "Significant figures indicate the precision of a measurement. Rules: Non-zero digits are significant; zeros between non-zeros are significant; trailing zeros after decimal are significant." },
      { heading: "Errors in Measurement", content: "Absolute error, Relative error, Percentage error. Systematic errors are consistent; random errors are unpredictable." },
    ],
    keyFormulas: [
      { label: "Absolute error", formula: "Δa = |aₘₑₐₙ – aᵢ|" },
      { label: "Relative error", formula: "Δa / aₘₑₐₙ" },
      { label: "Percentage error", formula: "(Δa / aₘₑₐₙ) × 100%" },
    ],
    keyPoints: ["Dimensions can be used to check the correctness of equations (dimensional analysis).", "Significant figures represent measurement precision.", "Systematic errors can be corrected; random errors can be minimized by averaging."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "SI unit of temperature is:", options: ["Celsius", "Fahrenheit", "Kelvin", "Joule"], answer: 2 },
      { question: "Dimension of force is:", options: ["MLT⁻²", "ML²T⁻²", "MLT⁻¹", "ML⁻¹T⁻²"], answer: 0 },
      { question: "Number of significant figures in 0.00580 is:", options: ["5", "3", "2", "6"], answer: 1 },
    ],
    prevChapterId: "chapter-01", nextChapterId: "chapter-03",
  },
  {
    chapterId: "chapter-03", order: 3,
    title: "Motion in a Straight Line",
    objective: "Study kinematics — position, velocity, acceleration, and equations of motion for straight-line motion.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Position, Displacement, Distance", content: "Position is location relative to a reference point. Displacement = change in position (vector). Distance = total path length (scalar)." },
      { heading: "Speed and Velocity", content: "Speed = distance/time (scalar). Velocity = displacement/time (vector). Instantaneous velocity = dx/dt." },
      { heading: "Acceleration", content: "Acceleration = rate of change of velocity = dv/dt. Uniform acceleration: constant a. Average acceleration = Δv/Δt." },
      { heading: "Equations of Motion", content: "For uniform acceleration: v = u + at; s = ut + ½at²; v² = u² + 2as; s = (u+v)t/2." },
    ],
    keyFormulas: [
      { label: "v = u + at", formula: "Final velocity from initial velocity and acceleration" },
      { label: "s = ut + ½at²", formula: "Displacement under uniform acceleration" },
      { label: "v² = u² + 2as", formula: "Velocity-displacement relation" },
      { label: "sₙ = u + a(2n–1)/2", formula: "Displacement in nth second" },
    ],
    keyPoints: ["Velocity and displacement are vectors; speed and distance are scalars.", "On a v-t graph, area under the curve = displacement; slope = acceleration.", "Free fall: a = g = 9.8 m/s² downward."],
    hasSimulation: true,
    simulationDescription: "Kinematics simulator — set initial velocity and acceleration to visualize motion, v-t graph, and x-t graph in real time.",
    sampleQuestions: [
      { question: "A car starts from rest and accelerates at 2 m/s². Velocity after 5 s:", options: ["5 m/s", "10 m/s", "20 m/s", "25 m/s"], answer: 1 },
      { question: "A ball is thrown up with 20 m/s. Time to reach max height (g=10):", options: ["1 s", "2 s", "4 s", "5 s"], answer: 1 },
      { question: "Slope of x-t graph gives:", options: ["acceleration", "velocity", "displacement", "force"], answer: 1 },
    ],
    prevChapterId: "chapter-02", nextChapterId: "chapter-04",
  },
  {
    chapterId: "chapter-04", order: 4,
    title: "Motion in a Plane",
    objective: "Study vectors, projectile motion, uniform circular motion, and relative velocity in two dimensions.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Vectors and Scalars", content: "Scalars have magnitude only (speed, mass). Vectors have magnitude and direction (velocity, force). Vector addition: triangle/parallelogram law." },
      { heading: "Projectile Motion", content: "Horizontal: uniform velocity (no acceleration). Vertical: free fall (a = g). Path is parabolic. Time of flight T = 2u sinθ/g; Range R = u² sin2θ/g; Max height H = u² sin²θ/2g." },
      { heading: "Uniform Circular Motion", content: "Object moves in a circle at constant speed. Centripetal acceleration a = v²/r directed towards centre. Period T = 2πr/v." },
      { heading: "Relative Velocity", content: "Velocity of A relative to B: v_AB = v_A – v_B." },
    ],
    keyFormulas: [
      { label: "Projectile range", formula: "R = u² sin2θ / g" },
      { label: "Max height", formula: "H = u² sin²θ / 2g" },
      { label: "Time of flight", formula: "T = 2u sinθ / g" },
      { label: "Centripetal acceleration", formula: "aₓ = v²/r = ω²r" },
    ],
    keyPoints: ["Maximum range occurs at θ = 45°.", "Centripetal force is not a new force; it is provided by existing forces (tension, gravity, normal, friction).", "In circular motion, speed is constant but velocity (direction) changes."],
    hasSimulation: true,
    simulationDescription: "Projectile motion simulator — set angle and speed to visualize trajectory, time of flight, and range.",
    sampleQuestions: [
      { question: "For maximum projectile range, launch angle = ?", options: ["30°", "45°", "60°", "90°"], answer: 1 },
      { question: "Centripetal acceleration of a particle in circular motion is directed:", options: ["Along velocity", "Away from centre", "Towards centre", "Tangentially"], answer: 2 },
      { question: "Horizontal component of velocity during projectile motion:", options: ["Increases", "Decreases", "Remains constant", "Becomes zero at top"], answer: 2 },
    ],
    prevChapterId: "chapter-03", nextChapterId: "chapter-05",
  },
  {
    chapterId: "chapter-05", order: 5,
    title: "Laws of Motion",
    objective: "Understand Newton's three laws of motion, friction, and applications to real-world problems.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Newton's First Law (Inertia)", content: "A body remains at rest or in uniform motion unless acted upon by an external force. This is the law of inertia." },
      { heading: "Newton's Second Law", content: "Net force = mass × acceleration (F = ma). The direction of acceleration is the same as the net force." },
      { heading: "Newton's Third Law", content: "For every action, there is an equal and opposite reaction. Forces always occur in pairs on different objects." },
      { heading: "Friction", content: "Static friction (maximum = μₛN) opposes impending motion. Kinetic friction (= μₖN) opposes sliding motion. Generally μₛ > μₖ." },
    ],
    keyFormulas: [
      { label: "Newton's 2nd Law", formula: "F = ma (or F = dp/dt)" },
      { label: "Static friction (max)", formula: "fₛ = μₛ × N" },
      { label: "Kinetic friction", formula: "fₖ = μₖ × N" },
      { label: "Normal force on incline", formula: "N = mg cosθ" },
    ],
    keyPoints: ["Inertia is the tendency of a body to resist change in state of motion.", "Impulse = FΔt = change in momentum.", "On a frictionless surface, the only horizontal force is from an applied force or tension."],
    hasSimulation: true,
    simulationDescription: "Newton's laws simulator — apply forces to objects and observe acceleration, friction effects, and reaction forces.",
    sampleQuestions: [
      { question: "A 5 kg block accelerates at 3 m/s². Net force = ?", options: ["15 N", "1.67 N", "8 N", "5 N"], answer: 0 },
      { question: "Normal reaction on a block on horizontal surface is:", options: ["Less than mg", "Equal to mg", "Greater than mg", "Zero"], answer: 1 },
      { question: "μₛ = 0.5 for a 10 kg block. Max static friction (g=10) = ?", options: ["5 N", "50 N", "100 N", "10 N"], answer: 1 },
    ],
    prevChapterId: "chapter-04", nextChapterId: "chapter-06",
  },
  {
    chapterId: "chapter-06", order: 6,
    title: "Work, Energy and Power",
    objective: "Understand work, kinetic energy, potential energy, conservation of energy, power, and collisions.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Work", content: "W = F·d·cosθ where θ is the angle between force and displacement. Work is a scalar. W > 0 if force and displacement are in the same direction." },
      { heading: "Kinetic Energy", content: "KE = ½mv². The work-energy theorem: W_net = ΔKE." },
      { heading: "Potential Energy", content: "Gravitational PE = mgh. Elastic PE = ½kx². PE is stored energy due to position or configuration." },
      { heading: "Conservation of Energy", content: "KE + PE = constant in a conservative system (no friction). Energy transforms between forms but total is conserved." },
      { heading: "Power", content: "Power = Work/Time = F·v. SI unit: Watt (W) = J/s. 1 horsepower = 746 W." },
    ],
    keyFormulas: [
      { label: "Work", formula: "W = Fd cosθ" },
      { label: "Kinetic Energy", formula: "KE = ½mv²" },
      { label: "Work-Energy Theorem", formula: "W_net = ΔKE = ½mv₂² – ½mv₁²" },
      { label: "Power", formula: "P = W/t = F·v" },
      { label: "Gravitational PE", formula: "U = mgh" },
    ],
    keyPoints: ["Work done by gravity is –mgh when object moves up (against gravity).", "Elastic collisions conserve both KE and momentum; inelastic only conserve momentum.", "Power = rate of doing work."],
    hasSimulation: true,
    simulationDescription: "Energy conservation simulator — roller coaster showing KE and PE interchange as ball rolls along a track.",
    sampleQuestions: [
      { question: "A 2 kg ball moving at 3 m/s has KE = ?", options: ["6 J", "9 J", "18 J", "3 J"], answer: 1 },
      { question: "Work done by gravity on a 1 kg object falling 10 m (g=10) is:", options: ["–100 J", "100 J", "10 J", "–10 J"], answer: 1 },
      { question: "Power of a machine doing 500 J in 10 s:", options: ["50 W", "500 W", "5000 W", "5 W"], answer: 0 },
    ],
    prevChapterId: "chapter-05", nextChapterId: "chapter-07",
  },
  {
    chapterId: "chapter-07", order: 7,
    title: "System of Particles and Rotational Motion",
    objective: "Understand centre of mass, torque, angular momentum, and moment of inertia for rotating bodies.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Centre of Mass", content: "The point where the entire mass of a system can be assumed to be concentrated. For a two-body system: x_cm = (m₁x₁ + m₂x₂)/(m₁+m₂)." },
      { heading: "Torque", content: "Torque τ = r × F = rF sinθ. It is the rotational equivalent of force. Unit: N·m." },
      { heading: "Moment of Inertia", content: "I = Σmᵢrᵢ². It is the rotational equivalent of mass. Depends on mass distribution and axis of rotation." },
      { heading: "Angular Momentum", content: "L = I·ω = r × p. Conservation: if no external torque, L = constant (e.g., spinning skater)." },
    ],
    keyFormulas: [
      { label: "Centre of mass", formula: "x_cm = Σmᵢxᵢ / Σmᵢ" },
      { label: "Torque", formula: "τ = r × F = Iα" },
      { label: "Rotational KE", formula: "KE = ½Iω²" },
      { label: "Angular momentum", formula: "L = Iω = mvr (for circular motion)" },
    ],
    keyPoints: ["The CM of a uniform body is at its geometric centre.", "I for solid sphere = 2/5 MR²; for ring = MR²; for disk = ½MR².", "Angular momentum is conserved when net external torque = 0."],
    hasSimulation: true,
    simulationDescription: "Moment of inertia visualizer — compare rotation of different shaped objects under the same torque.",
    sampleQuestions: [
      { question: "Torque τ if F=10N, r=2m, θ=90° is:", options: ["5 N·m", "20 N·m", "10 N·m", "0"], answer: 1 },
      { question: "Moment of inertia of a ring about central axis:", options: ["MR²/2", "MR²", "2MR²/5", "2MR²"], answer: 1 },
      { question: "A skater pulls arms in and spins faster. This demonstrates conservation of:", options: ["Energy", "Momentum", "Angular momentum", "Force"], answer: 2 },
    ],
    prevChapterId: "chapter-06", nextChapterId: "chapter-08",
  },
  {
    chapterId: "chapter-08", order: 8,
    title: "Gravitation",
    objective: "Study Newton's law of gravitation, gravitational field, potential, escape velocity, and orbital mechanics.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Newton's Law of Gravitation", content: "F = Gm₁m₂/r² where G = 6.674×10⁻¹¹ N·m²/kg². Attractive force between any two masses." },
      { heading: "Gravitational Field", content: "g = GM/r² at distance r from a mass M. On Earth's surface: g ≈ 9.8 m/s²." },
      { heading: "Escape Velocity", content: "Minimum velocity to escape a planet's gravity: vₑ = √(2GM/R) = √(2gR). For Earth: vₑ ≈ 11.2 km/s." },
      { heading: "Satellites and Orbital Velocity", content: "Orbital velocity: v₀ = √(GM/r) = √(gR²/r). Time period: T = 2πr/v₀ = 2π√(r³/GM). Kepler's 3rd law: T² ∝ r³." },
    ],
    keyFormulas: [
      { label: "Gravitational force", formula: "F = Gm₁m₂/r²" },
      { label: "Gravitational acceleration", formula: "g = GM/R²" },
      { label: "Escape velocity", formula: "vₑ = √(2gR) = √(2GM/R)" },
      { label: "Orbital velocity", formula: "v₀ = √(GM/r)" },
      { label: "Kepler's 3rd law", formula: "T² ∝ r³" },
    ],
    keyPoints: ["G is a universal constant; g varies with altitude and latitude.", "Geostationary satellite is at ~36,000 km with T = 24 h.", "Gravitational PE = –GMm/r (negative because gravity is attractive)."],
    hasSimulation: true,
    simulationDescription: "Solar system orbital simulator — visualize Kepler's laws with planet orbits and gravitational fields.",
    sampleQuestions: [
      { question: "Escape velocity from Earth (g=10, R=6400 km) is approximately:", options: ["7.9 km/s", "11.2 km/s", "9.8 km/s", "3 km/s"], answer: 1 },
      { question: "If distance from Earth's centre doubles, g becomes:", options: ["g/2", "g/4", "2g", "4g"], answer: 1 },
      { question: "Kepler's 3rd law states T² is proportional to:", options: ["r", "r²", "r³", "r⁴"], answer: 2 },
    ],
    prevChapterId: "chapter-07", nextChapterId: "chapter-09",
  },
  {
    chapterId: "chapter-09", order: 9,
    title: "Mechanical Properties of Solids",
    objective: "Understand stress, strain, elastic moduli (Young's, Bulk, Shear), and Hooke's Law.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Stress and Strain", content: "Stress = Force/Area (unit: Pa). Strain = Change in dimension/Original dimension (dimensionless). Hooke's Law: Stress ∝ Strain within elastic limit." },
      { heading: "Elastic Moduli", content: "Young's Modulus Y = Longitudinal stress / Longitudinal strain. Bulk Modulus K = –P / (ΔV/V). Shear Modulus G = Shear stress / Shear strain." },
    ],
    keyFormulas: [
      { label: "Stress", formula: "σ = F/A" },
      { label: "Strain", formula: "ε = ΔL/L" },
      { label: "Young's Modulus", formula: "Y = (F/A)/(ΔL/L) = FL/AΔL" },
      { label: "Bulk Modulus", formula: "K = –P/(ΔV/V)" },
    ],
    keyPoints: ["Elastic limit: the maximum stress within which a material returns to its original shape.", "Young's modulus of steel is higher than rubber, so steel is stiffer.", "Poisson's ratio σ = lateral strain / longitudinal strain."],
    hasSimulation: true,
    simulationDescription: "Stress-strain curve visualizer — see elastic and plastic regions, yield point, and breaking point.",
    sampleQuestions: [
      { question: "A wire of length 2m stretches by 1mm under load. Strain = ?", options: ["0.5", "0.005", "0.0005", "5"], answer: 2 },
      { question: "SI unit of stress:", options: ["N/m", "Pa", "J/m", "N·m"], answer: 1 },
      { question: "Hooke's Law is valid within:", options: ["Breaking point", "Elastic limit", "Plastic region", "Yield point"], answer: 1 },
    ],
    prevChapterId: "chapter-08", nextChapterId: "chapter-10",
  },
  {
    chapterId: "chapter-10", order: 10,
    title: "Mechanical Properties of Fluids",
    objective: "Study pressure, buoyancy, surface tension, viscosity, and Bernoulli's theorem.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Pressure in Fluids", content: "Pressure P = F/A = ρgh at depth h. Pascal's law: pressure applied at any point in a confined fluid is transmitted undiminished." },
      { heading: "Buoyancy (Archimedes' Principle)", content: "Buoyant force = weight of displaced fluid = ρ_fluid × V_submerged × g." },
      { heading: "Surface Tension", content: "Cohesive force between liquid molecules creates a surface film. Surface tension T = F/L. Excess pressure inside a bubble: 4T/r (soap bubble); 2T/r (spherical drop)." },
      { heading: "Viscosity and Stokes' Law", content: "Viscosity η is the resistance to flow. Stokes' law: drag force on sphere F = 6πηrv. Terminal velocity vₜ = 2r²(ρ–σ)g/9η." },
      { heading: "Bernoulli's Theorem", content: "P + ½ρv² + ρgh = constant along a streamline (energy conservation in fluid flow)." },
    ],
    keyFormulas: [
      { label: "Pressure at depth h", formula: "P = P₀ + ρgh" },
      { label: "Bernoulli's equation", formula: "P + ½ρv² + ρgh = const" },
      { label: "Continuity equation", formula: "A₁v₁ = A₂v₂" },
      { label: "Terminal velocity", formula: "vₜ = 2r²(ρ–σ)g / 9η" },
    ],
    keyPoints: ["In a horizontal pipe, higher velocity means lower pressure (Bernoulli).", "An object floats if its density < fluid density.", "Surface tension causes capillary rise: h = 2T cosθ / (ρgr)."],
    hasSimulation: true,
    simulationDescription: "Fluid flow and Bernoulli's principle simulator — pipe cross-section changes and pressure-velocity relationship.",
    sampleQuestions: [
      { question: "Pressure at 10m depth in water (ρ=1000 kg/m³, g=10):", options: ["10 Pa", "100 Pa", "100,000 Pa", "10,000 Pa"], answer: 2 },
      { question: "Bernoulli's theorem is based on:", options: ["Mass conservation", "Energy conservation", "Momentum conservation", "Newton's 3rd law"], answer: 1 },
      { question: "Buoyant force on a 0.5 m³ object in water (ρ_w=1000 kg/m³, g=10):", options: ["5000 N", "500 N", "50 N", "5 N"], answer: 0 },
    ],
    prevChapterId: "chapter-09", nextChapterId: "chapter-11",
  },
  {
    chapterId: "chapter-11", order: 11,
    title: "Thermal Properties of Matter",
    objective: "Study temperature scales, thermal expansion, specific heat, and heat transfer mechanisms.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Temperature Scales", content: "Celsius (°C), Fahrenheit (°F), Kelvin (K). Conversions: K = °C + 273.15; °F = (9/5)°C + 32." },
      { heading: "Thermal Expansion", content: "Linear: ΔL = αLΔT. Area: ΔA = 2αAΔT. Volume: ΔV = γVΔT where γ = 3α." },
      { heading: "Specific Heat and Calorimetry", content: "Q = mcΔT where m = mass, c = specific heat. Calorimetry: heat lost = heat gained for isolated systems." },
      { heading: "Heat Transfer", content: "Conduction: Q/t = kA(T₁–T₂)/d. Convection: heat by fluid movement. Radiation: Stefan-Boltzmann law: P = σAT⁴ (σ = 5.67×10⁻⁸ W/m²·K⁴)." },
    ],
    keyFormulas: [
      { label: "Linear expansion", formula: "ΔL = αL₀ΔT" },
      { label: "Heat", formula: "Q = mcΔT" },
      { label: "Conduction rate", formula: "H = kA(T₁–T₂)/d" },
      { label: "Stefan-Boltzmann law", formula: "P = σAT⁴" },
    ],
    keyPoints: ["Latent heat: Q = mL (no temperature change during phase transition).", "Anomalous expansion of water: water is densest at 4°C.", "Newton's law of cooling: rate of heat loss ∝ temperature difference with surroundings."],
    hasSimulation: true,
    simulationDescription: "Thermal expansion simulator — visualize linear, area, and volume expansion of materials with temperature change.",
    sampleQuestions: [
      { question: "0°C = ? K", options: ["100 K", "273 K", "373 K", "0 K"], answer: 1 },
      { question: "Heat needed to raise 2 kg of water by 10°C (c=4200 J/kg·K):", options: ["84,000 J", "8,400 J", "840 J", "420 J"], answer: 0 },
      { question: "Heat transfer through vacuum occurs by:", options: ["Conduction", "Convection", "Radiation", "None"], answer: 2 },
    ],
    prevChapterId: "chapter-10", nextChapterId: "chapter-12",
  },
  {
    chapterId: "chapter-12", order: 12,
    title: "Thermodynamics",
    objective: "Understand the four laws of thermodynamics, heat engines, refrigerators, and entropy.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Thermodynamic Systems", content: "Open system: exchanges both energy and matter. Closed: only energy. Isolated: neither. State variables: P, V, T, n." },
      { heading: "First Law of Thermodynamics", content: "ΔU = Q – W. Internal energy increases when heat is absorbed and decreases when work is done by the system." },
      { heading: "Thermodynamic Processes", content: "Isothermal (T=const): ΔU=0, Q=W. Adiabatic (Q=0): W=–ΔU. Isobaric (P=const): Q=nCₚΔT. Isochoric (V=const): W=0, Q=ΔU." },
      { heading: "Second Law and Entropy", content: "Heat cannot flow spontaneously from cold to hot (Clausius). No engine converts 100% heat to work (Kelvin-Planck). Entropy S measures disorder; ΔS ≥ 0 for isolated systems." },
      { heading: "Carnot Engine", content: "The most efficient heat engine: η = 1 – T₂/T₁ where T₁ is source and T₂ is sink temperature (in K)." },
    ],
    keyFormulas: [
      { label: "First Law", formula: "ΔU = Q – W" },
      { label: "Work done by gas (isobaric)", formula: "W = PΔV = nRΔT" },
      { label: "Carnot efficiency", formula: "η = 1 – T₂/T₁ = (T₁–T₂)/T₁" },
      { label: "Entropy change", formula: "ΔS = Q/T (reversible process)" },
    ],
    keyPoints: ["Zeroth law: If A=B and B=C in thermal equilibrium, then A=C.", "Third law: Entropy of a perfect crystal at 0 K is zero.", "COP of refrigerator = Q₂/W = T₂/(T₁–T₂)."],
    hasSimulation: true,
    simulationDescription: "PV diagram animator — visualize isothermal, adiabatic, isobaric, and isochoric processes on a PV diagram.",
    sampleQuestions: [
      { question: "In an isothermal process for ideal gas, ΔU =", options: ["Q", "W", "0", "Q+W"], answer: 2 },
      { question: "Carnot engine working between 400 K and 300 K has efficiency:", options: ["25%", "50%", "75%", "33%"], answer: 0 },
      { question: "In adiabatic process, Q =", options: ["0", "ΔU", "W", "–W"], answer: 0 },
    ],
    prevChapterId: "chapter-11", nextChapterId: "chapter-13",
  },
  {
    chapterId: "chapter-13", order: 13,
    title: "Kinetic Theory of Gases",
    objective: "Understand ideal gas model, kinetic interpretation of temperature, and degrees of freedom.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Ideal Gas and Assumptions", content: "Gas molecules are point masses, move randomly, elastic collisions, no intermolecular forces except during collision." },
      { heading: "Kinetic Theory Derivation", content: "Pressure P = ⅓ρ<v²> = ⅓(mn/V)<v²>. Average KE per molecule = (3/2)kT." },
      { heading: "rms, Average, and Most Probable Speed", content: "v_rms = √(3RT/M); v_avg = √(8RT/πM); v_mp = √(2RT/M). Ratio: v_mp : v_avg : v_rms = 1 : 1.128 : 1.225." },
    ],
    keyFormulas: [
      { label: "Ideal gas law", formula: "PV = nRT (R = 8.314 J/mol·K)" },
      { label: "Average KE per molecule", formula: "½m<v²> = (3/2)kT" },
      { label: "rms speed", formula: "v_rms = √(3RT/M)" },
      { label: "Mean free path", formula: "λ = 1/(√2 × πd²n)" },
    ],
    keyPoints: ["Temperature is a measure of average KE of molecules.", "Degrees of freedom f: monatomic=3, diatomic=5, polyatomic=6.", "Equipartition theorem: energy per degree of freedom = ½kT."],
    hasSimulation: true,
    simulationDescription: "Ideal gas simulation — visualize molecule collisions and Maxwell-Boltzmann speed distribution at different temperatures.",
    sampleQuestions: [
      { question: "Average KE of a gas molecule at temperature T is:", options: ["3/2 kT", "1/2 kT", "kT", "5/2 kT"], answer: 0 },
      { question: "At constant T and n, if V doubles, P becomes:", options: ["P/2", "2P", "4P", "P"], answer: 0 },
      { question: "RMS speed of gas molecules is proportional to:", options: ["√T", "T", "T²", "1/√T"], answer: 0 },
    ],
    prevChapterId: "chapter-12", nextChapterId: "chapter-14",
  },
  {
    chapterId: "chapter-14", order: 14,
    title: "Oscillations",
    objective: "Study simple harmonic motion, energy in SHM, resonance, and damped oscillations.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Simple Harmonic Motion", content: "SHM: restoring force ∝ displacement (F = –kx). Equation: x = A sin(ωt + φ). ω = 2πf = 2π/T." },
      { heading: "Energy in SHM", content: "PE = ½kx² = ½mω²x²; KE = ½mω²(A²–x²); Total E = ½kA² = ½mω²A² (constant)." },
      { heading: "Simple Pendulum", content: "T = 2π√(L/g) (for small angles). Note: independent of mass and amplitude." },
      { heading: "Damped and Forced Oscillations", content: "Damped: amplitude decreases with time. Forced: driven at a different frequency. Resonance: maximum amplitude when driving frequency = natural frequency." },
    ],
    keyFormulas: [
      { label: "SHM displacement", formula: "x = A sin(ωt + φ)" },
      { label: "Angular frequency", formula: "ω = √(k/m) = 2π/T" },
      { label: "Pendulum period", formula: "T = 2π√(L/g)" },
      { label: "Total energy SHM", formula: "E = ½kA² = ½mω²A²" },
    ],
    keyPoints: ["At mean position: v = Aω (max), a = 0, KE = max, PE = 0.", "At extreme: v = 0, a = Aω² (max), KE = 0, PE = max.", "Time period of spring-mass system: T = 2π√(m/k)."],
    hasSimulation: true,
    simulationDescription: "SHM simulator — pendulum and spring-mass system with energy visualization and phase diagram.",
    sampleQuestions: [
      { question: "Period of pendulum of length 1m (g=10) is:", options: ["π/5 s", "2π/√10 s", "2 s", "π s"], answer: 1 },
      { question: "In SHM, velocity is maximum at:", options: ["Extreme position", "Mean position", "Any position", "Depends on mass"], answer: 1 },
      { question: "Total energy in SHM depends on:", options: ["Mass only", "Amplitude only", "Amplitude and ω", "Amplitude, mass, and ω"], answer: 2 },
    ],
    prevChapterId: "chapter-13", nextChapterId: "chapter-15",
  },
  {
    chapterId: "chapter-15", order: 15,
    title: "Waves",
    objective: "Study wave motion, sound waves, superposition, standing waves, and Doppler effect.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Wave Types", content: "Transverse waves: displacement perpendicular to direction (light waves). Longitudinal waves: displacement parallel to direction (sound waves)." },
      { heading: "Wave Equation", content: "y(x,t) = A sin(kx – ωt) where k = 2π/λ (wave number), ω = 2πf. Speed v = ω/k = fλ." },
      { heading: "Superposition and Interference", content: "Constructive interference: waves in phase, amplitude adds. Destructive: waves out of phase (by π), amplitude cancels." },
      { heading: "Standing Waves", content: "Formed by superposition of two identical waves going in opposite directions. Nodes: no displacement; antinodes: max displacement." },
      { heading: "Doppler Effect", content: "Apparent frequency changes when source/observer moves. f' = f(v±v₀)/(v∓vₛ) where v₀ = observer velocity, vₛ = source velocity." },
    ],
    keyFormulas: [
      { label: "Wave speed", formula: "v = fλ = ω/k" },
      { label: "Speed of sound in gas", formula: "v = √(γP/ρ)" },
      { label: "Doppler formula", formula: "f' = f(v ± v₀)/(v ∓ vₛ)" },
      { label: "Frequency of string (nth harmonic)", formula: "fₙ = n/(2L) × √(T/μ)" },
    ],
    keyPoints: ["Sound travels fastest in solids, slowest in gases.", "Beats = |f₁ – f₂| per second.", "Speed of sound in air at 0°C ≈ 332 m/s."],
    hasSimulation: true,
    simulationDescription: "Wave superposition and standing wave simulator — visualize interference patterns, nodes, and antinodes.",
    sampleQuestions: [
      { question: "A wave has frequency 500 Hz and wavelength 0.4 m. Speed = ?", options: ["200 m/s", "100 m/s", "1250 m/s", "400 m/s"], answer: 0 },
      { question: "Doppler effect is about change in:", options: ["Speed", "Wavelength", "Frequency", "Amplitude"], answer: 2 },
      { question: "Standing wave has nodes at which position?", options: ["Max displacement", "Zero displacement", "Halfway", "Depends on frequency"], answer: 1 },
    ],
    prevChapterId: "chapter-14", nextChapterId: undefined,
  },
];
