/**
 * @file lib/content/class11-chemistry.ts
 * @description NCERT-aligned Class 11 Chemistry curriculum content
 * Every chapter matches NCERT Class 11 Chemistry (2025-26 edition)
 */

import type { ContentChapter } from "./class9-mathematics";

export const CLASS_11_CHEMISTRY_CHAPTERS: ContentChapter[] = [
  {
    chapterId: "chapter-01", order: 1,
    title: "Some Basic Concepts of Chemistry",
    objective: "Understand mole concept, empirical/molecular formulas, stoichiometry, and limiting reagents.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Importance of Chemistry", content: "Chemistry is the science of matter, its properties, composition, structure, and changes." },
      { heading: "Matter and Its Classification", content: "Pure substances: elements and compounds. Mixtures: homogeneous and heterogeneous." },
      { heading: "Laws of Chemical Combination", content: "Conservation of mass, Definite proportions, Multiple proportions, Gay-Lussac's law of gaseous volumes, Avogadro's law." },
      { heading: "Mole Concept", content: "1 mole = 6.022×10²³ particles (Avogadro's number, Nₐ). Molar mass = mass in grams of 1 mole. Moles = given mass / molar mass." },
      { heading: "Stoichiometry", content: "Mass-mole calculations based on balanced chemical equations. Limiting reagent determines the maximum product." },
    ],
    keyFormulas: [
      { label: "Moles", formula: "n = m/M (mass/molar mass)" },
      { label: "Molarity", formula: "M = moles of solute / volume of solution (in L)" },
      { label: "Percentage composition", formula: "%(element) = (mass of element / molar mass of compound) × 100" },
    ],
    keyPoints: ["Avogadro's number Nₐ = 6.022 × 10²³.", "Empirical formula gives simplest ratio; molecular formula gives actual number of atoms.", "In limiting reagent problems, calculate moles of each reactant."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Molar mass of H₂O is:", options: ["16 g/mol", "18 g/mol", "20 g/mol", "2 g/mol"], answer: 1 },
      { question: "Number of moles in 44 g of CO₂ (M=44 g/mol):", options: ["2 mol", "0.5 mol", "1 mol", "44 mol"], answer: 2 },
      { question: "Avogadro's number is approximately:", options: ["6.022×10²³", "6.022×10²²", "6.022×10²⁴", "1.602×10⁻¹⁹"], answer: 0 },
    ],
    prevChapterId: undefined, nextChapterId: "chapter-02",
  },
  {
    chapterId: "chapter-02", order: 2,
    title: "Structure of Atom",
    objective: "Understand atomic models, quantum numbers, electronic configuration, and periodic properties.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Atomic Models", content: "Thomson (plum pudding), Rutherford (nuclear model), Bohr (energy levels for hydrogen). Each model improved on the previous." },
      { heading: "Quantum Numbers", content: "n (principal: energy, size), l (azimuthal: shape), mₗ (magnetic: orientation), mₛ (spin: +½ or –½). Pauli exclusion: no two electrons can have same set of 4 quantum numbers." },
      { heading: "Orbitals and Shapes", content: "s: spherical, p: dumbbell, d: double dumbbell, f: complex. Number of orbitals per subshell: s=1, p=3, d=5, f=7." },
      { heading: "Electronic Configuration", content: "Aufbau principle: fill lowest energy first. Hund's rule: one electron in each degenerate orbital before pairing. Pauli exclusion: max 2 electrons per orbital with opposite spins." },
    ],
    keyFormulas: [
      { label: "Energy of Bohr orbit (H)", formula: "Eₙ = –13.6/n² eV" },
      { label: "Radius of Bohr orbit", formula: "rₙ = 0.529n² Å" },
      { label: "Wavelength (de Broglie)", formula: "λ = h/mv" },
    ],
    keyPoints: ["Heisenberg uncertainty principle: Δx·Δp ≥ h/4π.", "Energy of subshells: s < p < d < f within same shell.", "4s fills before 3d (Aufbau), but 3d is emptied before 4s in ionization."],
    hasSimulation: true,
    simulationDescription: "Bohr model hydrogen atom simulator — click orbitals, see electron transitions and photon emission/absorption.",
    sampleQuestions: [
      { question: "Principal quantum number n=2, possible l values:", options: ["0 only", "0 and 1", "0, 1, 2", "1 and 2"], answer: 1 },
      { question: "Maximum electrons in 3d subshell:", options: ["6", "10", "14", "2"], answer: 1 },
      { question: "Electronic configuration of Na (Z=11):", options: ["1s²2s²2p⁶3s¹", "1s²2s²2p⁵3s²", "1s²2s²2p⁶3p¹", "1s²2s²2p⁶"], answer: 0 },
    ],
    prevChapterId: "chapter-01", nextChapterId: "chapter-03",
  },
  {
    chapterId: "chapter-03", order: 3,
    title: "Classification of Elements and Periodicity in Properties",
    objective: "Understand periodic table organization and periodic trends in properties.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Modern Periodic Law", content: "Properties of elements are periodic functions of their atomic number." },
      { heading: "Periodic Table Organization", content: "118 elements. Groups 1–18. Periods 1–7. Blocks: s (groups 1-2), p (13-18), d (3-12), f (lanthanides/actinides)." },
      { heading: "Periodic Trends", content: "Atomic radius: decreases across period (increasing Zeff), increases down group. Ionization energy: increases across period, decreases down group. Electron affinity and electronegativity follow similar trends to IE." },
    ],
    keyFormulas: [],
    keyPoints: ["Zeff = Z – σ (nuclear charge minus shielding). Higher Zeff → smaller atom, higher IE.", "Noble gases have the highest IE in each period.", "Anomalies: N has higher IE than O (half-filled 2p is extra stable)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which has the largest atomic radius?", options: ["Na", "Mg", "Al", "K"], answer: 3 },
      { question: "Property that increases down a group:", options: ["Ionization energy", "Electronegativity", "Atomic radius", "Electron affinity"], answer: 2 },
      { question: "Elements in the same group have the same number of:", options: ["Protons", "Electrons", "Valence electrons", "Neutrons"], answer: 2 },
    ],
    prevChapterId: "chapter-02", nextChapterId: "chapter-04",
  },
  {
    chapterId: "chapter-04", order: 4,
    title: "Chemical Bonding and Molecular Structure",
    objective: "Understand ionic, covalent, and metallic bonds, VSEPR theory, hybridization, and MO theory.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Ionic Bond", content: "Formed by complete transfer of electrons from metal to non-metal. Electrostatic attraction between cations and anions. NaCl, MgO are examples." },
      { heading: "Covalent Bond", content: "Formed by sharing of electrons. Single (2e), double (4e), triple (6e) bonds. Lewis structures represent bonding." },
      { heading: "VSEPR Theory", content: "Valence Shell Electron Pair Repulsion: electron pairs arrange to minimize repulsion. Determines molecular geometry. LP-LP > LP-BP > BP-BP repulsion." },
      { heading: "Hybridization", content: "sp³ (tetrahedral, 109.5°): CH₄; sp² (trigonal planar, 120°): BF₃; sp (linear, 180°): BeCl₂; sp³d (trigonal bipyramidal): PCl₅; sp³d² (octahedral): SF₆." },
      { heading: "Molecular Orbital Theory", content: "Electrons are in molecular orbitals formed by LCAO. Bonding MOs (lower energy) and antibonding MOs (higher energy). Bond order = ½(bonding – antibonding electrons)." },
    ],
    keyFormulas: [
      { label: "Formal charge", formula: "FC = Valence e⁻ – Lone pair e⁻ – ½(Bonding e⁻)" },
      { label: "Bond order (MO theory)", formula: "½ × (Bonding – Antibonding electrons)" },
    ],
    keyPoints: ["Bond order increases with bond strength and decreases with bond length.", "VSEPR: lone pairs take more space than bonding pairs.", "Resonance structures: actual structure is a hybrid."],
    hasSimulation: true,
    simulationDescription: "Molecular geometry visualizer — build molecules, predict VSEPR shape, and see 3D structure with bond angles.",
    sampleQuestions: [
      { question: "Hybridization of carbon in CH₄:", options: ["sp", "sp²", "sp³", "sp³d"], answer: 2 },
      { question: "Bond order of N₂ by MO theory:", options: ["1", "2", "3", "0"], answer: 2 },
      { question: "Geometry of H₂O according to VSEPR:", options: ["Linear", "Bent/V-shaped", "Tetrahedral", "Trigonal planar"], answer: 1 },
    ],
    prevChapterId: "chapter-03", nextChapterId: "chapter-05",
  },
  {
    chapterId: "chapter-05", order: 5,
    title: "States of Matter",
    objective: "Study gas laws, kinetic molecular theory, liquid properties, and real gas behaviour.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Gas Laws", content: "Boyle's law: PV = const (T const). Charles's law: V/T = const (P const). Gay-Lussac's: P/T = const (V const). Avogadro: V ∝ n (same P, T). Combined: PV = nRT (ideal gas)." },
      { heading: "Kinetic Molecular Theory", content: "Gases consist of point masses in constant random motion. Collisions are elastic. Average KE ∝ temperature. Assumptions break at high P and low T." },
      { heading: "Real Gases", content: "Van der Waals equation: (P + an²/V²)(V–nb) = nRT. 'a' corrects for intermolecular attraction; 'b' corrects for volume of molecules." },
      { heading: "Liquids", content: "Surface tension: energy per unit area of surface. Viscosity: resistance to flow. Vapour pressure increases with temperature; boiling when P_vap = P_atm." },
    ],
    keyFormulas: [
      { label: "Ideal gas law", formula: "PV = nRT (R = 8.314 J/mol·K)" },
      { label: "Van der Waals", formula: "(P + an²/V²)(V – nb) = nRT" },
      { label: "Graham's law of effusion", formula: "Rate₁/Rate₂ = √(M₂/M₁)" },
    ],
    keyPoints: ["STP: 0°C, 1 atm; molar volume of ideal gas at STP = 22.4 L/mol.", "Boiling point increases with pressure (pressure cooker).", "Vapour pressure of mixture: Raoult's law P = x_A P°_A + x_B P°_B."],
    hasSimulation: true,
    simulationDescription: "Gas law simulator — visualize Boyle's and Charles's laws with interactive PVT graphs.",
    sampleQuestions: [
      { question: "Boyle's law: at constant T, as P increases, V:", options: ["Increases", "Decreases", "Stays same", "Doubles"], answer: 1 },
      { question: "Molar volume of ideal gas at STP:", options: ["22.4 L", "22400 mL", "Both A and B", "24 L"], answer: 2 },
      { question: "Van der Waals constant 'a' accounts for:", options: ["Molecular volume", "Intermolecular forces", "Temperature", "Pressure"], answer: 1 },
    ],
    prevChapterId: "chapter-04", nextChapterId: "chapter-06",
  },
  {
    chapterId: "chapter-06", order: 6,
    title: "Thermodynamics",
    objective: "Apply laws of thermodynamics to chemical reactions — enthalpy, entropy, Gibbs energy, and spontaneity.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "System and Surroundings", content: "Open system: exchanges matter and energy. Closed: only energy. Isolated: neither. Extensive properties: depend on amount (V, n). Intensive: do not (T, P, density)." },
      { heading: "First Law", content: "ΔU = q + w (IUPAC). q: heat absorbed by system; w: work done on system. At constant P: ΔH = ΔU + PΔV = qₚ." },
      { heading: "Hess's Law and Enthalpies", content: "ΔH for a reaction is independent of the pathway. Standard enthalpies: formation (ΔHf°), combustion, neutralization, atomization, bond dissociation." },
      { heading: "Entropy and Second Law", content: "Entropy S measures disorder. ΔSuniverse > 0 for spontaneous processes. ΔSsystem = qrev/T." },
      { heading: "Gibbs Energy", content: "ΔG = ΔH – TΔS. ΔG < 0: spontaneous; ΔG > 0: non-spontaneous; ΔG = 0: equilibrium. ΔG° = –RT ln K." },
    ],
    keyFormulas: [
      { label: "First law", formula: "ΔU = q + w" },
      { label: "Enthalpy", formula: "ΔH = ΔU + ΔnRT (for gases)" },
      { label: "Gibbs energy", formula: "ΔG = ΔH – TΔS" },
      { label: "Relationship to equilibrium", formula: "ΔG° = –RT ln K" },
    ],
    keyPoints: ["Exothermic reactions: ΔH < 0. Endothermic: ΔH > 0.", "ΔG = –nFE_cell for electrochemical cells.", "For a reaction to be always spontaneous: ΔH<0 and ΔS>0."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "In an exothermic reaction, ΔH is:", options: ["> 0", "< 0", "= 0", "Depends on T"], answer: 1 },
      { question: "A process is spontaneous when ΔG is:", options: ["Positive", "Negative", "Zero", "Any value"], answer: 1 },
      { question: "ΔH = ΔU + PΔV is true at:", options: ["Constant T", "Constant V", "Constant P", "All conditions"], answer: 2 },
    ],
    prevChapterId: "chapter-05", nextChapterId: "chapter-07",
  },
  {
    chapterId: "chapter-07", order: 7,
    title: "Equilibrium",
    objective: "Understand chemical equilibrium, Le Chatelier's principle, ionic equilibrium, pH, and buffers.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Chemical Equilibrium", content: "Dynamic state where rate of forward reaction = rate of backward reaction. Equilibrium constant Kc = [products]/[reactants] at given T. Kp = Kc(RT)^Δn." },
      { heading: "Le Chatelier's Principle", content: "If a system at equilibrium is disturbed, it shifts to counteract the disturbance: increase concentration of reactant → shift right; increase P → shift towards fewer moles of gas; increase T → shift towards endothermic direction." },
      { heading: "Ionic Equilibrium", content: "Weak acids/bases partially dissociate. Ka (acid dissociation constant), Kb. pKa = –log Ka. Stronger acid = higher Ka = lower pKa." },
      { heading: "pH and Buffers", content: "pH = –log[H⁺]. For water: pH + pOH = 14 at 25°C. Buffer resists pH change: Henderson-Hasselbalch equation: pH = pKa + log([A⁻]/[HA])." },
    ],
    keyFormulas: [
      { label: "Equilibrium constant", formula: "Kc = [C]ᶜ[D]ᵈ / [A]ᵃ[B]ᵇ" },
      { label: "Kp and Kc relation", formula: "Kp = Kc(RT)^Δn" },
      { label: "pH", formula: "pH = –log[H⁺]" },
      { label: "Henderson-Hasselbalch", formula: "pH = pKa + log([A⁻]/[HA])" },
      { label: "Kw", formula: "Kw = [H⁺][OH⁻] = 10⁻¹⁴ at 25°C" },
    ],
    keyPoints: ["Q < K: forward reaction favored. Q > K: backward reaction favored. Q = K: equilibrium.", "Common ion effect suppresses ionization of weak acid/base.", "Solubility product Ksp = [Mⁿ⁺][Xⁿ⁻] for sparingly soluble salts."],
    hasSimulation: true,
    simulationDescription: "Equilibrium constant simulator — change concentrations and see Q vs K comparison with reaction direction.",
    sampleQuestions: [
      { question: "If Kc = 100 for a reaction, the equilibrium favors:", options: ["Reactants", "Products", "Equal both", "Depends on T"], answer: 1 },
      { question: "Adding a catalyst to a reaction at equilibrium:", options: ["Shifts equilibrium right", "Shifts equilibrium left", "Does not shift equilibrium", "Increases K"], answer: 2 },
      { question: "pH of 0.01 M HCl is:", options: ["2", "–2", "12", "4"], answer: 0 },
    ],
    prevChapterId: "chapter-06", nextChapterId: "chapter-08",
  },
  {
    chapterId: "chapter-08", order: 8,
    title: "Redox Reactions",
    objective: "Understand oxidation, reduction, oxidation states, balancing redox equations, and electrochemical series.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Oxidation and Reduction", content: "Oxidation: loss of electrons (increase in oxidation state). Reduction: gain of electrons (decrease in oxidation state). OIL RIG: Oxidation Is Loss, Reduction Is Gain." },
      { heading: "Oxidation States", content: "Rules: pure element = 0; monatomic ion = charge; O = –2 (usually); H = +1 (usually); sum in neutral = 0; sum in ion = charge." },
      { heading: "Balancing Redox Equations", content: "Half-reaction method: write oxidation and reduction half-reactions, balance atoms and charges, add half-reactions. Ion-electron method in acidic/basic media." },
    ],
    keyFormulas: [],
    keyPoints: ["Oxidizing agent is itself reduced (gains electrons). Reducing agent is itself oxidized (loses electrons).", "Disproportionation: same substance both oxidized and reduced.", "Electrochemical series lists standard reduction potentials."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Oxidation state of Mn in KMnO₄:", options: ["+7", "+6", "+4", "+5"], answer: 0 },
      { question: "In 2H₂ + O₂ → 2H₂O, which is reduced?", options: ["H₂", "O₂", "H₂O", "All"], answer: 1 },
      { question: "OIL RIG means:", options: ["Oxidation Involves Loss, Reduction Involves Gain", "Oxidation Is Loss, Reduction Is Gain", "Only In Labs, Really Important Gases", "None of these"], answer: 1 },
    ],
    prevChapterId: "chapter-07", nextChapterId: "chapter-09",
  },
  {
    chapterId: "chapter-09", order: 9,
    title: "Hydrogen",
    objective: "Study hydrogen — isotopes, preparation, properties, hydrogen bonding, and uses.",
    durationLabel: "2 days",
    theoryPoints: [
      { heading: "Isotopes of Hydrogen", content: "Protium (¹H, 99.98%), Deuterium (²H or D, 0.016%), Tritium (³H or T, radioactive)." },
      { heading: "Preparation and Properties", content: "Lab: Zn + H₂SO₄ → ZnSO₄ + H₂. Commercial: steam reforming of methane. H₂ is colourless, odourless, lightest element. Burns in air: 2H₂ + O₂ → 2H₂O." },
      { heading: "Hydrogen Bonding", content: "Intermolecular H-bond (between molecules): responsible for high boiling point of H₂O, HF. Intramolecular H-bond (within same molecule): o-nitrophenol." },
      { heading: "Hydrides", content: "Ionic hydrides (NaH), covalent hydrides (H₂O, HCl), metallic hydrides (PdH₀.₆). Water is amphoteric: acts as acid or base." },
    ],
    keyFormulas: [],
    keyPoints: ["H₂O has anomalous properties due to extensive H-bonding: high BP, high surface tension.", "Dihydrogen is a clean fuel: 2H₂ + O₂ → 2H₂O (only water as product).", "Hard water: contains Ca²⁺, Mg²⁺ ions — interferes with soap."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Heaviest isotope of hydrogen:", options: ["Protium", "Deuterium", "Tritium", "All have equal mass"], answer: 2 },
      { question: "H₂ bonding in water makes it:", options: ["Less dense than ice", "Have low boiling point", "Have high boiling point", "Less polar"], answer: 2 },
      { question: "H₂ acts as reducing agent because:", options: ["It gains electrons", "It loses electrons", "It donates protons", "It has no electrons"], answer: 1 },
    ],
    prevChapterId: "chapter-08", nextChapterId: "chapter-10",
  },
  {
    chapterId: "chapter-10", order: 10,
    title: "The s-Block Elements",
    objective: "Study Group 1 (alkali metals) and Group 2 (alkaline earth metals) — properties, reactions, and uses.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Group 1: Alkali Metals (Li, Na, K, Rb, Cs, Fr)", content: "Soft, low density, highly reactive, react with water to form hydroxide and H₂. Reactivity increases down the group. Na is stored in kerosene." },
      { heading: "Group 2: Alkaline Earth Metals (Be, Mg, Ca, Sr, Ba, Ra)", content: "Harder and denser than alkali metals. React with water more slowly. Ca(OH)₂: slaked lime; CaCO₃: limestone; CaSO₄·2H₂O: gypsum." },
      { heading: "Anomalous Properties of Li and Be", content: "Li and Be show anomalous properties due to small size and high polarizing power. Li resembles Mg (diagonal relationship). Be resembles Al." },
    ],
    keyFormulas: [],
    keyPoints: ["Flame colours: Li=crimson, Na=yellow, K=lilac, Ca=brick red, Sr=crimson, Ba=apple green.", "Na₂CO₃·10H₂O: washing soda. NaHCO₃: baking soda. NaOH: caustic soda.", "Plaster of Paris: CaSO₄·½H₂O; sets by absorbing water to form gypsum."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which alkali metal is stored in kerosene?", options: ["Li", "K", "Na", "Cs"], answer: 2 },
      { question: "Flame colour of sodium:", options: ["Lilac", "Yellow", "Red", "Green"], answer: 1 },
      { question: "Chemical formula of baking soda:", options: ["Na₂CO₃", "NaOH", "NaHCO₃", "Na₂SO₄"], answer: 2 },
    ],
    prevChapterId: "chapter-09", nextChapterId: "chapter-11",
  },
  {
    chapterId: "chapter-11", order: 11,
    title: "The p-Block Elements",
    objective: "Study Groups 13–18: boron family, carbon family, nitrogen family, oxygen family, halogens, and noble gases.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Group 13: Boron Family", content: "B, Al, Ga, In, Tl. Al is the most abundant metal in earth's crust. B compounds: borax (Na₂B₄O₇·10H₂O). Al reacts with acids and bases (amphoteric)." },
      { heading: "Group 14: Carbon Family", content: "C, Si, Ge, Sn, Pb. Carbon allotropes: diamond, graphite, fullerene. Si: semiconductor material. CO₂ (acidic oxide), CO (toxic). SiO₂: silica/quartz." },
      { heading: "Group 15: Nitrogen Family", content: "N₂ is inert (triple bond). NH₃: basic gas. HNO₃: strong acid. P allotropes: white P (toxic), red P. NO₂: brown acidic gas." },
      { heading: "Group 16: Oxygen Family", content: "O₂ essential for life. O₃ (ozone): formed by UV. H₂S: poisonous gas smelling of rotten eggs. H₂SO₄: strong diprotic acid." },
      { heading: "Group 17: Halogens", content: "F₂: most electronegative. Cl₂: greenish-yellow gas. HF: weak acid. HCl: strong acid. Bleaching powder: CaOCl₂." },
    ],
    keyFormulas: [],
    keyPoints: ["Carbon has the unique ability to form long chains (catenation) and multiple bonds.", "F₂ is the strongest oxidizing halogen (most electronegative).", "Noble gases (Gr 18) are inert due to complete valence shell."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which halogen is a liquid at room temperature?", options: ["F₂", "Cl₂", "Br₂", "I₂"], answer: 2 },
      { question: "Allotrope of carbon with highest melting point:", options: ["Graphite", "Diamond", "Fullerene", "Charcoal"], answer: 1 },
      { question: "Most electronegative element:", options: ["O", "Cl", "F", "N"], answer: 2 },
    ],
    prevChapterId: "chapter-10", nextChapterId: "chapter-12",
  },
  {
    chapterId: "chapter-12", order: 12,
    title: "Organic Chemistry — Basic Principles",
    objective: "Understand organic molecule classification, nomenclature, electron displacement, and reaction types.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Classification of Organic Compounds", content: "Open chain (acyclic): alkanes, alkenes, alkynes. Cyclic: alicyclic (no aromatic), aromatic (benzene ring), heterocyclic (non-carbon atoms in ring)." },
      { heading: "IUPAC Nomenclature", content: "Find longest chain (parent), number from end nearest substituent, add prefix/suffix for functional groups. Priority: –COOH > –CHO > –OH > –NH₂ > –C=C > –C≡C." },
      { heading: "Electron Displacement Effects", content: "Inductive effect (I): permanent through sigma bonds. Resonance effect (R/M): through pi bonds. Hyperconjugation: alpha H through sigma-pi conjugation. Electromeric effect (E): on reactant under attack." },
      { heading: "Types of Organic Reactions", content: "Addition (unsaturated compounds), Elimination, Substitution (SN1, SN2, SE2), Rearrangement. Free radical, Carbocation (electrophile), Carbanion (nucleophile) intermediates." },
    ],
    keyFormulas: [],
    keyPoints: ["Carbon always has 4 bonds. Valence of functional groups determines naming suffix.", "Electron-donating groups (+I, +R): –CH₃, –OH, –NH₂ destabilize carbocations... wait, actually EDG stabilize carbocations.", "Carbocations: 3°>2°>1°>methyl (stability due to hyperconjugation/inductive effect)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "IUPAC name of CH₃CH₂OH:", options: ["Methanol", "Ethanol", "Propanol", "Butanol"], answer: 1 },
      { question: "Most stable carbocation:", options: ["CH₃⁺", "C₂H₅⁺", "(CH₃)₂CH⁺", "(CH₃)₃C⁺"], answer: 3 },
      { question: "Inductive effect is transmitted through:", options: ["π bonds", "σ bonds", "Resonance", "Hydrogen bonds"], answer: 1 },
    ],
    prevChapterId: "chapter-11", nextChapterId: "chapter-13",
  },
  {
    chapterId: "chapter-13", order: 13,
    title: "Hydrocarbons",
    objective: "Study alkanes, alkenes, alkynes, and aromatic hydrocarbons — structure, reactions, and properties.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Alkanes (Paraffins)", content: "CₙH₂ₙ₊₂. Sp³ hybridized C. Reactions: free-radical halogenation, combustion. Non-reactive at room temperature (hence 'paraffins')." },
      { heading: "Alkenes (Olefins)", content: "CₙH₂ₙ. C=C double bond. sp² hybridized. Electrophilic addition reactions: HX (Markovnikov rule), H₂O, Br₂ (decolorizes bromine water — test for alkene)." },
      { heading: "Alkynes", content: "CₙH₂ₙ₋₂. C≡C triple bond. sp hybridized. Addition reactions: one or two moles of reagent can add. Terminal alkynes are acidic (pKa ~25)." },
      { heading: "Aromatic Hydrocarbons", content: "Benzene (C₆H₆): planar, all bond angles 120°, delocalized electrons. Resonance structure. Electrophilic aromatic substitution (EAS): halogenation, nitration, sulfonation, Friedel-Crafts alkylation." },
    ],
    keyFormulas: [],
    keyPoints: ["Markovnikov rule: H adds to C with more H (in addition to HX across C=C).", "Benzene does not decolorize KMnO₄ or Br₂/CCl₄ — does electrophilic substitution, not addition.", "Saytzeff's rule: elimination gives more substituted alkene."],
    hasSimulation: true,
    simulationDescription: "Organic reaction mechanism animator — see step-by-step mechanisms for electrophilic addition and aromatic substitution.",
    sampleQuestions: [
      { question: "What test confirms presence of C=C double bond?", options: ["Fehling test", "Bromine water test", "Tollen's test", "Iodoform test"], answer: 1 },
      { question: "Benzene primarily undergoes:", options: ["Addition reactions", "Substitution reactions", "Elimination reactions", "Rearrangement"], answer: 1 },
      { question: "HBr adds to CH₂=CHCH₃ according to Markovnikov to give:", options: ["CH₃CHBrCH₃", "CH₂BrCH₂CH₃", "CH₃CH=CH₂", "CH₃CHCH₂Br"], answer: 0 },
    ],
    prevChapterId: "chapter-12", nextChapterId: "chapter-14",
  },
  {
    chapterId: "chapter-14", order: 14,
    title: "Environmental Chemistry",
    objective: "Understand atmospheric composition, pollution sources, greenhouse effect, ozone layer, and water/soil pollution.",
    durationLabel: "2 days",
    theoryPoints: [
      { heading: "Atmosphere and Troposphere", content: "78% N₂, 21% O₂, 0.9% Ar, 0.03% CO₂. Troposphere: weather occurs here. Stratosphere: ozone layer (15-35 km). Mesosphere, Thermosphere, Exosphere above." },
      { heading: "Greenhouse Effect and Global Warming", content: "CO₂, CH₄, N₂O, H₂O, CFCs trap IR radiation. Average temperature rising. Effects: ice melting, sea level rise, extreme weather." },
      { heading: "Ozone Layer Depletion", content: "CFCs (chlorofluorocarbons) break down O₃. Each Cl can destroy thousands of O₃ molecules. Allows harmful UV-B to reach Earth causing skin cancer, cataracts." },
      { heading: "Water and Soil Pollution", content: "BOD (Biochemical Oxygen Demand): measure of organic pollution. High BOD → less O₂ → kills aquatic life. Pesticides, heavy metals cause soil pollution." },
    ],
    keyFormulas: [],
    keyPoints: ["pH of acid rain < 5.6 (due to H₂SO₄ and HNO₃ from pollutants).", "Photochemical smog: formed in presence of sunlight with NOₓ and VOCs.", "Clean water BOD < 5 ppm; polluted > 17 ppm."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Main cause of ozone layer depletion:", options: ["CO₂", "CFCs", "CH₄", "SO₂"], answer: 1 },
      { question: "Acid rain has pH:", options: ["= 7", "> 7", "< 5.6", "= 5.6"], answer: 2 },
      { question: "Greenhouse gas with highest global warming potential per molecule:", options: ["CO₂", "CH₄", "N₂O", "H₂O"], answer: 2 },
    ],
    prevChapterId: "chapter-13", nextChapterId: undefined,
  },
];
