/**
 * @file lib/content/class12-biology.ts
 * @description NCERT-aligned Class 12 Biology curriculum content
 * Every chapter matches NCERT Class 12 Biology (2025-26 edition)
 */

import type { ContentChapter } from "./class9-mathematics";

export const CLASS_12_BIOLOGY_CHAPTERS: ContentChapter[] = [
  {
    chapterId: "chapter-01", order: 1,
    title: "Sexual Reproduction in Flowering Plants",
    objective: "Study flower structure, pollination, fertilization, and development of seed and fruit.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Flower Structure", content: "Androecium (stamens): anther + filament. Gynoecium (pistil/carpel): stigma + style + ovary (ovules inside). Bisexual: both androecium and gynoecium. Unisexual: one only." },
      { heading: "Pollen Development and Structure", content: "Pollen grain = male gametophyte. Wall: exine (sporopollenin, very resistant) and intine (cellulose). Contains vegetative (tube) cell and generative cell. Pollen germination: pollen tube grows through style." },
      { heading: "Pollination", content: "Self-pollination (autogamy): same flower. Cross-pollination (allogamy): different plant. Agents: wind (anemophily), water (hydrophily), insects (entomophily), birds (ornithophily), bats (chiropterophily)." },
      { heading: "Double Fertilization", content: "Unique to angiosperms. Two male gametes: one fuses with egg (syngamy) → zygote (2n), another fuses with secondary nucleus (polar nuclei) → endosperm (3n). Endosperm nourishes embryo." },
    ],
    keyFormulas: [],
    keyPoints: ["Apomixis: seed formation without fertilization (Citrus, mango polyembryony).", "Emasculation: removing anthers from bisexual flower before pollen maturation (for hybridization).", "Parthenocarpy: seedless fruit development without fertilization (banana)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Double fertilization results in:", options: ["Two zygotes", "Zygote (2n) + Endosperm (3n)", "Two endosperms", "One zygote (3n)"], answer: 1 },
      { question: "Sporopollenin (pollen exine) is resistant to:", options: ["Heat only", "Physical/chemical degradation", "UV light only", "Enzymatic degradation"], answer: 1 },
      { question: "Cross-pollination by wind is called:", options: ["Hydrophily", "Entomophily", "Anemophily", "Ornithophily"], answer: 2 },
    ],
    prevChapterId: undefined, nextChapterId: "chapter-02",
  },
  {
    chapterId: "chapter-02", order: 2,
    title: "Human Reproduction",
    objective: "Study male and female reproductive systems, gametogenesis, fertilization, and embryonic development.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Male Reproductive System", content: "Testes (spermatogenesis, testosterone), epididymis (sperm maturation), vas deferens, seminal vesicle + prostate + Cowper's glands (semen components), penis (copulatory organ)." },
      { heading: "Spermatogenesis", content: "Spermatogonia (2n) → primary spermatocyte (2n) → secondary spermatocyte (n) → spermatids (n) → mature spermatozoa (n). Regulated by FSH and testosterone." },
      { heading: "Female Reproductive System", content: "Ovaries (oogenesis, estrogen, progesterone), fallopian tubes (site of fertilization), uterus (implantation, development), vagina (birth canal)." },
      { heading: "Oogenesis and Menstrual Cycle", content: "Oogenesis: primary oocyte → secondary oocyte + polar body (1st meiosis) → mature ovum + polar body (2nd meiosis, after fertilization). Menstrual cycle: menstrual (days 1-5), proliferative (follicular), secretory (luteal) phases. LH surge → ovulation (day 14)." },
      { heading: "Fertilization and Implantation", content: "Fertilization in ampulla of fallopian tube. Acrosomal reaction → penetration of zona pellucida. Zygote → morula → blastocyst (implantation in uterus at ~6 days)." },
    ],
    keyFormulas: [],
    keyPoints: ["Corpus luteum: ruptured Graafian follicle; secretes progesterone — maintains uterine lining.", "Human chorionic gonadotropin (hCG): secreted by trophoblast → basis of pregnancy test.", "Gestation period: ~280 days (40 weeks) from LMP."],
    hasSimulation: true,
    simulationDescription: "Human reproductive system and gametogenesis 3D explorer — visualize spermatogenesis and oogenesis stages.",
    sampleQuestions: [
      { question: "Site of fertilization in humans:", options: ["Uterus", "Cervix", "Fallopian tube (ampulla)", "Ovary"], answer: 2 },
      { question: "Hormone responsible for LH surge (ovulation):", options: ["FSH", "Progesterone", "Estrogen", "Prolactin"], answer: 2 },
      { question: "Hormone detected in pregnancy test:", options: ["hCG", "LH", "FSH", "Progesterone"], answer: 0 },
    ],
    prevChapterId: "chapter-01", nextChapterId: "chapter-03",
  },
  {
    chapterId: "chapter-03", order: 3,
    title: "Reproductive Health",
    objective: "Study reproductive health, contraception, STIs, amniocentesis, and assisted reproductive technologies.",
    durationLabel: "2 days",
    theoryPoints: [
      { heading: "Population Explosion and Birth Control", content: "India: 2nd most populous (1.4 billion). Contraception methods: Natural (rhythm, coitus interruptus), Barrier (condom, diaphragm), IUDs (copper-T, hormone-releasing), Oral contraceptive pills (combined OCP), Injectables, Implants, Surgical (vasectomy, tubectomy)." },
      { heading: "Sexually Transmitted Infections (STIs)", content: "Gonorrhea (Neisseria gonorrhoeae), Syphilis (Treponema pallidum), Genital warts (HPV), AIDS (HIV). Prevention: safe sex, condoms, blood screening, avoid sharing needles." },
      { heading: "Assisted Reproductive Technologies (ART)", content: "IVF: in vitro fertilization → embryo transfer (ET). GIFT: gamete intrafallopian transfer. ZIFT: zygote intrafallopian transfer. Intracytoplasmic sperm injection (ICSI). Surrogacy. Amniocentesis: prenatal diagnosis of chromosomal disorders (Down syndrome)." },
    ],
    keyFormulas: [],
    keyPoints: ["MTP (Medical Termination of Pregnancy): legal under specific conditions in India.", "PCPNDT Act: banned sex determination of foetus (prevents female foeticide).", "Amniocentesis: examining foetal cells in amniotic fluid — diagnoses chromosomal/genetic disorders."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Which contraceptive method is 100% effective?", options: ["Condom", "OCP", "Copper-T", "None are 100% effective"], answer: 3 },
      { question: "AIDS is caused by:", options: ["Bacteria", "Fungus", "HIV (virus)", "Protozoa"], answer: 2 },
      { question: "IVF stands for:", options: ["In Vivo Fertilization", "In Vitro Fertilization", "Internal Vaginal Fertilization", "Induced Viable Fertilization"], answer: 1 },
    ],
    prevChapterId: "chapter-02", nextChapterId: "chapter-04",
  },
  {
    chapterId: "chapter-04", order: 4,
    title: "Principles of Inheritance and Variation",
    objective: "Study Mendel's laws, exceptions, chromosomal theory of inheritance, and mutation.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Mendel's Laws", content: "Law of Dominance: in a cross, dominant trait appears in F1. Law of Segregation: alleles separate during gamete formation. Law of Independent Assortment: genes on different chromosomes segregate independently (trihybrid etc.)." },
      { heading: "Extensions of Mendelism", content: "Incomplete dominance: F1 intermediate phenotype (4 o'clock flower). Codominance: both alleles expressed (AB blood group). Multiple alleles: ABO blood group (Iᴬ, Iᴮ, i). Pleiotropy: one gene → multiple traits (sickle cell)." },
      { heading: "Sex Determination and Linkage", content: "XY mechanism (humans): females XX, males XY. Sex-linked inheritance: X-linked recessive (haemophilia, colour blindness — more common in males). Linkage: genes on same chromosome tend to be inherited together (Morgan's work on Drosophila)." },
      { heading: "Mutation", content: "Gene mutation: point mutation (base substitution, insertion, deletion). Chromosomal mutation: aneuploidy (Down syndrome: trisomy 21 = 47 chromosomes), polyploidy." },
    ],
    keyFormulas: [
      { label: "Dihybrid cross F2 ratio", formula: "9:3:3:1 (phenotypic)" },
      { label: "Test cross ratio", formula: "1:1 (for heterozygous parent)" },
    ],
    keyPoints: ["Chromosomal theory of inheritance: Morgan and Sutton-Boveri. Genes are on chromosomes.", "Hardy-Weinberg principle: p² + 2pq + q² = 1 (allele frequencies constant in equilibrium).", "Pedigree analysis: filled circles/squares = affected individuals."],
    hasSimulation: true,
    simulationDescription: "Mendelian genetics Punnett square simulator — set up any cross and generate offspring ratios.",
    sampleQuestions: [
      { question: "In incomplete dominance, F2 ratio is:", options: ["3:1", "1:2:1", "1:1", "9:3:3:1"], answer: 1 },
      { question: "Down syndrome has how many chromosomes?", options: ["45", "46", "47", "48"], answer: 2 },
      { question: "Haemophilia is X-linked recessive. Carrier mother × normal father → probability of son having haemophilia:", options: ["0%", "25%", "50%", "100%"], answer: 2 },
    ],
    prevChapterId: "chapter-03", nextChapterId: "chapter-05",
  },
  {
    chapterId: "chapter-05", order: 5,
    title: "Molecular Basis of Inheritance",
    objective: "Study DNA structure, DNA replication, transcription, translation, and gene expression regulation.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "DNA Structure", content: "Watson-Crick model: double helix, antiparallel strands (3'→5' and 5'→3'). Base pairing: A-T (2 H-bonds), G-C (3 H-bonds). Right-handed B-form DNA in cells. Chargaff's rule: A=T, G=C." },
      { heading: "DNA Replication (Semi-Conservative)", content: "Meselson-Stahl experiment proved semi-conservative replication. Enzyme: DNA polymerase III (main); primase (RNA primer); helicase (unwinding); ligase (Okazaki fragments). Leading strand: continuous; lagging: discontinuous (Okazaki fragments)." },
      { heading: "Transcription", content: "Template strand (antisense) → mRNA (sense strand sequence). RNA polymerase reads 3'→5', synthesizes mRNA 5'→3'. In prokaryotes: no processing. In eukaryotes: hnRNA → capping (5' m⁷G cap) + polyadenylation (3' polyA) + splicing (remove introns, join exons) → mRNA." },
      { heading: "Translation", content: "mRNA codons (triplets) → amino acids (tRNA anticodon). Start codon: AUG (Met). Stop: UAA, UAG, UGA. Ribosomes (A, P, E sites). Polyribosomes: multiple ribosomes on one mRNA." },
    ],
    keyFormulas: [
      { label: "Chargaff's rule", formula: "[A] = [T], [G] = [C]; [A]+[G] = [T]+[C]" },
      { label: "Number of codons", formula: "4³ = 64 (61 sense + 3 stop codons)" },
    ],
    keyPoints: ["Central dogma: DNA → RNA → Protein (also reverse transcription by retroviruses).", "Genetic code is degenerate (multiple codons for same amino acid), unambiguous, universal.", "Gene regulation: lac operon (E. coli) — repressor bound to operator by default; lactose inactivates repressor."],
    hasSimulation: true,
    simulationDescription: "DNA replication and transcription/translation simulator — see the complete information flow from DNA to protein.",
    sampleQuestions: [
      { question: "In DNA, A pairs with T by how many hydrogen bonds?", options: ["3", "2", "1", "4"], answer: 1 },
      { question: "Stop codons are:", options: ["AUG, UAA, UAG", "UAA, UAG, UGA", "UAG, UGA, UGG", "UGA, AUG, UAA"], answer: 1 },
      { question: "Meselson-Stahl experiment proved:", options: ["Conservative replication", "Semi-conservative replication", "Dispersive replication", "Linear replication"], answer: 1 },
    ],
    prevChapterId: "chapter-04", nextChapterId: "chapter-06",
  },
  {
    chapterId: "chapter-06", order: 6,
    title: "Evolution",
    objective: "Study origin of life, theories of evolution, evidence, and speciation mechanisms.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Origin of Life", content: "Urey-Miller experiment: electric sparks in H₂O, H₂, CH₄, NH₃ mixture → amino acids formed. RNA World hypothesis: RNA was first biomolecule (could catalyze and replicate). Oparin and Haldane: coacervates (precells)." },
      { heading: "Theories of Evolution", content: "Lamarck (1809): use and disuse, inheritance of acquired characters (incorrect). Darwin (1859): natural selection — variation + struggle for existence + differential survival (survival of the fittest). Modern Synthesis: Neo-Darwinism — natural selection + genetics + mutation." },
      { heading: "Evidence for Evolution", content: "Fossil record, Comparative anatomy (homologous/analogous structures), Biogeography, Molecular biology (cytochrome c similarity), Embryology (gill slits in embryos)." },
      { heading: "Speciation", content: "Allopatric: geographic isolation → genetic divergence. Sympatric: reproductive isolation within same area (polyploidy in plants). Hardy-Weinberg equilibrium: no evolution occurring — all factors at equilibrium." },
    ],
    keyFormulas: [
      { label: "Hardy-Weinberg", formula: "p² + 2pq + q² = 1; p + q = 1" },
    ],
    keyPoints: ["Homologous organs: same origin, different function (forelimbs of humans, whales, bats).", "Analogous organs: different origin, similar function (wings of birds and insects).", "Industrial melanism (peppered moth): classic example of natural selection."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Who proposed the 'Use and Disuse' theory of evolution?", options: ["Darwin", "Wallace", "Lamarck", "Mendel"], answer: 2 },
      { question: "Homologous organs indicate:", options: ["Analogous evolution", "Convergent evolution", "Divergent evolution", "No evolution"], answer: 2 },
      { question: "Hardy-Weinberg principle describes allele frequency when:", options: ["Evolution is occurring", "No evolutionary forces act", "Migration occurs", "Mutation occurs"], answer: 1 },
    ],
    prevChapterId: "chapter-05", nextChapterId: "chapter-07",
  },
  {
    chapterId: "chapter-07", order: 7,
    title: "Human Health and Disease",
    objective: "Study immunity, vaccines, infectious diseases, cancer, and drug/alcohol abuse.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Innate and Adaptive Immunity", content: "Innate (non-specific): barriers (skin, mucus), phagocytes, NK cells, interferons, complement. Adaptive (specific): B-cells (humoral, antibody-mediated), T-cells (cell-mediated). Immunological memory (anamnestic response — faster 2nd response)." },
      { heading: "Types of Immunity", content: "Active (natural: infection, artificial: vaccination). Passive (natural: mother's antibodies via placenta/milk, artificial: antiserum injection — immediate but short-lived)." },
      { heading: "Infectious Diseases", content: "Malaria: Plasmodium (Anopheles mosquito vector). Typhoid: Salmonella typhi (Widal test). Pneumonia: Streptococcus pneumoniae. AIDS: HIV (retroviruse), attacks CD4+ T-cells. Cancer: uncontrolled cell division (oncogenes)." },
      { heading: "Drugs and Alcohol Abuse", content: "Opioids: morphine, heroin (analgesics, addiction). Cannabinoids: marijuana, hashish. Stimulants: cocaine, amphetamines. Effects: mental disorders, liver damage, cardiac failure. Prevention: education, counseling." },
    ],
    keyFormulas: [],
    keyPoints: ["IgG: crosses placenta (passive immunity to foetus). IgA: in breast milk. IgE: allergy.", "CD4+ T-helper cell count < 200/mm³ → AIDS (from HIV positive). Normal: 500-1500.", "Benign tumor: encapsulated, doesn't spread. Malignant (cancer): metastasis (spreads)."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "HIV attacks which cells?", options: ["B-cells", "CD4+ T-cells", "NK cells", "Macrophages"], answer: 1 },
      { question: "Malaria is caused by:", options: ["Virus", "Bacterium", "Plasmodium (protozoan)", "Fungus"], answer: 2 },
      { question: "Vaccine provides:", options: ["Passive immunity", "Active immunity", "Innate immunity", "No immunity"], answer: 1 },
    ],
    prevChapterId: "chapter-06", nextChapterId: "chapter-08",
  },
  {
    chapterId: "chapter-08", order: 8,
    title: "Microbes in Human Welfare",
    objective: "Study beneficial microbes in food, industry, sewage treatment, biogas, and biocontrol.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Microbes in Food Production", content: "Lactobacillus acidophilus: curd from milk (lactic acid). Yeast (Saccharomyces cerevisiae): fermentation (bread, wine, beer). Aspergillus niger: citric acid production. Microbes in cheese ripening." },
      { heading: "Industrial Microbes", content: "Penicillium notatum: penicillin (Fleming, 1928). Streptomyces: streptomycin. Aspergillus: glucoamylase. Clostridium: acetone-butanol. Trichoderma polysporum: cyclosporin A (immunosuppressant)." },
      { heading: "Sewage Treatment", content: "Primary: physical removal (screens, settling tanks). Secondary: biological — aerobic bacteria digest organic matter (activated sludge). BOD reduction. Tertiary: chemical treatment. Biogas from anaerobic sludge digestion." },
      { heading: "Biocontrol and Biofertilizers", content: "Bacillus thuringiensis (Bt): insecticide (Cry protein). Trichoderma: fungal biocontrol. Baculoviruses: insect pathogens. Biofertilizers: Rhizobium, Azotobacter, Azospirillum, mycorrhiza." },
    ],
    keyFormulas: [],
    keyPoints: ["Biogas: ~75% CH₄ + CO₂, produced by Methanobacterium (anaerobic).", "BOD (Biochemical Oxygen Demand): measure of organic pollution — clean water < 5 ppm.", "Mycorrhiza increases phosphate availability to plant."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Penicillin was discovered by:", options: ["Fleming", "Pasteur", "Jenner", "Koch"], answer: 0 },
      { question: "Main component of biogas:", options: ["H₂", "CO₂", "CH₄ (methane)", "N₂"], answer: 2 },
      { question: "Bacillus thuringiensis is used as:", options: ["Biofertilizer", "Biopesticide", "Biogas producer", "Food additive"], answer: 1 },
    ],
    prevChapterId: "chapter-07", nextChapterId: "chapter-09",
  },
  {
    chapterId: "chapter-09", order: 9,
    title: "Biotechnology: Principles and Processes",
    objective: "Study recombinant DNA technology, cloning vectors, PCR, and gel electrophoresis.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Recombinant DNA Technology", content: "Tools: Restriction endonucleases (molecular scissors — cut DNA at specific sequences), DNA ligase (molecular glue), vectors (plasmid, bacteriophage, cosmid), host cells." },
      { heading: "Restriction Enzymes", content: "Type II restriction enzymes cut at palindromic sequences (EcoRI cuts GAATTC). Creates sticky ends (cohesive ends) or blunt ends. Named from organism: EcoRI from E. coli R strain I." },
      { heading: "Cloning Vectors", content: "Plasmids (pBR322, pUC): origin of replication, selectable marker, restriction sites. Bacteriophage (λ phage), Cosmid (hybrid), BAC (Bacterial Artificial Chromosome), YAC (Yeast Artificial Chromosome) for large inserts." },
      { heading: "PCR and Gel Electrophoresis", content: "PCR: Polymerase Chain Reaction — exponential amplification of DNA. Steps: Denaturation (94°C) → Annealing (50-65°C) → Extension (72°C, Taq polymerase). Gel electrophoresis: separates DNA by size (smaller fragments migrate faster)." },
    ],
    keyFormulas: [],
    keyPoints: ["EcoRI palindromic sequence: 5'-GAATTC-3' / 3'-CTTAAG-5'.", "Competent cells: cells made capable of taking up foreign DNA (heat shock + CaCl₂).", "Recombinant DNA: DNA from two different sources joined together."],
    hasSimulation: true,
    simulationDescription: "Restriction enzyme and gel electrophoresis simulator — cut DNA and see band patterns.",
    sampleQuestions: [
      { question: "Restriction enzymes are also called:", options: ["Molecular glue", "Molecular scissors", "Molecular probes", "Molecular scissors and glue"], answer: 1 },
      { question: "In PCR, Taq polymerase is used because:", options: ["It's cheapest", "It's thermostable", "It works only at low T", "It produces RNA"], answer: 1 },
      { question: "In gel electrophoresis, smaller DNA fragments:", options: ["Move faster toward anode", "Move slower", "Don't move", "Move toward cathode"], answer: 0 },
    ],
    prevChapterId: "chapter-08", nextChapterId: "chapter-10",
  },
  {
    chapterId: "chapter-10", order: 10,
    title: "Biotechnology and its Applications",
    objective: "Study GMOs, transgenic plants, GM crops, gene therapy, molecular diagnostics, and ethics.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Transgenic Plants and GM Crops", content: "Bt cotton: Cry1Ac gene from Bt → Cry protein → kills bollworm (insect resistance). Flavr Savr tomato: delayed ripening. Golden Rice: β-carotene producing rice (Vitamin A precursor). Herbicide-resistant crops." },
      { heading: "Gene Therapy", content: "ADA deficiency (adenosine deaminase): first gene therapy trial. Retroviral vector delivers functional ADA gene to patient's lymphocytes." },
      { heading: "Molecular Diagnostics", content: "PCR: detects HIV from blood. ELISA (Enzyme-Linked Immunosorbent Assay): detects antibodies. DNA fingerprinting (VNTR, STR analysis): forensics, paternity testing." },
      { heading: "Bioethical Issues", content: "Biopiracy: use of indigenous knowledge without compensation. Terminator technology: prevents seed germination. GMO safety concerns. Biopatents and IPR (Intellectual Property Rights)." },
    ],
    keyFormulas: [],
    keyPoints: ["Cry proteins from Bt are insecticidal only after ingestion by insects (alkaline gut pH activates toxin).", "ELISA used to detect HIV antibodies (indirect ELISA) or HIV antigens (sandwich ELISA).", "Transgenic animals: used for pharmaceutical protein production (pharming) — e.g., transgenic sheep producing alpha-1-antitrypsin."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Bt cotton is resistant to:", options: ["Virus", "Bollworm (insect)", "Fungus", "Herbicides"], answer: 1 },
      { question: "ELISA is used to diagnose:", options: ["DNA mutations", "Antibodies or antigens (HIV, hepatitis)", "Gene expression", "Bacterial infections only"], answer: 1 },
      { question: "ADA deficiency is treated by:", options: ["Bone marrow transplant only", "Gene therapy", "Chemotherapy", "Radiation"], answer: 1 },
    ],
    prevChapterId: "chapter-09", nextChapterId: "chapter-11",
  },
  {
    chapterId: "chapter-11", order: 11,
    title: "Ecology: Organisms and Populations",
    objective: "Study ecological concepts, population attributes, growth models, and organism-environment interactions.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Ecology and Environment", content: "Ecology: study of interactions among organisms and between organisms and their physical environment. Levels: organism → population → community → ecosystem → biosphere." },
      { heading: "Population Attributes", content: "Birth rate, death rate, age structure, sex ratio, density. Population density = N/space. Carrying capacity (K): maximum population size an environment can support." },
      { heading: "Population Growth Models", content: "Exponential growth (dN/dt = rN): unlimited resources, J-shaped curve. Logistic growth (Verhulst-Pearl equation: dN/dt = rN[(K–N)/K]): S-shaped (sigmoid), more realistic." },
      { heading: "Population Interactions", content: "Predation (–/+), Competition (–/–), Mutualism (+/+), Commensalism (+/0), Amensalism (–/0), Parasitism (–/+). Lotka-Volterra equations: predator-prey oscillations." },
    ],
    keyFormulas: [
      { label: "Exponential growth", formula: "dN/dt = rN; Nt = N₀e^(rt)" },
      { label: "Logistic growth", formula: "dN/dt = rN[(K–N)/K]" },
    ],
    keyPoints: ["Gause's competitive exclusion principle: two species competing for same resources cannot coexist (one out-competes the other).", "r-selected species: many offspring, low parental care (insects). K-selected: few offspring, high parental care (elephants).", "Niche: role of an organism in the ecosystem (total ecological role)."],
    hasSimulation: true,
    simulationDescription: "Population growth simulator — compare exponential vs logistic growth curves with variable r and K.",
    sampleQuestions: [
      { question: "Logistic growth shows:", options: ["J-shaped curve", "S-shaped curve", "Exponential increase", "Hyperbolic curve"], answer: 1 },
      { question: "When N=K in logistic growth, population growth rate is:", options: ["Maximum", "Zero", "Negative", "Constant"], answer: 1 },
      { question: "Mutualism is a (+/+) interaction. Example:", options: ["Predation", "Competition", "Mycorrhiza-plant", "Parasitism"], answer: 2 },
    ],
    prevChapterId: "chapter-10", nextChapterId: "chapter-12",
  },
  {
    chapterId: "chapter-12", order: 12,
    title: "Ecosystem",
    objective: "Study ecosystem components, energy flow, nutrient cycling, productivity, and succession.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Ecosystem Components", content: "Abiotic: climate, soil, water, nutrients. Biotic: producers (autotrophs), consumers (primary/secondary/tertiary), decomposers (bacteria, fungi)." },
      { heading: "Energy Flow and Food Web", content: "Energy flows from producers → consumers (unidirectional, non-cyclic). 10% rule (Lindemann): only 10% energy transferred between trophic levels. Pyramids: number, biomass, energy (only energy is always upright)." },
      { heading: "Biogeochemical Cycles", content: "Carbon cycle: CO₂ → photosynthesis → respiration/decomposition → CO₂. Nitrogen cycle: fixation → nitrification → assimilation → ammonification → denitrification. Phosphorus cycle (no gaseous phase)." },
      { heading: "Ecological Succession", content: "Primary: begins on bare rock/sand (pioneer species → climax community). Secondary: faster, begins where soil exists. Succession increases species diversity, biomass, and stability." },
    ],
    keyFormulas: [
      { label: "10% rule (Lindemann)", formula: "Energy at level n+1 = 10% of energy at level n" },
      { label: "Net Primary Productivity", formula: "NPP = GPP – R (R = respiration)" },
    ],
    keyPoints: ["Only energy pyramid is always upright; biomass and number pyramids can be inverted.", "Pioneer species in primary succession: lichens (on bare rock).", "Secondary succession is faster because soil and seeds already exist."],
    hasSimulation: true,
    simulationDescription: "Energy flow in ecosystem — trace energy transfer through food chain trophic levels.",
    sampleQuestions: [
      { question: "At which trophic level is energy maximum in an ecosystem?", options: ["Herbivores", "Carnivores", "Producers", "Decomposers"], answer: 2 },
      { question: "NPP = GPP – ?", options: ["Photosynthesis", "Respiration", "Decomposition", "Predation"], answer: 1 },
      { question: "Energy transfer efficiency between trophic levels is:", options: ["100%", "50%", "10%", "1%"], answer: 2 },
    ],
    prevChapterId: "chapter-11", nextChapterId: "chapter-13",
  },
  {
    chapterId: "chapter-13", order: 13,
    title: "Biodiversity and Conservation",
    objective: "Study types of biodiversity, threats, hotspots, and conservation strategies.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Types of Biodiversity", content: "Genetic diversity (within species), Species diversity (number of species in an area), Ecological diversity (variety of ecosystems). ~1.7 million species described; estimated 5-50 million total." },
      { heading: "Biodiversity Importance", content: "Direct uses: food, medicine, industrial products. Indirect (ecosystem services): pollination, water purification, climate regulation, nutrient cycling. Existence value." },
      { heading: "Threats to Biodiversity", content: "HIPPO: Habitat loss (main threat), Invasive species, Pollution, Population (human), Overhunting (over-exploitation). Sixth mass extinction is currently ongoing." },
      { heading: "Conservation Strategies", content: "In-situ: protect in natural habitat (wildlife sanctuaries, national parks, biosphere reserves, Ramsar sites for wetlands). Ex-situ: seed banks, zoos, cryopreservation, tissue culture." },
    ],
    keyFormulas: [],
    keyPoints: ["India: one of 12 megadiversity countries (biodiversity hotspots: Western Ghats, Eastern Himalayas).", "IUCN Red List: Extinct, Critically Endangered, Endangered, Vulnerable, Near Threatened, Least Concern.", "Project Tiger (1973) — conservation of Bengal tiger; Project Elephant — elephant conservation."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Main cause of biodiversity loss:", options: ["Pollution", "Invasive species", "Habitat destruction", "Over-exploitation"], answer: 2 },
      { question: "Ex-situ conservation includes:", options: ["National parks", "Biosphere reserves", "Seed banks and zoos", "Wildlife sanctuaries"], answer: 2 },
      { question: "Hotspots of biodiversity in India include:", options: ["Thar desert", "Western Ghats", "Gangetic plain", "Deccan plateau"], answer: 1 },
    ],
    prevChapterId: "chapter-12", nextChapterId: "chapter-14",
  },
  {
    chapterId: "chapter-14", order: 14,
    title: "Environmental Issues",
    objective: "Study air, water, and soil pollution, global warming, ozone depletion, deforestation, and agro-chemicals.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Air Pollution", content: "SPM (Suspended Particulate Matter), SO₂, NOₓ, CO, CO₂, O₃ (ground level). Acid rain: pH < 5.6 (due to SO₂ + NOₓ + water). Photochemical smog: O₃ + PAN + acrolein (sunlight + NOₓ + VOCs)." },
      { heading: "Water and Soil Pollution", content: "Water: sewage (BOD), industrial effluents (heavy metals: Pb, Hg, Cd), agricultural runoff (pesticides, fertilizers → eutrophication). Biomagnification: DDT concentration increases up food chain. Soil: pesticides, industrial waste." },
      { heading: "Greenhouse Effect and Global Warming", content: "CO₂, CH₄, N₂O, CFCs, H₂O vapor trap IR radiation. Effects: ice melting, sea level rise, climate change, extreme weather. Solutions: reduce emissions, renewable energy, afforestation." },
      { heading: "Deforestation and Remediation", content: "Deforestation causes: habitat loss, climate change, soil erosion. Reforestation/afforestation: planting trees. Chipko movement: local people hugging trees to prevent cutting. Joint Forest Management programs." },
    ],
    keyFormulas: [],
    keyPoints: ["BOD: biological oxygen demand — higher BOD = more polluted water.", "Minamata disease: mercury poisoning (from industrial effluent, Japan). Itai-itai: cadmium poisoning.", "E-waste: hazardous waste from electronics — requires special disposal."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Acid rain is caused mainly by:", options: ["CO₂ and CO", "SO₂ and NOₓ", "CH₄ and O₃", "CFC and CO₂"], answer: 1 },
      { question: "Biomagnification is maximum in:", options: ["Producers", "Primary consumers", "Secondary consumers", "Top predators"], answer: 3 },
      { question: "Chipko movement was related to:", options: ["Water conservation", "Tree protection", "Soil conservation", "Wildlife protection"], answer: 1 },
    ],
    prevChapterId: "chapter-13", nextChapterId: undefined,
  },
];
