/**
 * @file lib/content/class10-social-science.ts
 * @description Real, NCERT-aligned Class 10 Social Science curriculum content
 * (History, Geography, Political Science, Economics — 2025-26 edition).
 */

import type { ContentChapter } from "./class9-mathematics";

export const CLASS_10_SOCIAL_SCIENCE_CHAPTERS: ContentChapter[] = [
  { chapterId: "chapter-01", order: 1,  title: "The Rise of Nationalism in Europe",   objective: "Study the emergence of nation-states and unification of Germany/Italy.", durationLabel: "3 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], nextChapterId: "chapter-02" },
  { chapterId: "chapter-02", order: 2,  title: "Nationalism in India",                objective: "Study the Non-Cooperation and Civil Disobedience movements.",             durationLabel: "3 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-01", nextChapterId: "chapter-03" },
  { chapterId: "chapter-03", order: 3,  title: "The Making of a Global World",        objective: "Study globalisation through history — trade, migration, and colonialism.", durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-02", nextChapterId: "chapter-04" },
  { chapterId: "chapter-04", order: 4,  title: "The Age of Industrialisation",        objective: "Study the growth of industries in Britain and India.",                    durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-03", nextChapterId: "chapter-05" },
  { chapterId: "chapter-05", order: 5,  title: "Print Culture and the Modern World",  objective: "Study the history of print and its social impact.",                       durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-04", nextChapterId: "chapter-06" },
  { chapterId: "chapter-06", order: 6,  title: "Resources and Development",          objective: "Classify resources and study land/soil resources of India.",              durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-05", nextChapterId: "chapter-07" },
  { chapterId: "chapter-07", order: 7,  title: "Forest and Wildlife Resources",      objective: "Study biodiversity conservation and types of forests in India.",           durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-06", nextChapterId: "chapter-08" },
  { chapterId: "chapter-08", order: 8,  title: "Water Resources",                     objective: "Study water scarcity, multipurpose river projects, and rainwater harvesting.", durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-07", nextChapterId: "chapter-09" },
  { chapterId: "chapter-09", order: 9,  title: "Agriculture",                        objective: "Study farming types, cropping patterns, and the Green Revolution.",        durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-08", nextChapterId: "chapter-10" },
  { chapterId: "chapter-10", order: 10, title: "Minerals and Energy Resources",      objective: "Classify minerals and conventional/non-conventional energy sources.",      durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-09", nextChapterId: "chapter-11" },
  { chapterId: "chapter-11", order: 11, title: "Power Sharing",                      objective: "Study forms of power sharing with case studies (Belgium, Sri Lanka).",     durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-10", nextChapterId: "chapter-12" },
  { chapterId: "chapter-12", order: 12, title: "Federalism",                         objective: "Study federal government structure and decentralisation in India.",        durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-11", nextChapterId: "chapter-13" },
  { chapterId: "chapter-13", order: 13, title: "Political Parties",                  objective: "Study the party system, national/state parties, and challenges.",          durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-12", nextChapterId: "chapter-14" },
  { chapterId: "chapter-14", order: 14, title: "Outcomes of Democracy",              objective: "Evaluate democracy's performance on accountability and quality of life.",   durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-13", nextChapterId: "chapter-15" },
  { chapterId: "chapter-15", order: 15, title: "Development",                        objective: "Study national income, comparison of development, and sustainability.",    durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-14", nextChapterId: "chapter-16" },
  { chapterId: "chapter-16", order: 16, title: "Sectors of the Indian Economy",      objective: "Classify economic activities into primary, secondary, and tertiary sectors.", durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-15", nextChapterId: "chapter-17" },
  { chapterId: "chapter-17", order: 17, title: "Money and Credit",                   objective: "Study the role of money, banks, and credit in the economy.",              durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-16", nextChapterId: "chapter-18" },
  { chapterId: "chapter-18", order: 18, title: "Globalisation and the Indian Economy", objective: "Study MNCs, trade barriers, and the impact of globalisation.",           durationLabel: "2 days", theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-17", nextChapterId: "chapter-19" },
  { chapterId: "chapter-19", order: 19, title: "Consumer Rights",                    objective: "Study consumer protection laws and redressal mechanisms in India.",        durationLabel: "1 day",  theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-18", nextChapterId: "chapter-20" },
  { chapterId: "chapter-20", order: 20, title: "Challenges to Democracy",            objective: "Analyse contemporary challenges facing democratic institutions.",          durationLabel: "1 day",  theoryPoints: [], keyFormulas: [], keyPoints: [], hasSimulation: false, sampleQuestions: [], prevChapterId: "chapter-19" },
];
