/**
 * @file lib/content/class12-mathematics.ts
 * @description NCERT-aligned Class 12 Mathematics curriculum content
 * Every chapter matches NCERT Class 12 Mathematics (2025-26 edition)
 */

import type { ContentChapter } from "./class9-mathematics";

export const CLASS_12_MATHEMATICS_CHAPTERS: ContentChapter[] = [
  {
    chapterId: "chapter-01", order: 1,
    title: "Relations and Functions",
    objective: "Study types of relations (reflexive, symmetric, transitive), types of functions, binary operations, and composition.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Types of Relations", content: "Reflexive: (a,a) ∈ R for all a. Symmetric: if (a,b) ∈ R then (b,a) ∈ R. Transitive: (a,b) and (b,c) in R implies (a,c) in R. Equivalence relation: all three." },
      { heading: "Types of Functions", content: "One-One (injective): f(a)=f(b) ⟹ a=b. Onto (surjective): range=codomain. Bijective: both. Invertible: bijective functions have inverse f⁻¹." },
      { heading: "Composition of Functions", content: "If f: A→B and g: B→C, then gof: A→C defined by gof(x) = g(f(x)). Composition is generally not commutative." },
      { heading: "Binary Operations", content: "A binary operation * on set A: a*b ∈ A for all a,b ∈ A. Commutative: a*b=b*a. Associative: (a*b)*c=a*(b*c). Identity: a*e=e*a=a." },
    ],
    keyFormulas: [
      { label: "Number of equivalence relations on {1,2} is", formula: "2 (trivial {(1,1),(2,2)} and full {(1,1),(1,2),(2,1),(2,2)})" },
      { label: "Composition (gof)(x)", formula: "g(f(x))" },
    ],
    keyPoints: ["An equivalence relation partitions the set into equivalence classes.", "A function is invertible iff it is bijective.", "The identity element for composition of functions is the identity function f(x)=x."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "R = {(1,2),(2,1)} on {1,2} is:", options: ["Reflexive", "Symmetric", "Transitive", "Equivalence"], answer: 1 },
      { question: "f(x) = x² on R is:", options: ["Injective only", "Surjective only", "Bijective", "Neither"], answer: 3 },
      { question: "If f(x)=x+1 and g(x)=x², then gof(2) =", options: ["9", "5", "4", "8"], answer: 0 },
    ],
    prevChapterId: undefined, nextChapterId: "chapter-02",
  },
  {
    chapterId: "chapter-02", order: 2,
    title: "Inverse Trigonometric Functions",
    objective: "Understand inverse trig functions, their domains, ranges, and properties.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Definition and Domain/Range", content: "sin⁻¹ x: domain [–1,1], range [–π/2, π/2]. cos⁻¹ x: domain [–1,1], range [0, π]. tan⁻¹ x: domain R, range (–π/2, π/2)." },
      { heading: "Principal Values", content: "The principal value is the value in the principal branch. E.g., sin⁻¹(1/2) = π/6 (not 5π/6)." },
      { heading: "Properties", content: "sin⁻¹(–x) = –sin⁻¹x; cos⁻¹(–x) = π–cos⁻¹x; sin⁻¹x + cos⁻¹x = π/2; tan⁻¹x + cot⁻¹x = π/2." },
    ],
    keyFormulas: [
      { label: "sin⁻¹x + cos⁻¹x", formula: "π/2 (for x ∈ [–1,1])" },
      { label: "tan⁻¹x + cot⁻¹x", formula: "π/2 (for x ∈ R)" },
      { label: "tan⁻¹x + tan⁻¹y", formula: "tan⁻¹((x+y)/(1–xy)) if xy < 1" },
    ],
    keyPoints: ["Inverse trig functions have restricted domains to make them injective.", "sin⁻¹(sin x) = x only for x ∈ [–π/2, π/2].", "sin(sin⁻¹ x) = x for x ∈ [–1, 1]."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "sin⁻¹(1) = ?", options: ["π", "π/2", "π/4", "π/3"], answer: 1 },
      { question: "cos⁻¹(–1/2) = ?", options: ["π/3", "2π/3", "π/6", "5π/6"], answer: 1 },
      { question: "sin⁻¹x + cos⁻¹x = ?", options: ["π", "π/2", "0", "2π"], answer: 1 },
    ],
    prevChapterId: "chapter-01", nextChapterId: "chapter-03",
  },
  {
    chapterId: "chapter-03", order: 3,
    title: "Matrices",
    objective: "Understand types of matrices, matrix operations, transpose, and elementary row/column operations.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Types of Matrices", content: "Row matrix, Column matrix, Square matrix, Diagonal matrix, Scalar matrix, Identity (unit) matrix, Zero matrix, Symmetric (A=Aᵀ), Skew-symmetric (A=–Aᵀ)." },
      { heading: "Matrix Operations", content: "Addition/Subtraction: element-wise (same order). Multiplication: (A×B)ᵢⱼ = Σ AᵢₖBₖⱼ. Condition: columns of A = rows of B." },
      { heading: "Transpose", content: "(Aᵀ)ᵢⱼ = Aⱼᵢ. Properties: (Aᵀ)ᵀ=A; (A+B)ᵀ=Aᵀ+Bᵀ; (AB)ᵀ=BᵀAᵀ." },
      { heading: "Special Results", content: "For square matrix A: A+Aᵀ is always symmetric; A–Aᵀ is always skew-symmetric. Any square matrix can be expressed as sum of a symmetric and skew-symmetric matrix." },
    ],
    keyFormulas: [
      { label: "Matrix multiplication (m×n)(n×p) = m×p matrix", formula: "(AB)ᵢⱼ = Σₖ AᵢₖBₖⱼ" },
      { label: "Symmetric part of A", formula: "½(A + Aᵀ)" },
      { label: "Skew-symmetric part of A", formula: "½(A – Aᵀ)" },
    ],
    keyPoints: ["Matrix multiplication is not commutative in general: AB ≠ BA.", "The identity matrix I acts as the multiplicative identity: AI = IA = A.", "A square matrix A is invertible iff det(A) ≠ 0."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "Order of product of 2×3 and 3×4 matrices is:", options: ["3×3", "2×4", "3×4", "4×2"], answer: 1 },
      { question: "If A is a 3×3 skew-symmetric matrix, then A = ?", options: ["Aᵀ", "–Aᵀ", "A⁻¹", "2A"], answer: 1 },
      { question: "For identity matrix I: A × I = ?", options: ["I", "A", "0", "Aᵀ"], answer: 1 },
    ],
    prevChapterId: "chapter-02", nextChapterId: "chapter-04",
  },
  {
    chapterId: "chapter-04", order: 4,
    title: "Determinants",
    objective: "Evaluate determinants, apply properties, find adjoint and inverse of a matrix, and use Cramer's rule.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Determinant of a Matrix", content: "For 2×2: |A| = ad–bc. For 3×3: expand along a row using cofactors. A 3×3 determinant has 3 terms." },
      { heading: "Properties of Determinants", content: "det(A) = det(Aᵀ). If two rows are identical, det = 0. Interchanging two rows changes sign. Multiplying a row by k multiplies det by k." },
      { heading: "Adjoint and Inverse", content: "adj(A) = transpose of cofactor matrix. A⁻¹ = adj(A)/det(A). Exists only if det(A) ≠ 0." },
      { heading: "Applications", content: "Cramer's rule for solving AX=B: x = det(A₁)/det(A), y = det(A₂)/det(A), z = det(A₃)/det(A)." },
    ],
    keyFormulas: [
      { label: "2×2 determinant", formula: "|A| = ad – bc for [[a,b],[c,d]]" },
      { label: "Inverse matrix", formula: "A⁻¹ = adj(A) / det(A)" },
      { label: "Area of triangle", formula: "½ |x₁(y₂–y₃) + x₂(y₃–y₁) + x₃(y₁–y₂)|" },
    ],
    keyPoints: ["det(AB) = det(A) × det(B).", "If det(A) = 0, the system AX=B has no unique solution.", "A matrix times its adjoint = det(A) × I."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "det([[2,3],[1,4]]) = ?", options: ["5", "11", "8", "–5"], answer: 0 },
      { question: "If |A| = 5, then |adj(A)| for 3×3 matrix A = ?", options: ["5", "25", "125", "15"], answer: 1 },
      { question: "A square matrix is singular when:", options: ["det = 1", "det = 0", "det > 0", "det < 0"], answer: 1 },
    ],
    prevChapterId: "chapter-03", nextChapterId: "chapter-05",
  },
  {
    chapterId: "chapter-05", order: 5,
    title: "Continuity and Differentiability",
    objective: "Understand continuity, differentiability, chain rule, logarithmic differentiation, and implicit differentiation.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Continuity", content: "f(x) is continuous at x=a if: f(a) is defined; lim(x→a) f(x) exists; lim(x→a) f(x) = f(a). Polynomials, rational functions (at non-zero denominator), trigonometric functions are continuous." },
      { heading: "Differentiability", content: "f is differentiable at x=a if f'(a) = lim(h→0) [f(a+h)–f(a)]/h exists. Differentiability implies continuity, but not vice versa." },
      { heading: "Rules of Differentiation", content: "Product rule: (uv)' = u'v + uv'. Quotient rule: (u/v)' = (u'v–uv')/v². Chain rule: d/dx f(g(x)) = f'(g(x))·g'(x)." },
      { heading: "Higher Order Derivatives", content: "Second derivative f''(x) = d²y/dx². Used in finding maxima/minima: if f'(a)=0 and f''(a)<0, local max; f''(a)>0, local min." },
    ],
    keyFormulas: [
      { label: "d/dx (uv)", formula: "u'v + uv' (product rule)" },
      { label: "d/dx (u/v)", formula: "(u'v – uv')/v²" },
      { label: "d/dx (xⁿ)", formula: "nxⁿ⁻¹" },
      { label: "d/dx (eˣ)", formula: "eˣ" },
      { label: "d/dx (ln x)", formula: "1/x" },
      { label: "d/dx (sin⁻¹x)", formula: "1/√(1–x²)" },
      { label: "d/dx (tan⁻¹x)", formula: "1/(1+x²)" },
    ],
    keyPoints: ["Logarithmic differentiation is used for y = f(x)^g(x) type functions.", "Implicit differentiation: differentiate both sides w.r.t. x, treating y as function of x.", "Rolle's theorem: if f(a)=f(b) and f is cont. on [a,b], then f'(c)=0 for some c ∈ (a,b)."],
    hasSimulation: true,
    simulationDescription: "Derivative function plotter — visualize f(x) and f'(x) simultaneously to understand continuity and differentiability.",
    sampleQuestions: [
      { question: "d/dx (sin x · eˣ) = ?", options: ["cos x · eˣ", "sin x · eˣ", "eˣ(cos x + sin x)", "eˣ(cos x – sin x)"], answer: 2 },
      { question: "If y = ln x, then dy/dx = ?", options: ["1/x²", "1/x", "ln x", "x"], answer: 1 },
      { question: "d/dx (tan⁻¹ x) = ?", options: ["1/(1–x²)", "1/(1+x²)", "1/√(1–x²)", "–1/(1+x²)"], answer: 1 },
    ],
    prevChapterId: "chapter-04", nextChapterId: "chapter-06",
  },
  {
    chapterId: "chapter-06", order: 6,
    title: "Application of Derivatives",
    objective: "Apply derivatives to find rate of change, tangents/normals, maxima/minima, and monotonicity.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Rate of Change", content: "dy/dx represents the rate of change of y with respect to x. E.g., if V = volume of sphere, dV/dt = 4πr² × dr/dt." },
      { heading: "Tangent and Normal", content: "Slope of tangent at (x₁,y₁): m = f'(x₁). Equation of tangent: y–y₁ = m(x–x₁). Normal slope = –1/m; equation similarly." },
      { heading: "Increasing and Decreasing Functions", content: "f is increasing on (a,b) if f'(x) > 0. Decreasing if f'(x) < 0. f'(x) = 0 at stationary points." },
      { heading: "Maxima and Minima", content: "First derivative test: sign change of f'(x) at critical point. Second derivative test: f''(x)<0 → max, f''(x)>0 → min, f''(x)=0 → test fails." },
    ],
    keyFormulas: [
      { label: "Tangent equation", formula: "y – y₁ = f'(x₁)(x – x₁)" },
      { label: "Normal slope", formula: "–1/f'(x₁)" },
      { label: "Approximation", formula: "Δy ≈ f'(x)·Δx" },
    ],
    keyPoints: ["A function has absolute maximum/minimum in a closed interval — check critical points and endpoints.", "Rolle's theorem applies when f(a)=f(b).", "Mean value theorem: f'(c) = [f(b)–f(a)]/(b–a) for some c in (a,b)."],
    hasSimulation: true,
    simulationDescription: "Maxima-minima explorer — plot functions and see tangents, critical points, and local extrema interactively.",
    sampleQuestions: [
      { question: "Slope of tangent to y = x² at x = 3 is:", options: ["6", "9", "3", "18"], answer: 0 },
      { question: "f(x) = x³ – 3x has local minimum at:", options: ["x=0", "x=1", "x=–1", "x=3"], answer: 1 },
      { question: "Approximate value of √25.1 using derivatives:", options: ["5.01", "5.1", "5.001", "5.005"], answer: 0 },
    ],
    prevChapterId: "chapter-05", nextChapterId: "chapter-07",
  },
  {
    chapterId: "chapter-07", order: 7,
    title: "Integrals",
    objective: "Master indefinite and definite integration — standard formulas, substitution, by parts, and partial fractions.",
    durationLabel: "8 days",
    theoryPoints: [
      { heading: "Antiderivative (Indefinite Integral)", content: "∫f(x)dx = F(x) + C, where F'(x) = f(x). The +C is the constant of integration." },
      { heading: "Standard Integrals", content: "∫xⁿ dx = xⁿ⁺¹/(n+1)+C (n≠–1); ∫eˣ dx = eˣ+C; ∫1/x dx = ln|x|+C; ∫sin x dx = –cos x+C; ∫cos x dx = sin x+C; ∫sec²x dx = tan x+C." },
      { heading: "Definite Integral", content: "∫ₐᵇ f(x)dx = F(b)–F(a) (Fundamental Theorem of Calculus). Represents area under the curve f(x) from a to b." },
      { heading: "Integration by Parts", content: "∫u dv = uv – ∫v du. Use ILATE rule: Inverse trig, Logarithmic, Algebraic, Trigonometric, Exponential — for choosing u." },
      { heading: "Integration by Partial Fractions", content: "Decompose rational functions into simpler fractions before integrating. E.g., 1/[(x+1)(x+2)] = 1/(x+1) – 1/(x+2)." },
    ],
    keyFormulas: [
      { label: "∫xⁿ dx", formula: "xⁿ⁺¹/(n+1) + C, n ≠ –1" },
      { label: "∫eˣ dx", formula: "eˣ + C" },
      { label: "∫1/x dx", formula: "ln|x| + C" },
      { label: "∫sin x dx", formula: "–cos x + C" },
      { label: "∫cos x dx", formula: "sin x + C" },
      { label: "∫ by parts", formula: "∫u·v dx = u·∫v dx – ∫[u'·∫v dx] dx" },
    ],
    keyPoints: ["Definite integral of an odd function over symmetric interval [–a,a] = 0.", "∫ₐᵇ f(x)dx = –∫ᵦₐ f(x)dx.", "Properties: ∫ₐᵇ f(x)dx = ∫ₐᶜ f(x)dx + ∫ᶜᵇ f(x)dx."],
    hasSimulation: true,
    simulationDescription: "Area under curve visualizer — see definite integral as area and approximate using Riemann sums.",
    sampleQuestions: [
      { question: "∫x³ dx = ?", options: ["x⁴/4 + C", "3x² + C", "x⁴ + C", "x³/3 + C"], answer: 0 },
      { question: "∫₀² 2x dx = ?", options: ["4", "2", "8", "0"], answer: 0 },
      { question: "∫eˣ dx = ?", options: ["eˣ + C", "eˣ/x + C", "xeˣ + C", "eˣ·x + C"], answer: 0 },
    ],
    prevChapterId: "chapter-06", nextChapterId: "chapter-08",
  },
  {
    chapterId: "chapter-08", order: 8,
    title: "Application of Integrals",
    objective: "Use definite integrals to find areas bounded by curves and lines.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "Area Between Curves", content: "Area between y=f(x) and y=g(x) from a to b (f≥g): A = ∫ₐᵇ [f(x) – g(x)] dx." },
      { heading: "Area Under a Curve", content: "Area between y=f(x), x-axis, and x=a, x=b: A = ∫ₐᵇ |f(x)| dx." },
    ],
    keyFormulas: [
      { label: "Area under curve", formula: "A = ∫ₐᵇ f(x) dx (if f≥0)" },
      { label: "Area between two curves", formula: "A = ∫ₐᵇ [f(x) – g(x)] dx (f ≥ g)" },
    ],
    keyPoints: ["If f(x) < 0 in [a,b], the area is ∫ₐᵇ |f(x)|dx = –∫ₐᵇ f(x)dx.", "Area of circle x²+y²=r² is πr² (by integration).", "Area of ellipse x²/a²+y²/b²=1 is πab."],
    hasSimulation: true,
    simulationDescription: "Area calculation visualizer — shade area between curves and compute using integration.",
    sampleQuestions: [
      { question: "Area under y=x from x=0 to x=4:", options: ["8", "16", "4", "2"], answer: 0 },
      { question: "Area enclosed by y=x² and y=x is:", options: ["1/6", "1/3", "1/2", "1"], answer: 0 },
      { question: "Area of region bounded by y=√x, x=0, x=4, x-axis:", options: ["8/3", "16/3", "4", "8"], answer: 1 },
    ],
    prevChapterId: "chapter-07", nextChapterId: "chapter-09",
  },
  {
    chapterId: "chapter-09", order: 9,
    title: "Differential Equations",
    objective: "Understand differential equations — order, degree, general solutions, and variable separable method.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Order and Degree", content: "Order: highest derivative present. Degree: power of the highest order derivative (when equation is free of fractions/radicals in derivatives)." },
      { heading: "General and Particular Solutions", content: "General solution contains arbitrary constants (equal to order). Particular solution obtained by applying initial conditions." },
      { heading: "Variable Separable Method", content: "Separate variables: f(y)dy = g(x)dx, then integrate both sides." },
      { heading: "Linear Differential Equations", content: "dy/dx + Py = Q (P, Q functions of x). Integrating factor: μ = e^(∫P dx). Solution: y·μ = ∫Q·μ dx + C." },
    ],
    keyFormulas: [
      { label: "Linear DE solution", formula: "y·e^(∫P dx) = ∫Q·e^(∫P dx) dx + C" },
      { label: "Variable separable", formula: "∫f(y) dy = ∫g(x) dx + C" },
    ],
    keyPoints: ["A differential equation of order n has n arbitrary constants in its general solution.", "Homogeneous DE: dy/dx = F(y/x), use y = vx substitution.", "Growth/decay: dN/dt = kN → N = N₀eᵏᵗ."],
    hasSimulation: true,
    simulationDescription: "Differential equation solution plotter — see solution curves for different initial conditions (direction field).",
    sampleQuestions: [
      { question: "Order of d²y/dx² + dy/dx + y = 0:", options: ["1", "2", "3", "0"], answer: 1 },
      { question: "Solution of dy/dx = y gives:", options: ["y = Cx", "y = Ce^x", "y = C ln x", "y = C + x"], answer: 1 },
      { question: "Integrating factor of dy/dx + y/x = x is:", options: ["1/x", "x", "ln x", "x²"], answer: 1 },
    ],
    prevChapterId: "chapter-08", nextChapterId: "chapter-10",
  },
  {
    chapterId: "chapter-10", order: 10,
    title: "Vector Algebra",
    objective: "Study vectors, dot product, cross product, and their applications in geometry.",
    durationLabel: "4 days",
    theoryPoints: [
      { heading: "Vectors", content: "A vector has magnitude and direction. Position vector of point P(x,y,z): r = xî + yĵ + zk̂. |r| = √(x²+y²+z²)." },
      { heading: "Dot Product (Scalar Product)", content: "a·b = |a||b|cosθ = a₁b₁ + a₂b₂ + a₃b₃. If a·b=0, vectors are perpendicular." },
      { heading: "Cross Product (Vector Product)", content: "a×b has magnitude |a||b|sinθ and direction by right-hand rule. |a×b| = area of parallelogram. a×b = –b×a." },
    ],
    keyFormulas: [
      { label: "Dot product", formula: "a·b = |a||b|cosθ" },
      { label: "Cross product magnitude", formula: "|a×b| = |a||b|sinθ" },
      { label: "Unit vector", formula: "â = a/|a|" },
      { label: "Projection of a on b", formula: "(a·b)/|b|" },
    ],
    keyPoints: ["î·î = ĵ·ĵ = k̂·k̂ = 1; î·ĵ = ĵ·k̂ = k̂·î = 0.", "î×ĵ = k̂; ĵ×k̂ = î; k̂×î = ĵ.", "Scalar triple product a·(b×c) gives volume of parallelepiped."],
    hasSimulation: true,
    simulationDescription: "3D vector visualizer — add, subtract vectors, visualize dot and cross products in 3D space.",
    sampleQuestions: [
      { question: "If a·b = 0, vectors are:", options: ["Parallel", "Perpendicular", "Equal", "Opposite"], answer: 1 },
      { question: "|a×b| if |a|=2, |b|=3, θ=90° is:", options: ["6", "0", "5", "√13"], answer: 0 },
      { question: "î × ĵ = ?", options: ["î", "ĵ", "k̂", "–k̂"], answer: 2 },
    ],
    prevChapterId: "chapter-09", nextChapterId: "chapter-11",
  },
  {
    chapterId: "chapter-11", order: 11,
    title: "Three Dimensional Geometry",
    objective: "Study direction cosines, equations of lines and planes in 3D, and their mutual relationships.",
    durationLabel: "5 days",
    theoryPoints: [
      { heading: "Direction Cosines and Ratios", content: "If line makes angles α, β, γ with x, y, z axes: l=cosα, m=cosβ, n=cosγ are direction cosines. l²+m²+n²=1. Direction ratios a,b,c are proportional to l,m,n." },
      { heading: "Equation of Line", content: "Through A(x₁,y₁,z₁) with direction (a,b,c): (x–x₁)/a = (y–y₁)/b = (z–z₁)/c (symmetric). Vector form: r = a + λb." },
      { heading: "Equation of Plane", content: "General: ax+by+cz=d. Vector form: r·n̂ = d. Three-point form: from three given points." },
      { heading: "Angle and Distance", content: "Angle between lines with directions (l₁,m₁,n₁) and (l₂,m₂,n₂): cosθ = |l₁l₂+m₁m₂+n₁n₂|. Distance from point to plane: |ax₁+by₁+cz₁–d|/√(a²+b²+c²)." },
    ],
    keyFormulas: [
      { label: "Direction cosines constraint", formula: "l² + m² + n² = 1" },
      { label: "Line vector form", formula: "r = a + λb" },
      { label: "Plane equation (intercept form)", formula: "x/a + y/b + z/c = 1" },
      { label: "Distance point to plane", formula: "|ax₁+by₁+cz₁–d| / √(a²+b²+c²)" },
    ],
    keyPoints: ["Two lines are perpendicular if l₁l₂+m₁m₂+n₁n₂=0; parallel if l₁/l₂=m₁/m₂=n₁/n₂.", "Two planes are perpendicular if a₁a₂+b₁b₂+c₁c₂=0.", "Shortest distance between skew lines = |( a₂–a₁)·(b₁×b₂)| / |b₁×b₂|."],
    hasSimulation: true,
    simulationDescription: "3D geometry visualizer — plot lines, planes, and their intersections in three dimensions.",
    sampleQuestions: [
      { question: "If direction ratios of line are (2,3,6), direction cosines include:", options: ["l=2/7", "l=2/3", "l=1/2", "l=3/7"], answer: 0 },
      { question: "Equation x/2 + y/3 + z/4 = 1 is a plane in:", options: ["Standard form", "Intercept form", "Vector form", "Normal form"], answer: 1 },
      { question: "Angle between planes is determined by their:", options: ["Intercepts", "Normal vectors", "Areas", "Distances"], answer: 1 },
    ],
    prevChapterId: "chapter-10", nextChapterId: "chapter-12",
  },
  {
    chapterId: "chapter-12", order: 12,
    title: "Linear Programming",
    objective: "Formulate and solve linear programming problems graphically using corner point method.",
    durationLabel: "3 days",
    theoryPoints: [
      { heading: "LPP Formulation", content: "Objective function (to maximize/minimize), subject to linear constraints and non-negativity conditions." },
      { heading: "Graphical Method", content: "Plot all constraints as half-planes. Feasible region: intersection of all half-planes. Corner point theorem: optimal solution is at a corner point of the feasible region." },
      { heading: "Types of Solutions", content: "Unique optimal solution, Multiple optimal solutions (along an edge), Unbounded solution (no maximum exists), Infeasible (no feasible region)." },
    ],
    keyFormulas: [],
    keyPoints: ["The objective function is always linear in LPP.", "The feasible region must be convex.", "If feasible region is bounded, both max and min exist."],
    hasSimulation: false,
    sampleQuestions: [
      { question: "In LPP, optimal value always occurs at:", options: ["Any point", "Corner point", "Interior point", "Origin"], answer: 1 },
      { question: "If feasible region is empty, the LPP is:", options: ["Unbounded", "Infeasible", "Optimal", "Degenerate"], answer: 1 },
      { question: "Corner point method is used in:", options: ["Simplex method", "Graphical method", "Matrix method", "Derivative method"], answer: 1 },
    ],
    prevChapterId: "chapter-11", nextChapterId: "chapter-13",
  },
  {
    chapterId: "chapter-13", order: 13,
    title: "Probability",
    objective: "Understand conditional probability, multiplication theorem, Bayes' theorem, random variables, and binomial distribution.",
    durationLabel: "6 days",
    theoryPoints: [
      { heading: "Conditional Probability", content: "P(A|B) = P(A∩B)/P(B), provided P(B)>0. It is the probability of A occurring given B has occurred." },
      { heading: "Multiplication Theorem", content: "P(A∩B) = P(A)·P(B|A) = P(B)·P(A|B). For independent events: P(A∩B) = P(A)·P(B)." },
      { heading: "Bayes' Theorem", content: "P(Eᵢ|A) = P(Eᵢ)·P(A|Eᵢ) / Σⱼ P(Eⱼ)·P(A|Eⱼ). Used for finding posterior probabilities." },
      { heading: "Random Variable and Distribution", content: "Random variable X assigns a number to each outcome. Expected value: E(X) = ΣxᵢP(xᵢ). Variance: Var(X) = E(X²) – [E(X)]²." },
      { heading: "Binomial Distribution", content: "X ~ B(n,p): P(X=r) = nCr × pʳ × (1–p)^(n–r). Mean = np, Variance = npq where q=1–p." },
    ],
    keyFormulas: [
      { label: "Conditional probability", formula: "P(A|B) = P(A∩B)/P(B)" },
      { label: "Bayes' theorem", formula: "P(Eᵢ|A) = P(Eᵢ)P(A|Eᵢ) / Σ P(Eⱼ)P(A|Eⱼ)" },
      { label: "Binomial P(X=r)", formula: "nCr × pʳ × qⁿ⁻ʳ" },
      { label: "Mean of B(n,p)", formula: "np" },
      { label: "Variance of B(n,p)", formula: "npq (q = 1–p)" },
    ],
    keyPoints: ["If P(A|B) = P(A), A and B are independent.", "Total probability theorem: P(A) = ΣP(Eᵢ)·P(A|Eᵢ).", "Bernoulli trials: n independent trials, each with probability p of success."],
    hasSimulation: true,
    simulationDescription: "Binomial distribution visualizer — see probability distribution histogram for different n and p values.",
    sampleQuestions: [
      { question: "P(A) = 0.3, P(B) = 0.4, P(A∩B) = 0.12. Are A and B independent?", options: ["Yes", "No", "Cannot determine", "Only in some cases"], answer: 0 },
      { question: "In B(5, 0.5), P(X=3) = ?", options: ["5/16", "5/32", "10/32", "3/16"], answer: 2 },
      { question: "Mean of B(10, 0.4) = ?", options: ["6", "4", "2.4", "8"], answer: 1 },
    ],
    prevChapterId: "chapter-12", nextChapterId: undefined,
  },
];
